### PR TITLE
Make AmplifyService service to be tree shakable

### PR DESCRIPTION
**Pull request by mohammedzamakhan**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by powerful23** [comment]
@mohammedzamakhan can you provide more info about how this change will make it tree shakable? Maybe a doc link or something. Thanks.

**Comment by mohammedzamakhan** [comment]
https://angular.io/guide/dependency-injection-providers#tree-shakable-providers

**Comment by haverchuck** [comment]
@mohammedzamakhan - Thanks for submitting this PR.  Unfortunately, I believe this providedIn functionality was introduced as part of Angular 6, and we are trying to maintain backwards compatibility with versions 5 and up.  We have introduced an alternative means of using only particular Amplify modules, which is described [in our docs](https://aws-amplify.github.io/docs/js/angular#option-2-configuring-the-amplify-provider-with-specified-amplify-js-modules).

**Comment by mohammedzamakhan** [comment]
I don't believe that this is like a breaking change, and will not work in Angular 5. It should still be working with Angular 5 project. The only thing is, they will need to explicitly provide the service in a module

**Pull request closed without merging**
