### PR TITLE
Support Microsoft's react-native-windows (macOS)

### PR DESCRIPTION
**Pull request by mandrigin**
_Issue #, if available:_ N/A

_Description of changes:_

The current version of authenticator in amplify-js not working on react-native on macOS (https://github.com/Microsoft/react-native-windows), it fails with this issue: https://github.com/aws-amplify/amplify-js/issues/3682.

No workaround works because the podfile doesn't allow this code to run on macOS. At the same time, all the code I see there is perfectly valid for macOS, compiles and runs there.

After this change in the Podfile, I am able to compile and run the authenticator on react-native app on macOS.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mandrigin** [comment]
Hmm, I'm not really sure why `yarn install` failed on circleci; there are no JS or dependency changes here...

**Comment by ericclemmons** [comment]
@mandrigin I restarted the build in CircleCI. Also no idea why it failed 🤷

**Comment by mandrigin** [comment]
Thank you! Now it’s a different failure that has nothing to do with iOS 😢. 
Maybe I used a broken commit as the base to my branch?

**Comment by mandrigin** [comment]
@ericclemmons it was super outdated branch for some reason... I've rebased it and let's see how it goes now.

**Comment by sammartinez** [comment]
@mandrigin, Thanks for opening this pull request and contributing. At this time, we are not looking to add this support as we would need to do a full design review and add supporting documentation for this. However, we will take this into consideration for the future as well look further for feature request specific to React Native. Thanks again!

**Comment by mandrigin** [comment]
This was a single config change in a podspec but sure...

**Pull request closed without merging**
