### PR TITLE
fix(@aws-amplify/aws-amplify-react): Improve french translations

### PR DESCRIPTION
**Pull request by ChristopheBougere**
_Description of changes:_

Just improved or added a bunch of french translations.
I must say that it is quite a cumbersome task, and I probably missed some of them because there is no official list of all translations. There are some dynamic strings, or messages depending on thrown Error that makes it very difficult to anticipate everything. I already filed this as a feature request in #3092

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
@ChristopheBougere Thanks for your PR!

I ran into the same issue in #4979 as part of our UI Refactor (#3279).

You can see an example here:
> https://github.com/aws-amplify/amplify-js/blob/ui-components/master/packages/amplify-ui-components/src/components/amplify-sign-in/amplify-sign-in.tsx#L255

The bad news is that there are more strings available in the refactor than `master`.

I'd love to work with you on getting proper translations into #3279.   Your points in #3092 are spot on.

How could I help?

**Comment by ChristopheBougere** [comment]
Hi @ericclemmons 
Great to see that the UI refactor includes a translations centralization!
I'd be happy to take care of french translations. I think there is only English for now (with strings located in [this file](https://github.com/aws-amplify/amplify-js/blob/ui-components/master/packages/amplify-ui-components/src/common/Translations.ts)). What would be the process to add a new language?

**Comment by ericclemmons** [comment]
@ChristopheBougere That's right.  In #4979, I tried to carry forward existing translations, but there the implementations weren't 1-to-1.

What we'll need to do is revert a bit of dc263817d76da3d42f1a19ffd25037f1367ad8d0 so that translations are automatically bootstrapped.

If I setup a PR & lay out how to continue the implementation, would you be able to bring your work over?

**Comment by ChristopheBougere** [comment]
Sure I could do that. Correct me if I'm wrong, but basically it should consist in a translation of all the strings in [this file](https://github.com/aws-amplify/amplify-js/blob/ui-components/master/packages/amplify-ui-components/src/common/Translations.ts)?

**Comment by ericclemmons** [comment]
@ChristopheBougere I'll need a bit to setup the PR, but you're right: it's effectively just a map of those translations:

```ts
import { Translations } from './common/Translations';

export const fr: Record<Translations, string> = {
   ...
   [Translations.SIGN_OUT]: 'Déconnexion',
   ...
}
```

**Comment by ChristopheBougere** [comment]
@ericclemmons sounds good to me, let me know when I can help

**Comment by thibaultdalban** [comment]
@ericclemmons and @ChristopheBougere I'm not sure if it's the right place to post :confused:
I would like to let you know that we just release the first version of an npm package dedicated to the Amplify translations.
Please have a look at https://www.npmjs.com/package/amplify-i18n I would be very interested in your feedback.
Currently, the translations have been done by machine translation but we are going to do an entire review with our professional translators.

**Pull request merged**
