### PR TITLE
Feat/ui form checkbox

### PR DESCRIPTION
**Pull request by nkint**
_Issue #, if available:_

see discussion #5887
fix issue #6440

_Description of changes:_

I tried to enable checkbox in authentication form so that I can use something like this (example with React):

```
				<AmplifyAuthenticator
					usernameAlias="email"
				>
					<AmplifySignUp
						slot="sign-up"
						usernameAlias="email"
						formFields={[
							{
								type: 'email',
								label: 'Custom email',
								placeholder: 'john.doe@email.com',
								required: true,
							},
							{
								type: 'password',
								label: 'Password',
								placeholder: 'A secret password',
								required: true,
							},
							{
								type: 'checkbox',
								label: 'Accept privacy terms.',
								required: true,
							},
						]}
					></AmplifySignUp>
				</AmplifyAuthenticator>
```

I have seen a lot of auto-generated changes, that I commited in a separated commit (2a840de). Please told me if there is something wrong this PR, I will be happy to fix it.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ashika01** [comment]
@nkint Could you try using checkbox in all components that take in `formFields`? Also, test the `inputChange` functionality is not already? I just tried to add checkbox to signIn and something is broke..

**Comment by sammartinez** [comment]
@nkint, To @ashika01 feedback, can you look to adjust this PR to utilize what she has called out? Thanks ahead of time!

**Comment by eddiekeller** [comment]
Hey @nkint , just wanted to double back on this PR. Are you still working on it and updating it with the feedback provided? No worries if not - just let us know and we can close it out for you.

**Comment by nkint** [comment]
hei @eddiekeller thanks for asking.
I'm not working on it anymore.

**Pull request closed without merging**
