### PR TITLE
chore(cognito-identity-js) Add CognitoUserPool.getUserPoolName

### PR DESCRIPTION
**Pull request by razor-x**
#### Description of changes

This `user.pool.getUserPoolId().split('_')[1]` was changed to `user.pool.getUserPoolName` (according to SoC)

#### Issue #, if available

See here for context: https://github.com/aws-amplify/amplify-js/issues/8244

#### Description of how you validated changes

Trivial find / replace. Waiting for tests to pass.

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ashika01** [comment]
@razor-x can you update the branch and give me a ping I can work on getting this merged in. Apologies for delay in response.

**Comment by razor-x** [comment]
> @razor-x can you update the branch and give me a ping I can work on getting this merged in. Apologies for delay in response.

No worries. I've been away since your reply.

<details>
<summary>Tests are passing locally for me:</summary>

```
❯ yarn run test --scope amazon-cognito-identity-js               
yarn run v1.22.19
$ lerna run test --stream --scope amazon-cognito-identity-js
lerna notice cli v3.22.1
lerna info versioning independent
lerna notice filter including "amazon-cognito-identity-js"
lerna info filter [ 'amazon-cognito-identity-js' ]
lerna info Executing command in 1 package: "yarn run test"
amazon-cognito-identity-js: $ jest --config ./jest.config.js
amazon-cognito-identity-js: PASS __tests__/CognitoUserAttribute.test.js (11.843s)
amazon-cognito-identity-js: PASS __tests__/Client.test.js (11.801s)
amazon-cognito-identity-js: PASS __tests__/CookieStorage.test.js (12.024s)
amazon-cognito-identity-js: PASS __tests__/CognitoRefreshToken.test.js (12.204s)
amazon-cognito-identity-js: PASS __tests__/StorageHelperRN.test.js
amazon-cognito-identity-js: PASS __tests__/CognitoUserSession.test.js (12.247s)
amazon-cognito-identity-js: PASS __tests__/CognitoUserPool.test.js (12.14s)
amazon-cognito-identity-js: PASS __tests__/cryptoSecureRandomInt.test.js
amazon-cognito-identity-js: PASS __tests__/DateHelper.test.js
amazon-cognito-identity-js: PASS __tests__/UserAgent.test.js
amazon-cognito-identity-js: PASS __tests__/StorageHelper.test.js
amazon-cognito-identity-js: PASS __tests__/CognitoJwtToken.test.js
amazon-cognito-identity-js: PASS __tests__/index.test.js
amazon-cognito-identity-js: PASS __tests__/CognitoAccessToken.test.js
amazon-cognito-identity-js: PASS __tests__/BigInteger.test.js
amazon-cognito-identity-js: PASS __tests__/AuthenticationDetails.test.js
amazon-cognito-identity-js: PASS __tests__/CognitoIdToken.test.js
amazon-cognito-identity-js: PASS __tests__/UserAgentDefault.test.js
amazon-cognito-identity-js: PASS __tests__/AuthenticationHelper.test.js (15.965s)
amazon-cognito-identity-js: PASS __tests__/CognitoUser.test.js (9.842s)
amazon-cognito-identity-js: --------------------------|----------|----------|----------|----------|-------------------|
amazon-cognito-identity-js: File                      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
amazon-cognito-identity-js: --------------------------|----------|----------|----------|----------|-------------------|
amazon-cognito-identity-js: All files                 |    84.05 |    71.91 |    83.06 |    85.06 |                   |
amazon-cognito-identity-js:  AuthenticationDetails.js |      100 |     87.5 |      100 |      100 |                17 |
amazon-cognito-identity-js:  AuthenticationHelper.js  |      100 |    94.44 |      100 |      100 |           251,253 |
amazon-cognito-identity-js:  BigInteger.js            |    85.93 |    71.13 |    92.68 |    89.45 |... 71,611,613,615 |
amazon-cognito-identity-js:  Client.js                |    51.04 |    41.67 |    45.16 |    51.14 |... 00,201,206,207 |
amazon-cognito-identity-js:  CognitoAccessToken.js    |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  CognitoIdToken.js        |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  CognitoJwtToken.js       |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  CognitoRefreshToken.js   |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  CognitoUser.js           |    79.46 |    69.77 |     75.2 |    79.95 |... 2048,2071,2169 |
amazon-cognito-identity-js:  CognitoUserAttribute.js  |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  CognitoUserPool.js       |    81.03 |    61.54 |      100 |     80.7 |... 85,186,189,192 |
amazon-cognito-identity-js:  CognitoUserSession.js    |      100 |       90 |      100 |      100 |                15 |
amazon-cognito-identity-js:  CookieStorage.js         |    92.86 |       85 |      100 |    92.68 |          46,67,98 |
amazon-cognito-identity-js:  DateHelper.js            |      100 |    83.33 |      100 |      100 |                40 |
amazon-cognito-identity-js:  StorageHelper-rn.js      |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  StorageHelper.js         |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  UserAgent.js             |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js:  index.js                 |      100 |      100 |      100 |      100 |                   |
amazon-cognito-identity-js: --------------------------|----------|----------|----------|----------|-------------------|
amazon-cognito-identity-js: Test Suites: 20 passed, 20 total
amazon-cognito-identity-js: Tests:       759 passed, 759 total
amazon-cognito-identity-js: Snapshots:   1 passed, 1 total
amazon-cognito-identity-js: Time:        24.331s
amazon-cognito-identity-js: Ran all test suites.
lerna success run Ran npm script 'test' in 1 package in 25.8s:
lerna success - amazon-cognito-identity-js
Done in 26.58s.

```
</details>

<details>
<summary>But I cannot get the linter to run</summary>

```
❯ yarn run lint --scope amazon-cognito-identity-js               
yarn run v1.22.19
$ lerna run lint --scope amazon-cognito-identity-js
lerna notice cli v3.22.1
lerna info versioning independent
lerna notice filter including "amazon-cognito-identity-js"
lerna info filter [ 'amazon-cognito-identity-js' ]
lerna info Executing command in 1 package: "yarn run lint"
lerna ERR! yarn run lint exited 1 in 'amazon-cognito-identity-js'
lerna ERR! yarn run lint stdout:
$ eslint src
Cannot read config file: /home/razorx/forks/amplify-js/packages/amazon-cognito-identity-js/.eslintrc.yaml
Error: unidentified alias ".test.js" at line 10, column 19:
      files: *.test.js
                      ^
YAMLException: Cannot read config file: /home/razorx/forks/amplify-js/packages/amazon-cognito-identity-js/.eslintrc.yaml
Error: unidentified alias ".test.js" at line 10, column 19:
      files: *.test.js
                      ^
    at generateError (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readAlias (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1276:5)
    at composeNode (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1368:20)
    at readBlockMapping (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

~/forks/amplify-js/packages/amazon-cognito-identity-js cognito-identity-js/refactor-get-user-pool-name
❯ yarn run lint
yarn run v1.22.19
$ eslint src
Cannot read config file: /home/razorx/forks/amplify-js/packages/amazon-cognito-identity-js/.eslintrc.yaml
Error: unidentified alias ".test.js" at line 10, column 19:
      files: *.test.js
                      ^
YAMLException: Cannot read config file: /home/razorx/forks/amplify-js/packages/amazon-cognito-identity-js/.eslintrc.yaml
Error: unidentified alias ".test.js" at line 10, column 19:
      files: *.test.js
                      ^
    at generateError (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:167:10)
    at throwError (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:173:9)
    at readAlias (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1276:5)
    at composeNode (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1368:20)
    at readBlockMapping (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readBlockMapping (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1089:11)
    at composeNode (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1359:12)
    at readDocument (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1525:3)
    at loadDocuments (/home/razorx/forks/amplify-js/node_modules/js-yaml/lib/js-yaml/loader.js:1588:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

I'd love to fix the CI build, but the output gives no indication of what the error is. Any idea what might be failing given this cryptic output?

```
yarn run v1.22.17
$ lerna run test --stream
lerna notice cli v3.22.1
lerna info versioning independent
lerna info ci enabled
lerna info Executing command in 27 packages: "yarn run test"
amazon-cognito-identity-js: $ jest --config ./jest.config.js
@aws-amplify/ui: $ webpack
aws-amplify-vue: $ ./node_modules/.bin/vue-cli-service test:unit
aws-amplify-react-native: $ npm run lint && jest -w 1 --passWithNoTests --coverage --maxWorkers 2 --config jest.config.js
@aws-amplify/core: $ tslint 'src/**/*.ts' && jest -w 1 --coverage
aws-amplify-react-native: npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1654288458571-0.0034024722531720286/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
aws-amplify-react-native: > aws-amplify-react-native@6.0.4 lint /root/amplify-js/packages/aws-amplify-react-native
aws-amplify-react-native: > eslint src
@aws-amplify/ui: Killed
@aws-amplify/ui: error Command failed with exit code 137.
@aws-amplify/ui: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run test exited 137 in '@aws-amplify/ui'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 137

CircleCI received exit code 137
```

**Comment by ashika01** [comment]
@razor-x Can you get ur branch update to date and then i can run the linter on that or see what the issue is :)

**Comment by razor-x** [comment]
> @razor-x Can you get ur branch update to date and then i can run the linter on that or see what the issue is :)

Done, thanks.

**Comment by haverchuck** [comment]
@razor-x  Could you please update your branch with latest from the  base branch?

**Review by haverchuck — APPROVED** [review]

**Review by haverchuck — APPROVED** [review]

**Review by jimblanc — APPROVED** [review]
Looks good, thanks for your contribution!

**Review by AllanZhengYP — APPROVED** [review]

**Comment by razor-x** [comment]
> @razor-x Did you happen to add your fork of this project into your own CircleCI account?

It's been a while so I don't know if I did that intentionally or if CircleCI picked it up automatically. It's possible I did that to try and debug the tests before opening the PR. I am surprised that when opening the PR back to the upstream repo the build status from the fork would show up here. I've disabled those builds now.

Thanks for looking into this, I know this contribution is not high impact, but hopefully some of the issues with this PR can help streamline things for for future first-time contributors.

**Comment by abdallahshaban557** [comment]
@razor-x  - merged now! we will get this out in our next release! Thank you for the contribution!

**Pull request merged**
