### PR TITLE
Fixes #1368 - Unable to verify secret hash for client

### LINKED ISSUE #1368: Unable to verify secret hash for client
When signing in or signing up with aws amplify for js, it gives that error. The user pool has client secret checked and I need it like that. Is there any solution for this problem or is still a feature to be implemented?

### PR DESCRIPTION
**Pull request by Techblogogy**
_Issue #, if available:_
#1368

_Description of changes:_
Added support for client secret. When creating new `UserPool` you can now pass additional parameter `ClientSecret`, which will fix "Unable to verify secret hash for client" error.

Supported actions:
- SignUp
- ForgotPassword
- ConfirmSignUp
- ResendConfirmationCode
- ConfirmForgotPassword
- InitiateAuth
- RespondToAuthChallenge

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
Thanks for your PR! We'll schedule this for an internal design review & further validation.

**Comment by Techblogogy** [comment]
@ericclemmons thank you) If you'll have any comments / suggestions from your end please let me know :)

**Comment by ericclemmons** [comment]
Hi @Techblogogy, I wanted to let you know that we've had a meeting about PR in particular, but have additional follow-ups before we can proceed.

Please see my comment on https://github.com/aws-amplify/amplify-js/issues/1368#issuecomment-562785656 & help fill in any of the gaps I may have missed.

Hoping to get this resolved as soon as we can!

**Comment by ericclemmons** [comment]
Unfortunately, we haven't learned enough to have a valid rationale for escalating this change through security & API reviews.  Until then, unchecking "generate client secret" is recommended:
> https://github.com/aws-amplify/amplify-js/issues/1368#issuecomment-562785656

The good news is that we're still extremely interested in customer feedback on why this stop-gap solution isn't desirable.  Please let us know!

We really appreciate your PR & efforts with this, @Techblogogy.

**Comment by syl20lego** [comment]
I understand you probably don't want to add crypto library, but can you provide a callback function for us to create the signature, this way your code remains free but allow your clients to implement the functionality with the crypto library.

**Pull request closed without merging**
