### PR TITLE
fix(@aws-amplify/auth): keep existing history.state

### LINKED ISSUE #6621: HandleAuthResponse clears the history.state and makes `current` undefined
**Describe the bug**
After authentication `window.history.state` gets cleared, and `current` route becomes undefined which causes issue for routing related features.

**To Reproduce**
The problematic line: https://github.com/aws-amplify/amplify-js/blob/main/packages/auth/src/Auth.ts#L1942

```
window.history.replaceState(
    {},
    null,
    (this._config.oauth as AwsCognitoOAuthOpts).redirectSignIn
);
```

**Expected behavior**
The current history should be kept. https://github.com/vuejs/vue-router-next/issues/366#issuecomment-678622415

```
window.history.replaceState(
  window.history.state,
  '',
  (this._config.oauth as AwsCognitoOAuthOpts).redirectSignIn
);
```

**Code Snippet**
Please provide a code snippet or a link to sample code of the issue you are experiencing to help us reproduce the issue. (Be sure to remove any sensitive data)

**Screenshots**

**What is Configured?**
NA

**Smartphone (please complete the following information):**

- Device: Desktop
- OS: Windows
- Browser Chrome
- Version: 84.0.4147.135 

**Additional context**
This breaks advanced features in `vue-router`

**_You can turn on the debug mode to provide more info for us by setting window.LOG_LEVEL = 'DEBUG'; in your app._**

### PR DESCRIPTION
**Pull request by posva**
Fix #6621

_Description of changes:_ As described in the issue, wiping the state breaks routers implementation, making amplify-js incompatible with some frontend routers, and breaking any existing usage of the state by the user.

I couldn't find any reference of saving anything to the state in the library so I didn't find what was necessary to wipe so I used the whole `history.state` property. The second argument should also be a string.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by svidgen** [comment]
Tested and LGTM.

**Review by svidgen — APPROVED** [review]

**Comment by jdnz** [comment]
Can confirm this is an issue for me using vue-router and amplify auth together. I have to patch the auth package to remove the `history.replaceState` calls so that my URLs aren't rewritten by auth.

A good solution would be to have the ability to set a custom redirect method. In msal-browser they do this: https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/navigation.md.

**Comment by cwomack** [comment]
Hey, [@posva](https://github.com/posva) :wave:. Thank you for your contribution with this PR. With the release of the latest major version of Amplify (aws-amplify@>6), we do not plan on merging this PR and highly recommend updating to the most recent version. Please refer to our [release announcement](https://aws.amazon.com/blogs/mobile/amplify-javascript-v6/?sc_channel=sm&sc_publisher=TWITTER&sc_geo=GLOBAL&sc_outcome=awareness&linkId=248500593), [migration guide](https://docs.amplify.aws/javascript/build-a-backend/troubleshooting/migrate-from-javascript-v5-to-v6/), and [documentation ](https://docs.amplify.aws/javascript/start/getting-started/)for more information.

**Comment by cwomack** [comment]
@posva, we had the team review and test this PR thoroughly again and no longer have the initial concerns about merging the suggested changes in v5 and v6 of Amplify.  We apologize for the delays, and we’ll ensure our process of reviewing and testing external PR’s is more efficient going forward.

I’ll reopen this PR and have the team merge the changes in soon for our next release!

**Comment by posva** [comment]
Hello, feel free to just open a new PR and ignore this one as the files are not the same anymore. The fix should be the same or similar, I will let you decide on that. To be completely transparent: I don't intend to participate in this issue any further. I hope it helps to fix the issue users were having and wish you luck!

**Comment by cwomack** [comment]
[@posva](https://github.com/posva) I know you mentioned being done with this PR, but wanted to follow up on the current status of things before closing this out.

First and foremost, we appreciate the feedback and patience on this contribution that you submitted years ago. The triage process and more intensive testing is on us to get right for future PR’s, which we’re working to improve. Per your request above, we moved the implementation of the history.state into two separate PR’s ([#12781](https://github.com/aws-amplify/amplify-js/pull/12781) for v5 and [#12782](https://github.com/aws-amplify/amplify-js/pull/12782) for v6) and have already merged them in.

Thank you again for raising issues in our triage process and ultimately improving Amplify!

**Pull request closed without merging**
