### PR TITLE
feat(aws-amplify-vue/auth): Add federated sign in for social providers

### PR DESCRIPTION
**Pull request by OrozcoJonathan**
*Issue #, if available:*
#2516

*Description of changes:*
This change adds a federated sign in component to the aws-amplify-vue library

Docs link aws-amplify/docs#506
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by The-Edge-Malaysia** [comment]
Hi!
I am wondering is this made itself to the master branch? I am new to amplify and wonder if I can use the branch vueFedderatedIdentity directly?

How can I installed the codes by OrozcoJonathan as I need google sign in badly but could not get it to work properly.

**Comment by OrozcoJonathan** [comment]
> Hi!
> I am wondering is this made itself to the master branch? I am new to amplify and wonder if I can use the branch vueFedderatedIdentity directly?
> 
> How can I installed the codes by OrozcoJonathan as I need google sign in badly but could not get it to work properly.


[**@The-Edge-Malaysia**](https://github.com/The-Edge-Malaysia) commented on [Jun 13, 2019, 11:19 AM PDT](https://github.com/aws-amplify/amplify-js/pull/2812#issuecomment-501823235 "2019-06-13T18:19:48Z - Replied by Github Reply Comments"):
> Hi!  
> I am wondering is this made itself to the master branch? I am new to amplify and wonder if I can use the branch vueFedderatedIdentity directly?
> 
> How can I installed the codes by OrozcoJonathan as I need google sign in badly but could not get it to work properly.

It has not been merged in yet, but if you wanted to use it you can pull this branch into your existing project and test it out.

**Comment by OrozcoJonathan** [comment]
[**@The-Edge-Malaysia**](https://github.com/The-Edge-Malaysia)  It has not been merged in yet, but you're more than welcome to use this branch in your project and test it out.

**Comment by The-Edge-Malaysia** [comment]
Tq

**Comment by The-Edge-Malaysia** [comment]
@haverchuck appreciate if you can review this branch. thanks a million

**Comment by thzero** [comment]
Requesting review.  This has languished for awhile now, but its a big missing compared to React support.

**Comment by robert-moore** [comment]
This one really needs to happen. It's a major missing feature compared to react

**Comment by voraczech** [comment]
This Pull request is almost exactly one year old. Is there any chance that it will be merged for example in a week or two?

**Comment by voraczech** [comment]
@mlabieniec @manueliglesias @haverchuck Is it possible to merge this pull request? Or is there any other solution to implement a federation sign in with VueJS? I'd love to use Amplify, therefore I think it must be as easy as possible to create awesome projects. Thanks in advance for your response, guys! 🙏

**Comment by praghavan039** [comment]
Can this be merged please.

**Comment by elorzafe** [comment]
@praghavan039 @voraczech @robert-moore @thzero @The-Edge-Malaysia @OrozcoJonathan 

@OrozcoJonathan thanks for this PR, we pull this changes forward into new UI components libraries. For more information on how to use federated sign in with social providers you can find it [here](https://github.com/aws-amplify/amplify-js/tree/master/packages/amplify-ui-components#amplify-authenticator-federated)

**Pull request closed without merging**
