### PR TITLE
fix(aws-amplify-react-native): migrate to community picker

### PR DESCRIPTION
**Pull request by calebpollman**
#### Description of changes

Migrates usage of React Native deprecated `Picker` to community [`Picker`](https://github.com/react-native-picker/picker) in `aws-amplify-react-native`

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/6845

#### Description of how you validated changes
Manually tested in Android and iOS sample app with React Native v0.66

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by evcodes — APPROVED** [review]
LGTM! One nit, there may be some potential problems with your .prettierrc file since some of the styles from this file were changed. 

Pending some tests on expo

**Comment by chintannp** [comment]
Thanks for the fix Caleb. I have tested the fix with RN `v0.62.1` , `v0.65.1` and `v0.66.1`.

**Review by sammartinez — APPROVED** [review]
LGTM 🌮 Let's wait to merge until after the release for this. Thanks for the quick turnaround on this!

**Comment by wbroek** [comment]
@calebpollman thanks for the quick actions and PR but think you missed one in VerifyContact https://github.com/calebpollman/amplify-js/blob/5fefb186ca480afc81c66a5e10178292c62d8ad8/packages/aws-amplify-react-native/src/Auth/VerifyContact.tsx#L15
Thats where it crashed for me as well...
Could you adjust that one as well?

**Comment by calebpollman** [comment]
> @calebpollman thanks for the quick actions and PR but think you missed one in VerifyContact https://github.com/calebpollman/amplify-js/blob/5fefb186ca480afc81c66a5e10178292c62d8ad8/packages/aws-amplify-react-native/src/Auth/VerifyContact.tsx#L15 Thats where it crashed for me as well... Could you adjust that one as well?

Thanks for catching that @wbroek will make the update before we merge

**Comment by calebpollman** [comment]
Documentation update PR: https://github.com/aws-amplify/docs/pull/3745

**Pull request merged**
