### PR TITLE
fix: aws-amplify-react-native Auth, ConfirmSignUp: Resend Code enabled/dis…

### PR DESCRIPTION
**Pull request by bensewell**
#### Description of changes

Made the "Resend Code" button on ConfirmSignUp use the current username rather than the state.

#### Issue #, if available

#9766

#### Description of how you validated changes

Simply brought code into sync with the Confirm button above it.

#### Checklist

- [x ] PR description included

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bensewell** [comment]
@Ashish-Nanda does this look good to you?

**Comment by calebpollman** [comment]
@bensewell This looks pretty straightforward in terms of a change, but can you please merge from `main` and push your branch?

**Review by Samaritan1011001 — APPROVED** [review]
Thank you for the contribution! LGTM!

**Review by calebpollman — APPROVED** [review]
LGTM 🚢

**Review by chintannp — APPROVED** [review]
Thanks for the contribution. LGTM 🚀

**Comment by calebpollman** [comment]
@bensewell Can you merge `main` in to your PR branch again please? Once it passes the integ tests we can move forward with merging

**Comment by bensewell** [comment]
@calebpollman all done

**Comment by calebpollman** [comment]
Thanks @bensewell!

**Pull request merged**
