### PR TITLE
fix(auth): Catch password reset Cognito API error response

### PR DESCRIPTION
**Pull request by oschwartz10612**
#### Description of changes

This is a pretty simple fix I think. `Auth.currentAuthenticatedUser` does not currently catch if the password is reset in Cognito. It currently will just return the current user even though the Cognito API call returns 400 with the following message. 

`{"__type":"PasswordResetRequiredException","message":"Password reset required for the user"}`

We need to catch this message I believe in the same way that the token revoke is handled.

#### Description of how you validated changes
Tested in a personal demo application.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by oschwartz10612** [comment]
Hello @aws-amplify-ops / reviewers! Do you think we can merge this? I would love to have this in the mainline shortly so I can use this in our application.

**Comment by oschwartz10612** [comment]
Hey, is this something we can get merged so I can resolve the bug in my application? I think this is a pretty simple fix.

**Review by erinleigh90 — APPROVED** [review]

**Comment by erinleigh90** [comment]
@oschwartz10612 Can you update your branch to reflect the changes in main? Code looks good and checks out locally, so we will merge once the branch is caught up and checks are passing. Thank you!

**Comment by oschwartz10612** [comment]
Hi @erinleigh90, thanks for reviewing! I just updated the branch!

**Review by erinleigh90 — APPROVED** [review]
LGTM! Thank you!

**Review by israx — APPROVED** [review]
Hey @oschwartz10612 . Thanks for putting this together.

LGTM!

**Pull request merged**
