### PR TITLE
fix: session cookies when SSR config enabled

### LINKED ISSUE #10786: Auth only sets session cookies when SSR is enabled
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 12.6.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.03 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
    Watchman: 2022.12.05.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 89.1.21.77
    Chrome: 108.0.5359.124
    Firefox: 102.6.0
    Safari: 16.1
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @aws-amplify/ui-react: ^4.2.0 => 4.2.0 
    @aws-amplify/ui-react-internal:  undefined ()
    @babel/core:  undefined ()
    @babel/runtime:  7.15.4 
    @edge-runtime/primitives:  2.0.0 
    @hapi/accept:  undefined ()
    @napi-rs/triples:  undefined ()
    @next/react-dev-overlay:  undefined ()
    @segment/ajv-human-errors:  undefined ()
    @types/node: 18.11.15 => 18.11.15 
    @types/react: 18.0.26 => 18.0.26 
    @types/react-dom: 18.0.9 => 18.0.9 
    @vercel/nft:  undefined ()
    acorn:  undefined ()
    amphtml-validator:  undefined ()
    anser:  undefined ()
    arg:  undefined ()
    assert:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-amplify: ^5.0.5 => 5.0.5 
    babel-packages:  undefined ()
    browserify-zlib:  undefined ()
    browserslist:  undefined ()
    buffer:  undefined ()
    bytes:  undefined ()
    chalk:  undefined ()
    ci-info:  undefined ()
    cli-select:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constants-browserify:  undefined ()
    content-disposition:  undefined ()
    content-type:  undefined ()
    cookie:  undefined ()
    cross-spawn:  undefined ()
    crypto-browserify:  undefined ()
    css.escape:  undefined ()
    cssnano-simple:  undefined ()
    data-uri-to-buffer:  undefined ()
    debug:  undefined ()
    devalue:  undefined ()
    domain-browser:  undefined ()
    edge-runtime:  undefined ()
    eslint: 8.29.0 => 8.29.0 
    eslint-config-next: 13.0.6 => 13.0.6 
    events:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    fresh:  undefined ()
    get-orientation:  undefined ()
    glob:  undefined ()
    gzip-size:  undefined ()
    http-proxy:  undefined ()
    https-browserify:  undefined ()
    icss-utils:  undefined ()
    ignore-loader:  undefined ()
    image-size:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    jest-worker:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    micromatch:  undefined ()
    mini-css-extract-plugin:  undefined ()
    nanoid:  undefined ()
    native-url:  undefined ()
    neo-async:  undefined ()
    next: 13.0.6 => 13.0.6 
    node-fetch:  undefined ()
    node-html-parser:  undefined ()
    ora:  undefined ()
    os-browserify:  undefined ()
    p-limit:  undefined ()
    path-browserify:  undefined ()
    platform:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-modules-extract-imports:  undefined ()
    postcss-modules-local-by-default:  undefined ()
    postcss-modules-scope:  undefined ()
    postcss-modules-values:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-safe-parser:  undefined ()
    postcss-scss:  undefined ()
    postcss-value-parser:  undefined ()
    process:  undefined ()
    punycode:  undefined ()
    querystring-es3:  undefined ()
    raw-body:  undefined ()
    react: 18.2.0 => 18.2.0 (18.3.0-next-2655c9354-20221121)
    react-dom: 18.2.0 => 18.2.0 (18.3.0-next-2655c9354-20221121)
    react-is:  18.2.0 
    react-refresh:  0.12.0 
    react-server-dom-webpack:  undefined ()
    regenerator-runtime:  0.13.4 
    sass-loader:  undefined ()
    scheduler:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    setimmediate:  undefined ()
    shell-quote:  undefined ()
    source-map:  undefined ()
    stacktrace-parser:  undefined ()
    stream-browserify:  undefined ()
    stream-http:  undefined ()
    string-hash:  undefined ()
    string_decoder:  undefined ()
    strip-ansi:  undefined ()
    tar:  undefined ()
    terser:  undefined ()
    text-table:  undefined ()
    timers-browserify:  undefined ()
    tty-browserify:  undefined ()
    typescript: 4.9.4 => 4.9.4 
    ua-parser-js:  undefined ()
    undici:  undefined ()
    unistore:  undefined ()
    util:  undefined ()
    vm-browserify:  undefined ()
    watchpack:  undefined ()
    web-vitals:  undefined ()
    webpack:  undefined ()
    webpack-sources:  undefined ()
    ws:  undefined ()
  npmGlobalPackages:
    @aws-amplify/cli: 10.4.0
    @expo/ngrok: 4.1.0
    amplify-cli: 1.0.0
    corepack: 0.10.0
    npm: 8.11.0
    react-native: 0.70.6
    serve: 14.0.1
    verdaccio: 5.15.4
    yarn: 1.22.19

```

</details>

### Describe the bug

When [`ssr` flag is enabled](https://docs.amplify.aws/lib/ssr/q/platform/js/#withssrcontext), the session tokens are stored in both local storage and cookie storage. However, the cookies are session cookies(i.e. without `expiration`), the cookie storage is erased after relaunching the browser. As a result, the backend API cannot get the token hence rendering the page.

### Expected behavior

The session token shoud be stored as persistent cookie in cookie storage. 

### Reproduction steps

I created a reproduction repo for it:
1. Clone the [reproduction repo](https://github.com/AllanZhengYP/amplify-nextjs-test/tree/D65972415) and add `aws-exports.js`
2. `yarn && yarn dev`
3. Login with amplify UI: Sets tokens in local storage AND session cookie(no expiration)
4. Go to SSR page(`api/profile`): rander correctly
5. Quit browser and reopen
6. Go to log in page: No need to log in again because of the persistent local storage
7. Go to SSR page(`api/profile`): doesn’t work because session cookies are erased

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

/cc @haverchuck

### PR DESCRIPTION
**Pull request by AllanZhengYP**
#### Description of changes

When `ssr` config is enabled, the Amplify uses cookie storage to store the tokens. Currently Amplify doesn't set an expiration to cookies. So the cookies are session cookies. It means when customer relaunch the browser, these cookies are gone, hence they need to repeat signing in. 

With this change, the session tokens stored in the cookie storage have a default 1 year expiration. So they persists during the relaunch. The 1 year expiration is picked because it's also used as default expiration by `CookieStorage` of `amazon-cognito-identity-js` package. 

When the token themselves expires, they'll be refreshed [before further API requests](https://github.com/aws-amplify/amplify-js/blob/cc5f1c3f2efc520dbfe1dc110f4406da5e063675/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1426).

/cc @elorzafe 

#### Issue #, if available

Resolves #10786
Associated to: https://github.com/aws-amplify/amplify-js-samples-staging/pull/505

#### Description of how you validated changes
Integration test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by elorzafe — DISMISSED** [review]
Looks good to me 

Thanks @AllanZhengYP 🏅 

You will need to remove the releasable branch before merge

**Review by helgabalashova — APPROVED** [review]

**Review by elorzafe — APPROVED** [review]

**Review by helgabalashova — APPROVED** [review]

**Comment by weisisheng** [comment]
Is this issue assumed to be settled?  A review of a bunch of posts suggests a fix in  "aws-amplify": 5.0.10 solved the SSR "no authenticated user" but I am up to 5.0.16   and still having no user found after logging in successfully client-side and trying some getServerSideProps() tests.

**Comment by aliza-khu** [comment]
@weisisheng, Is this issue still exist in the latest version of aws-amplify(5.0.23)?

**Comment by aliza-khu** [comment]
@AllanZhengYP, Is this issue still exist in the latest version of aws-amplify(5.0.23)?
Is this fix also works for the application who haven't enabled SSR

**Comment by tannerabread** [comment]
Hi @aliza-khu can you follow this issue https://github.com/aws-amplify/amplify-js/issues/10818 for updates

**Comment by weisisheng** [comment]
> @weisisheng, Is this issue still exist in the latest version of aws-amplify(5.0.23)?

Yes, now on 5.1.2

**Pull request merged**
