### PR TITLE
fix: duplicate entry in connection states

### PR DESCRIPTION
**Pull request by takpen**
#### Description of changes

This PR fixes the duplicate entry of `ConnectedPendingNetwork` in the connection states array.

#### Issue #, if available

N/A

#### Checklist

- [x] PR description included

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nadetastic** [comment]
Hi @takpen thank you for your contribution! I'm discussing this change with the team and will follow up with any updates/comments. Seems like a minor update so hopefully we can merge it for a release soon.

**Review by stocaaro — APPROVED** [review]
LGTM

**Review by cwomack — APPROVED** [review]
LGTM

**Review by abdallahshaban557 — APPROVED** [review]
LGTM!

**Review by jimblanc — APPROVED** [review]

**Pull request merged**
