### PR TITLE
chore(@aws-amplify/ui-components): v1 ☂️

### PR DESCRIPTION
**Pull request by ericclemmons**
- [x] https://github.com/aws-amplify/amplify-js/pull/7650 
- [x] https://github.com/aws-amplify/amplify-js/pull/7651
- [ ] ~~https://github.com/aws-amplify/amplify-js/pull/7653~~ I'd rather not delay this release because of this nice-to-have change.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by wlee221 — APPROVED** [review]
This LGTM! Thanks @ericclemmons 👍

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Comment by ericclemmons** [comment]
I'm going to test this merge locally first with Verdaccio to see if it bumps versions as expected.

**Review by amhinson — APPROVED** [review]
LGTM 🎉

**Comment by ericclemmons** [comment]
I updated this PR to explicitly set these packages to `1.0.0`.  In my testing, because conventional commits **rely on the commit message**, I have to carefully construct the right format:
> https://www.conventionalcommits.org/en/v1.0.0/#summary

So, there's a risk that we squash & commit and _it doesn't bump correctly in CI/CD_ due to user error in the PR title or GitHub process.

Rather than risk it at all, **I've explicitly set the versions to `1.0.0`**. Worst-case scenario, the first release will be `1.0.1`. Best-case scenario, lerna will honor the `1.0.0`.

**Comment by ericclemmons** [comment]
Alright, I need to see why this build is failing.

I just did a test to see what we'll see:

### `yarn publish:verdaccio`
```
yarn run v1.22.10
$ lerna publish --no-push --canary minor --dist-tag=unstable --preid=unstable --exact --force-publish --yes

Found 25 packages to publish:
 - amazon-cognito-identity-js => 4.6.0-unstable.6+d1d1e2941
 - @aws-amplify/ui-angular => 0.5.0-unstable.6+d1d1e2941
 - @aws-amplify/ui-components => 0.11.0-unstable.6+d1d1e2941
 - @aws-amplify/ui-react => 0.3.0-unstable.6+d1d1e2941
 - @aws-amplify/ui-vue => 0.4.0-unstable.6+d1d1e2941
 - @aws-amplify/ui => 2.1.0-unstable.537+d1d1e2941
 - @aws-amplify/analytics => 4.1.0-unstable.6+d1d1e2941
 - @aws-amplify/api-graphql => 1.3.0-unstable.6+d1d1e2941
 - @aws-amplify/api-rest => 1.3.0-unstable.6+d1d1e2941
 - @aws-amplify/api => 3.3.0-unstable.6+d1d1e2941
 - @aws-amplify/auth => 3.5.0-unstable.6+d1d1e2941
 - aws-amplify-angular => 5.1.0-unstable.6+d1d1e2941
 - aws-amplify-react-native => 4.4.0-unstable.21+d1d1e2941
 - aws-amplify-react => 4.3.0-unstable.6+d1d1e2941
 - aws-amplify-vue => 2.2.0-unstable.21+d1d1e2941
 - aws-amplify => 3.4.0-unstable.6+d1d1e2941
 - @aws-amplify/cache => 3.2.0-unstable.6+d1d1e2941
 - @aws-amplify/core => 3.9.0-unstable.6+d1d1e2941
 - @aws-amplify/datastore => 2.10.0-unstable.6+d1d1e2941
 - @aws-amplify/interactions => 3.4.0-unstable.6+d1d1e2941
 - @aws-amplify/predictions => 3.3.0-unstable.6+d1d1e2941
 - @aws-amplify/pubsub => 3.3.0-unstable.6+d1d1e2941
 - @aws-amplify/pushnotification => 3.3.0-unstable.6+d1d1e2941
 - @aws-amplify/storage => 3.4.0-unstable.6+d1d1e2941
 - @aws-amplify/xr => 2.3.0-unstable.6+d1d1e2941

```

### `yarn publish:release`

```
yarn run v1.22.10
$ lerna publish --conventional-commits --yes --message 'chore(release): Publish [ci skip]'

Changes:
 - @aws-amplify/ui-angular: 1.0.0 => 1.0.1
 - @aws-amplify/ui-components: 1.0.0 => 1.0.1
 - @aws-amplify/ui-react: 1.0.0 => 1.0.1
 - @aws-amplify/ui-storybook: 1.0.0 => 1.0.1 (private)
 - @aws-amplify/ui-vue: 1.0.0 => 1.0.1
 - @aws-amplify/ui-react: 1.0.0 => 1.0.1
 - @aws-amplify/ui-storybook: 1.0.0 => 1.0.1 (private)
 - @aws-amplify/ui-vue: 1.0.0 => 1.0.1
 - @aws-amplify/analytics: 4.0.9 => 4.0.10
 - @aws-amplify/api-graphql: 1.2.21 => 1.2.22
 - @aws-amplify/api-rest: 1.2.21 => 1.2.22
 - @aws-amplify/api: 3.2.21 => 3.2.22
 - @aws-amplify/auth: 3.4.21 => 3.4.22
 - aws-amplify-angular: 5.0.47 => 5.0.48
 - aws-amplify-react: 4.2.22 => 4.2.23
 - aws-amplify: 3.3.18 => 3.3.19
 - @aws-amplify/cache: 3.1.46 => 3.1.47
 - @aws-amplify/core: 3.8.13 => 3.8.14
 - @aws-amplify/datastore: 2.9.7 => 2.9.8
 - @aws-amplify/interactions: 3.3.21 => 3.3.22
 - @aws-amplify/predictions: 3.2.21 => 3.2.22
 - @aws-amplify/pubsub: 3.2.19 => 3.2.20
 - @aws-amplify/pushnotification: 3.2.21 => 3.2.22
 - @aws-amplify/storage: 3.3.21 => 3.3.22
 - @aws-amplify/xr: 2.2.21 => 2.2.22

Successfully published:
 - @aws-amplify/ui-angular@1.0.1
 - @aws-amplify/ui-components@1.0.1
 - @aws-amplify/ui-react@1.0.1
 - @aws-amplify/ui-vue@1.0.1
 - @aws-amplify/analytics@4.0.10
 - @aws-amplify/api-graphql@1.2.22
 - @aws-amplify/api-rest@1.2.22
 - @aws-amplify/api@3.2.22
 - @aws-amplify/auth@3.4.22
 - aws-amplify-angular@5.0.48
 - aws-amplify-react@4.2.23
 - aws-amplify@3.3.19
 - @aws-amplify/cache@3.1.47
 - @aws-amplify/core@3.8.14
 - @aws-amplify/datastore@2.9.8
 - @aws-amplify/interactions@3.3.22
 - @aws-amplify/predictions@3.2.22
 - @aws-amplify/pubsub@3.2.20
 - @aws-amplify/pushnotification@3.2.22
 - @aws-amplify/storage@3.3.22
 - @aws-amplify/xr@2.2.22
...
```

**Pull request merged**
