### PR TITLE
Upgrade to AndroidX, remove deprecated android dependencies, upgrade to latest Firebase.

### PR DESCRIPTION
**Pull request by therealadum**
*Issue #, if available:*
No issue opened, but when using the @aws-amplify/pushnotificaiton library on Android with other libraries that use AndroidX / the newest google play services, builds will fail with the error `Duplicate class com.google.android.gms.gcm.PendingCallback`.

Upon further investigation, this is because the current pushnotification build.gradle file specifies the use of a deprecated library, `com.firebase:firebase-jobdispatcher:0.6.0`. In newer versions of `com.google.firebase`, these are handled without the use of the deprecated JobDispatcher class.

*Description of changes:*

Changes to build dependencies:
- upgraded gradle wrapper to `5.1.1`
- upgraded gradle build tools to `3.4.2`
- upgraded google-services to `4.3.0`
- upgraded targetSDK to `28`
- removed `com.android.support:appcompat` and replaced with androidx appcompat
- use `jettifier` and `androidx` for backwards compatibility to `com.android.support:appcompat`

Changes to core files:
- removed `RNPushNotificationDeviceIDService.java`
  - reason: in the newest version of firebase, the `FirebaseMessagingService` class takes care of the token generation with the `@Override onNewToken`
- updated `RNPushNotificationModule.java` `getToken` method to use the up-to-date firebase method for getting the token id
  - reason: the old `getToken` method used deprecated firebase functions

All other core file changes were removing unused imports.

Changes for projects consuming this library:
In the installation instructions at `https://aws-amplify.github.io/docs/js/push-notifications`, you are no longer required to add the following service into your `AndroidManifest.xml`:
```
<!-- [START firebase_iid_service] -->
     <service android:name="com.amazonaws.amplify.pushnotification.RNPushNotificationDeviceIDService">
         <intent-filter>
             <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
         </intent-filter>
     </service>
```
The reason for omitting this is because the method was removed as mentioned above, because it is no longer required by the `FirebaseMessagingService` to have an explicit INSTANCE_ID_EVENT (handled by the `onNewToken` function).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bneigher** [comment]
would love this to be merged guys!!

**Comment by AndreasEK** [comment]
What's the reason this hasn't been merged yet?

**Comment by amalviya001** [comment]
I am facing same issue in AndroidX. Can you please merge code into master ASAP.

**Comment by james-freely** [comment]
Can someone review this?

**Comment by sammartinez** [comment]
Thanks for contributing, due to the conflicts and not hearing from you, we are going to close this pull request. Thanks again for contributing and please keep the pull requests coming!

**Pull request closed without merging**
