### PR TITLE
make amplify a devDependency

### PR DESCRIPTION
**Pull request by haverchuck**
*Description of changes:*
Downgrades aws-amplify dependency to prevent breaking change.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by yuth** [comment]
prior to this change did we expect the user of this package to include `aws-amplify` in their `package.json`?

**Comment by powerful23** [comment]
The `aws-amplify-react` and `aws-amplify-react-native` have that `aws-amplify` dependency but `aws-amplify-angular` doesn't. If we want to do the same thing to angular, we should pay attention to the backward compatibility and the documentation.

**Comment by powerful23** [comment]
Just created a pr to correct the documentation. #1490

**Comment by haverchuck** [comment]
All of our documentation has always told people to install aws-amplify on their own.

**Comment by haverchuck** [comment]
I was able to just make this a change from dependency to devDependency.

**Pull request merged**
