### PR TITLE
Add AmplifyContainer to angular module

### PR DESCRIPTION
**Pull request by jordanranz**
_Description of changes:_
- Add `AmplifyContainer` component to angular module

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by WeMakeLive** [comment]
@jordanranz
Thanks for doing this. I was stuck with this missing! Can the build be fixed?

**Comment by jordanranz** [comment]
@WeMakeLive, Curious what the build failure that you are seeing is? Also, what build command are you using?

**Comment by WeMakeLive** [comment]
> are seeing is? Also, what build command are you using?
@jordanranz circleci build is failing

**Comment by WeMakeLive** [comment]
@jordanranz @sammartinez Still looks to be failing the build (I dony have rights to see what CircleCI is saying)
I am hoping this will fix my `ERROR in Cannot determine the module for class AmplifyContainer in /[x]/node_modules/@aws-amplify/ui-angular/dist/core.d.ts! Add AmplifyContainer to the NgModule to fix it.` error

**Comment by jordanranz** [comment]
For some reason this unnecessarily changed the types in the core lib. Going to close this in favor of: https://github.com/aws-amplify/amplify-js/pull/6025

**Pull request closed without merging**
