### PR TITLE
Add token expiration margin in amazon-cognito-identity-js

### PR DESCRIPTION
**Pull request by jogold**
*Description of changes:* This PR adds the possibility to specify a token expiration margin. A positive value will result in a session expiring sooner. This can be useful to avoid the case where the token is still valid in frontend but not anymore when reaching the backend.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by elorzafe** [comment]
@jogold thanks for your contribution. This will need some internal discussion.

**Comment by undefobj** [comment]
@jogold @elorzafe is this just a "buffer" to ensure that the client will expire within the boundary of the backend to account for clock skew? If that's the case I would rather encode this into the client lib itself rather than requiring customers to pass it in. Am I interpreting it correctly?

**Comment by elorzafe** [comment]
@jogold what problem are you experiencing? doesn't work for you to just add clockDrift manually?

**Comment by jogold** [comment]
Hello,

I'm the one who introduced the clock drift back when this code was still in its own repo (see (see https://github.com/amazon-archives/amazon-cognito-identity-js/pull/541).

The clock drift can be positive or negative and was introduced when I had problems with users having their computer clock more than 1 hour off in the future, they were not able to login at all.

The proposal here is indeed just a "buffer" to ensure that when the frontend sees that the token is still valid it's still the case when it reaches the backend.

**Comment by undefobj** [comment]
> Hello,
> 
> I'm the one who introduced the clock drift back when this code was still in its own repo (see [amazon-archives/amazon-cognito-identity-js#541](https://github.com/amazon-archives/amazon-cognito-identity-js/pull/541)).
> 
> The clock drift can be positive or negative and was introduced when I had problems with users having their computer clock more than 1 hour off in the future, they were not able to login at all. It is calculated and not set.
> 
> The proposal here is indeed just a "buffer" to ensure that when the frontend sees that the token is still valid it's still the case when it reaches the backend.

@jogold wouldn't a better solution be to fix the clock drift on the system either in app code or under the covers? I wouldn't want to add any buffer parameter like this to a public Amplify API as it leaks implementation. Additionally there could be security implications as now the short term token expiry boundary is being overwritten.

@elorzafe @powerful23 can you take a look into this further.

**Comment by jogold** [comment]
Hi @undefobj,

I don't understand your security concerns: the token expiry is never overwritten, this is impossible, it's a JWT. The real expiry (`exp` claim) is set by the backend (Cognito here). So from the back end's point-of-view nothing changes.

The expiration margin and/or clock drift simply changes the validity from the front end's point-of-view. When an expired token reaches the back end, even if we have played with expiration margin and/or clock drift in the front end, it doesn't matter, the request will be rejected.

**Comment by elorzafe** [comment]
@jogold,
I agree with @undefobj, I think the best approach right now will be to set a default expiration margin of 5 minutes instead of adding more stuff to the api. Would you like to make that change?, otherwise we should close this PR.

@jogold thanks for your contribution.

**Comment by jogold** [comment]
You mean setting a constant in `isValid()`? Isn't 5 minutes too much? We only need to account for computer and/or network latencies.

**Comment by elorzafe** [comment]
@jogold I mean `this.tokenExpirationMargin` on line L85 of CognitoUserSession

**Comment by gabrielenosso** [comment]
any news on this?

**Comment by ivands** [comment]
Why did no one merge this PR...
I'm having the same problem's.
@jogold did everything you asked to fixed the problem.
Can we please take the time to press the merge button.

**Pull request closed without merging**
