### PR TITLE
Update AWSS3Provider.ts

### PR DESCRIPTION
**Pull request by purefan**
Honor the acl config param.
Attempts to fix https://github.com/aws-amplify/amplify-js/issues/960

_Issue #, if available:_
960

_Description of changes:_
The put function does nothing if a config value for acl or level is passed, the comment in the function suggests that "level" should be valid but the code does nothing about it. Chose to implement acl for compatibility with [the sdk](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#upload-property)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
Thanks for the PR @purefan!

It looks like @alexhenkel did something similar with his fork:
https://github.com/AlexHenkel/amplify-js/pull/1

Would you be able to put in a unit test similar to:
https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/storage/__tests__/Providers/AWSS3Provider-unit-test.ts#L428-L453
or:
https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/storage/__tests__/Storage-unit-test.ts#L487-L509

to validate this behavior?

Let me know if you're unable to or need some guidance. I'm happy to help!

**Comment by purefan** [comment]
Hi @ericclemmons Yeah Im all for writing a test or two but I cant build locally, followed the instructions [here](https://github.com/aws-amplify/amplify-js/wiki/Local-Development), `yarn build` fails with exit code 1: 

```
$ DEBUG=* yarn build
amazon-cognito-identity-js: > amazon-cognito-identity-js@3.2.0 clean /home/purefan/Projects/personal/amplify-js/packages/amazon-cognito-identity-js
amazon-cognito-identity-js: > rimraf lib es
aws-amplify-vue: [dotenv][DEBUG] did not match key and value when parsing line 1: 
aws-amplify-vue: 2019-12-05T09:37:28.344Z vue:env /home/purefan/Projects/personal/amplify-js/packages/aws-amplify-vue/.env.production.local { parsed: {} }
aws-amplify-vue: [dotenv][DEBUG] did not match key and value when parsing line 1: 
aws-amplify-vue: 2019-12-05T09:37:28.346Z vue:env /home/purefan/Projects/personal/amplify-js/packages/aws-amplify-vue/.env.production { parsed: {} }
aws-amplify-vue: [dotenv][DEBUG] did not match key and value when parsing line 1: 
aws-amplify-vue: 2019-12-05T09:37:28.346Z vue:env /home/purefan/Projects/personal/amplify-js/packages/aws-amplify-vue/.env.local { parsed: {} }
aws-amplify-vue: 2019-12-05T09:37:28.346Z vue:env /home/purefan/Projects/personal/amplify-js/packages/aws-amplify-vue/.env { parsed: {} }
aws-amplify-vue: [dotenv][DEBUG] did not match key and value when parsing line 1: 
aws-amplify-vue: 2019-12-05T09:37:28.396Z vue:project-config { css: { modules: true, extract: false },
aws-amplify-vue:   baseUrl: '/',
aws-amplify-vue:   publicPath: '/',
aws-amplify-vue:   outputDir: 'dist',
aws-amplify-vue:   assetsDir: '',
aws-amplify-vue:   indexPath: 'index.html',
aws-amplify-vue:   filenameHashing: true,
aws-amplify-vue:   runtimeCompiler: false,
aws-amplify-vue:   transpileDependencies: [],
aws-amplify-vue:   productionSourceMap: true,
aws-amplify-vue:   parallel: true,
aws-amplify-vue:   pages: undefined,
aws-amplify-vue:   crossorigin: undefined,
aws-amplify-vue:   integrity: false,
aws-amplify-vue:   lintOnSave: true,
aws-amplify-vue:   devServer: {} }
@aws-amplify/ui: You have installed webpack-cli and webpack-command together. To work with the "webpack" command you need only one CLI package, please remove one of them or use them directly via their binary.
@aws-amplify/ui: error Command failed with exit code 1.
@aws-amplify/ui: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@aws-amplify/ui'
lerna WARN complete Waiting for 4 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
```

I thought it could be webpack + webpack-cli being taken as an error (I think its a warning but I could be wrong) so I removed `webpack` from a couple of `package.json`s in the `/packages` folder but that did not help. I also added a bunch of env files that it complained were missing (`.env`, `.env.production`,...) I also tried `DEBUG=* NODE_ENV=development` but no change. 

I feel Im missing something obvious but if anyone can shed some light then I could move forward with this PR 

Cheers!

**Comment by ericclemmons** [comment]
@purefan Thanks for giving it a shot! There's clearly some work to do to improve our local developer experience.

I'll give it a shot & see if I can get a test in for you!

**Comment by ericclemmons** [comment]
@purefan Thanks for enabling writes from contributors!  I was able to push a quick test update. 

Once things pass, we'll get some more 👀 on it and a 👍 to ship it.

Thanks again!

**Comment by sammartinez** [comment]
@purefan Thanks for tackling this! This is great work and we appreciate yourself taking the time to send this Pull Request to us. Could possibly add similar for [API Documentation](https://github.com/aws-amplify/amplify-js/pull/2376/files) under the put API ? After this update i believe we will be ready to get this in.

**Comment by ericclemmons** [comment]
Resolving merge conflicts via https://github.com/aws-amplify/amplify-js/pull/5520

**Pull request closed without merging**
