### PR TITLE
fixing a problem where auth config level is different than expected f…

### PR DESCRIPTION
**Pull request by codeglider**
Referring to Issue [Issue 4175](https://github.com/aws-amplify/amplify-js/issues/4175)

awsreactnativeattributeissue

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by amhinson** [comment]
@codeglider You can just pass the `usernameAttributes` at the root level of the config instead of inside the `authConfig` object and it should work without this change.

```js
const signUpConfig = {
  usernameAttributes: "email",
  signUpFields: [...]
}
```

https://docs.amplify.aws/ui/auth/authenticator?framework=react-native#sign-upin-with-emailphone-number

**Comment by codeglider** [comment]
> ```js
> usernameAttributes: "email",
> ```

That doesn't seem to work.

Screen Shot 2020-04-22 at 5 13 41 PM

**Comment by amhinson** [comment]
Can you check and make sure you're running the latest version of `aws-amplify-react-native` without any custom changes to it? I have a sample app running with a similar `signUpConfig` and the email is being correctly used for email on the sign in screen.

```js
export default withAuthenticator(App, {
  usernameAttributes: 'email',
  signUpConfig: {
    signUpFields: [...],
  },
});
```

**Comment by codeglider** [comment]
@amhinson that does work!  But it's so confusing in the documentation.
I had it as 
```
export default withAuthenticator(
  App,
  true,
  null,
  null,
  MyTheme,
  signUpConfig,
);
```
When I changed to 
```
export default withAuthenticator(App, {
  includeGreetings: true,
  usernameAttributes: 'email',
  signUpConfig: signUpConfig,
});
```
Working just fine.
Thank you for your guidance.

**Comment by amhinson** [comment]
@codeglider I'm glad that worked for you! We will be working on getting better documentation for this sort of thing in the future, so your feedback will definitely be taken into account. 👍

**Comment by codeglider** [comment]
Thanks. Now post login fails something about `Unrecognized font family 'Material Icons'`

**Comment by amhinson** [comment]
I'd recommend opening up another issue so we can track it better.

**Comment by oxbits** [comment]
@codeglider im havin the same issue _  did u open another tix ?  
or did u solve `Unrecognized font family 'Material Icons'`

**Pull request closed without merging**
