### PR TITLE
Pass client FormData to axios

### LINKED ISSUE #1437: API: Add support to send FormData
**Do you want to request a feature or report a bug?**
New feature

**What is the current behavior?**
Blank JSON object `{}` will be sent to server

**Steps to reproduce**
```javascript
import API from '@aws-amplify/api'

const fd = new FormData()
fd.append('test', 'foobar')

API.put('MyApi', '/products', {body: fd})
```

**What is the expected behavior?**
Contents of [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects) will be sent to the server successfully.

**Version**
`"@aws-amplify/api": "1.0.5"`

### PR DESCRIPTION
**Pull request by tom-rb**
_Issue:_ closes #1437 

_Description of changes:_

RestClient was always doing a `JSON.stringify` in the `body` param. By checking if the body is a `FormData`, we can just forward it to axios who will handle the request properly.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by CaptainPanks — APPROVED** [review]

**Review by ericclemmons — APPROVED** [review]
This looks like a valuable addition! I also make the mistake of sending `FormData`, which led to:

> https://twitter.com/ericclemmons/status/1313579287480430592

@elorzafe What are your thoughts on this?

**Comment by shweta-codeprism** [comment]
Hi, can this be merged , we are really waiting for this feature..

**Review by amhinson — APPROVED** [review]
LGTM 👍

**Comment by shweta-codeprism** [comment]
@tom-rb  how are we going to send this data? 

`const formData = new FormData();
{
body: formData
}
`
is allowing us to send the data, but ends up receiving status 0 over xhr call

**Pull request merged**
