### PR TITLE
Migrating to community edition of AsyncStorage for React Native

### PR DESCRIPTION
**Pull request by Ashish5591**
_Issue #:_
fixes: #4351 
fixes: #4272

_Description of changes:_
Migrating to community edition of AsyncStorage for React Native

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by azimgd** [comment]
@Amplifiyer @haverchuck Too many people are having issues with sessions due to latest broken push including https://github.com/aws-amplify/amplify-js/issues/4380 https://github.com/aws-amplify/amplify-js/pull/3991
Can we please merge this and hopefully fix `sessions are not persisted on refresh (react-native)` issue ?

**Comment by azimgd** [comment]
Meanwhile new issues are being reported https://github.com/aws-amplify/amplify-js/issues/4417 https://github.com/aws-amplify/amplify-js/issues/4420 do we have any estimates on when this could be merged ?

@Amplifiyer @haverchuck @iartemiev

**Comment by Ashish5591** [comment]
Hi @azimgd,

I put up this PR thinking that moving to the community edition of async storage will resolve issues related to #4351 and #4380, but it may not be the root cause. I've responded in detail in this [comment](https://github.com/aws-amplify/amplify-js/issues/4351#issuecomment-556682870)

We are still investigating. Let us know if you have more insight.

**Comment by azimgd** [comment]
Thanks @Ashish5591

While i have already implemented custom storage for auth package it looks like there seems to be an unstable behavior of session. Spent couple days trying to figure out the root of problem but haven't had any luck. 
Rolled back to `"aws-amplify": "^1.2.4"` + custom class with community version of `async-storage` for now.

**Comment by Ashish5591** [comment]
@azimgd take a look at this [comment](https://github.com/aws-amplify/amplify-js/issues/4351#issuecomment-557722463) to see if it fixes it for you.

**Comment by amber-pli** [comment]
Sorry, I notice this is merged to aws-amplify:native-60, but I cannot see it on https://github.com/aws-amplify/amplify-js/tree/native-60

**Pull request merged**
