### PR TITLE
fix: pin jsdoc version

### PR DESCRIPTION
**Pull request by jamesaucode**
#### Description of changes
The latest jsdoc requires node >= 14. Pinning it to an older version to avoid upgrading our docker images' node version.

#### Description of how you validated changes
CircleCI 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by evcodes — APPROVED** [review]
LGTM thanks for the fix!

**Review by ashika01 — APPROVED** [review]
🚢

**Comment by ashika01** [comment]
I would assume we would want to upgrade the docker image node version in long run?

**Comment by jamesaucode** [comment]
> I would assume we would want to upgrade the docker image node version in long run?

I would assume yes. @iartemiev will probably have more context on this.

**Pull request merged**
