### PR TITLE
feature(@aws-amplify/aws-amplify-vue): Add ability to omit sign up fi…

### PR DESCRIPTION
**Pull request by AndrewT51**
…elds by giving them a negative number as a displayOrder value.

issue #1901

*Description of changes:*
Add logic to remove fields that have been given a negative displayOrder, so that when the returned options are iterated through a 'v-for' directive, the omitted fields are not rendered to the ui. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jbouse** [comment]
This would solve the issue I'm currently encountering and forcing me to re-invent and write my own component which I'd rather not do.

**Comment by haverchuck** [comment]
@AndrewT51 @jbouse  - This is a great idea/use case, so thank you for submitting a PR.  We've kicked this around, and I think we'd like to implement a hideDefaults parameter on the config object in which users can list the keys of fields they want to hide.  We've already implemented for testing (but not yet released on the main branch), and we'd love to hear your feedback on going this route.  

@AndrewT51  - We'll make sure to give you credit in the merge!

**Comment by AndrewT51** [comment]
@haverchuck @jbouse Thanks for the feedback, I appreciate it.

@haverchuck I wasn't sure of the best way to add this functionality, but your suggestion of a hideDefaults parameter sounds intuitive and is probably a good way to go. Thanks for taking the time to look over this pr.

**Comment by haverchuck** [comment]
@AndrewT51 @jbouse  - The hideDefaults and hiddenDefaults options should now be available on our @unstable build. Thanks again for starting this conversation.

**Pull request closed without merging**
