### PR TITLE
Add appropriate typigns for sendCustomChallengeAnswer

### LINKED ISSUE #595: Fix sendCustomChallengeAnswer typings
Do you want to request a feature or report a bug?

Bug

What is the current behavior?

Current typings for `CognitoUser.sendCustomChallengeAnswer` are invalid. See https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/index.d.ts#L57 and notice the callback of type NodeCallback...then, look at the actual code https://github.com/aws/aws-amplify/blob/master/packages/amazon-cognito-identity-js/src/CognitoUser.js#L696-L706 and notice that the expected callback is a map of functions.

What is the expected behavior?

The typings should match the underlying JS or else things don't work as expected :)

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?

amazon-cognito-identity-js v2.0.2

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.

### PR DESCRIPTION
**Pull request by abemusic**
*Issue #, if available:*

Fixes #595

*Description of changes:*

Fixes the typings for the sendCustomChallengeAnswer method

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by buggy** [comment]
Both #566 and this PR contain definitions for `initiateAuth`. We probably don't need to merge this PR after #566 is merged. @abemusic can you confirm if that's correct?

**Comment by abemusic** [comment]
I'm not following. This PR is updating the `sendCustomChallengeAnswer` type definitions which were not matching what the underlying JS is doing. Apologies if I'm not understanding :)

**Comment by abemusic** [comment]
This is what the typings currently expect:

```
sendCustomChallengeAnswer(answer, function(error, result) {})
```

the underlying JS expects the same callbacks as authenticateUser:

```
sendCustomChallengeAnswer(answer, {
  onFailure(error) {
    ...
  },
  onSuccess(session) {
    ...
  },
  mfaRequired ...
  // and so on
});
```

**Comment by abemusic** [comment]
Bump

**Comment by abemusic** [comment]
@buggy @yuntuowang bump

**Comment by skonb** [comment]
What is the status of this issue? I think this is not fixed yet.

**Comment by elorzafe** [comment]
@abemusic thanks for your PR, this issue was fixed on this PR #1024

Thanks again!

**Pull request closed without merging**
