### PR TITLE
Add BigInteger tests

### PR DESCRIPTION
**Pull request by ericclemmons**
_Issue #, if available:_ #4422, #4427

This adds tests to validate both #4422 & #4427.

```console
yarn workspace amazon-cognito-identity-js jest --watch
```

The risk is that I had to update `babel` to `>7` so that `jest` could run tests.

~~As a result, we need to confirm that the build process is correct, which means possibly converting it to use @Amplifiyer's CJS/ESM build scripts.~~ Not possible, as these are `.js` files and we'd have to upgrade to TypeScript 3.7 to enable `allowJs` alongside `declarations`.

**There are two options:**

1. Merge this PR (which includes #4422 & #4427), which has _some_ risk due to the Babel upgrade to support testing with Jest.
1. Close this PR to avoid risk & merge #4422 & #4427 independently to credit our contributors.  This punts on the testing/Babel/build problem, so we're delaying the risk.

**Either way, this PR validates #4422 & #4427**.

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
I attempted to keep the builds as consistent as possible with the Babel upgrade, but Babel's output is different (of course).

**Comment by KesleyDavid** [comment]
Good morning guys, any predictions of the release of the update?

I have a client who is unable to access the system due to the negative number error.

It would help me a lot this update

**Comment by ericclemmons** [comment]
@KesleyDavid We're discussing this as a team this morning and get this resolved as soon as we can.

A lot of the team has been participating with re:Invent, so I wanted to make sure we get the right 👀 on this.  

Thanks for reaching out: it's _very_ helpful in getting the things that matter most to our customers across the goal line. 💪

**Comment by KesleyDavid** [comment]
@ericclemmons 

Good morning everyone, any update forecast to be released?

I really need this change, I'm developing a system, and we're unable to login.
And all future functions must be logged in

I would be very grateful for the update.

image

**Comment by ericclemmons** [comment]
We'll need to validate this with React Native just to be sure there are no regressions:
> https://aws-amplify.github.io/docs/js/start#option-2-use-react-native-cli-recommended-if-you-have-mobile-development-experience

**Comment by ericclemmons** [comment]
Here's a quick React Native test referencing `BigInteger.js` directly:

```diff
diff --git a/App.js b/App.js
index bb77580..d550968 100644
--- a/App.js
+++ b/App.js
@@ -6,6 +6,8 @@
  * @flow
  */

+import BigInteger from "amazon-cognito-identity-js/lib/BigInteger"
+
 import React from 'react';
 import {
   SafeAreaView,
@@ -39,6 +41,12 @@ const App: () => React$Node = () => {
             </View>
           )}
           <View style={styles.body}>
+            <View style={styles.sectionContainer}>
+              <Text style={styles.sectionTitle}>BigInteger Test</Text>
+              <Text style={styles.sectionDescription}>
+                {new BigInteger('-abcd1234', 16).toString(4)}
+              </Text>
+            </View>
             <View style={styles.sectionContainer}>
               <Text style={styles.sectionTitle}>Step One</Text>
               <Text style={styles.sectionDescription}>
```

##### Before
> Screen Shot 2019-12-17 at 2 20 57 PM

##### After
> Screen Shot 2019-12-17 at 2 21 49 PM

**Comment by ericclemmons** [comment]
I was able to validate that React Native goes through a different code path and experiences a _different_ error:
> https://github.com/aws-amplify/amplify-js/issues/4592

This PR should be safe to merge!

**Pull request merged**
