### PR TITLE
fix(@aws-amplify/pushnotification): make eligible variables final

### PR DESCRIPTION
**Pull request by Samaritan1011001**
#### Description of changes

This is a fix for a pushnotification issue when building for Android. Certain variables need to be declared `final`. It occurs only with lower react-native versions observed in version 63 and 64 which internally initiates a new project with lower Gradle versions.

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/9274

#### Description of how you validated changes
- Manual testing
- yarn test

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by calebpollman — COMMENTED** [review]
LGTM, but curious, does adding the `final` declarations cause any differing behavior in RN versions > 64?

**Comment by Samaritan1011001** [comment]
> LGTM, but curious, does adding the `final` declarations cause any differing behavior in RN versions > 64?

Yeah, no side effects with > 64 versions. Check with 66 and is working fine.

**Review by cshfang — APPROVED** [review]

**Comment by elorzafe** [comment]
@Samaritan1011001 can you create a matrix with all the versions of gradle, react-native we are having issues and the ones we are going to be fixed by this. All those combinations seems hard to keep track of, and might be better for have clear understanding for us and our customers which combinations we have tested.

**Review by elorzafe — APPROVED** [review]
LGTM 🌮 
Thanks @Samaritan1011001

**Review by calebpollman — APPROVED** [review]
Thanks @Samaritan1011001 

Can you please address the feedback left by @elorzafe, think it would be helpful to track

**Comment by Samaritan1011001** [comment]
Thank you all for the feedback. 
@elorzafe and @calebpollman, here is the table for it. 
| RN version & Gradle version | Tested |
| --- | --- |
| 60 & 3.4.1 | ✅  |
| 61 & 3.4.2 | ❌  |
| 62 & 3.5.2 | ❌  |
| 63 & 3.5.3 | ✅  |
| 64 & 4.1.0 | ✅  |
| 65 & 4.2.1 | ❌  |
| 66 & 4.2.2 | ✅  |

**Pull request merged**
