### PR TITLE
[TS] Fix Auth return types

### PR DESCRIPTION
**Pull request by murbanowicz**
Remove '| any' to improve TS users experience

*Description of changes:*
All methods accepting or returning `CognitoUser` not `CognitoUser | any`.
It is ruining TS experience as editors will only autocomplete the common parts which is nothing in this case.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by powerful23** [comment]
@murbanowicz thanks for your contribution. The reason we keep that `any` type is to avoid breaking users' code. We will correct this type in our next break release. Sorry based on that we cannot merge your pr now.

**Comment by murbanowicz** [comment]
Can we then merge it when possible? 
Could you explain why you see that as braking change? I just started using Amplify so I do not know the history, that's why I see no braking changes here

**Comment by powerful23** [comment]
@murbanowicz because some developers are using `user.username` in their code and if we merge this change, it will break their code when compiling with typescript, like this:
https://github.com/aws-amplify/amplify-js/issues/1666

**Comment by powerful23** [comment]
I will put this into the Auth v2 milestone as this should be resolved in the next big release.

**Pull request closed without merging**
