### PR TITLE
fix type error in types/Storage.ts

### LINKED ISSUE #8955: [Feedback] Error TS2344 (@aws-amplify/storage/lib-esm/types/Storage.d.ts)
**Page**: [`/start/getting-started/data-model/q/integration/[integration]`](https://docs.amplify.aws/start/getting-started/data-model/q/integration/angular/#connect-frontend-to-api)

**Feedback**: using Angular CLI: 12.2.7, Node: 12.14.0, Package Manager: npm 6.14.8, OS: win32 x64

Error: node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:44:46 - error TS2344: Type 'T[U]' does not satisfy the constraint '(...args: any) => any'.
  Type 'T["get"] | T["copy"] | T["put"] | T["remove"] | T["list"]' is not assignable to type '(...args: any) => any'.
    Type 'T["copy"]' is not assignable to type '(...args: any) => any'.
      Type '((src: StorageCopyTarget, dest: StorageCopyDestination, config?: any) => Promise<any>) | ((src: StorageCopyTarget, dest: StorageCopyDestination, config?: any) => Promise<...>) | undefined' is not assignable to type '(...args: any) => any'.
        Type 'undefined' is not assignable to type '(...args: any) => any'.

44 } : U extends 'copy' ? never : LastParameter<T[U]> & {

### PR DESCRIPTION
**Pull request by jamesaucode**
#### Description of changes

There was a type error in the `types/Storage.ts` file that causes user's build to fail unless they have `skipLibCheck: true` in their `tsconfig.json`
Will now check if the generic type has the `copy` function implemented before checking `T['copy']`

#### Issue #, if available

fixes #8955 

#### Description of how you validated changes
Tested locally + unit tests.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by petercwk — APPROVED** [review]
LGTM!

**Comment by clintfoster** [comment]
Is it possible there has a been a regression? I'm getting the following with Amplify `4.3.33`:

```
node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:47:178 - error TS2344: Type 'T' does not satisfy the constraint 'Record<string, any>'.

47 export declare type StorageGetConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'get'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'get'>, T>;
                                                                                                                                                                                    ~

  node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:47:38
    47 export declare type StorageGetConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'get'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'get'>, T>;
                                            ~
    This type parameter might need an `extends Record<string, any>` constraint.

node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:48:178 - error TS2344: Type 'T' does not satisfy the constraint 'Record<string, any>'.

48 export declare type StoragePutConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'put'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'put'>, T>;
                                                                                                                                                                                    ~

  node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:48:38
    48 export declare type StoragePutConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'put'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'put'>, T>;
                                            ~
    This type parameter might need an `extends Record<string, any>` constraint.

node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:49:187 - error TS2344: Type 'T' does not satisfy the constraint 'Record<string, any>'.

49 export declare type StorageRemoveConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'remove'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'remove'>, T>;
                                                                                                                                                                                             ~

  node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:49:41
    49 export declare type StorageRemoveConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'remove'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'remove'>, T>;
                                               ~
    This type parameter might need an `extends Record<string, any>` constraint.

node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:50:181 - error TS2344: Type 'T' does not satisfy the constraint 'Record<string, any>'.

50 export declare type StorageListConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'list'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'list'>, T>;
                                                                                                                                                                                       ~

  node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:50:39
    50 export declare type StorageListConfig<T> = T extends StorageProvider ? StorageOperationConfig<T, 'list'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'list'>, T>;
                                             ~
    This type parameter might need an `extends Record<string, any>` constraint.

node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:51:189 - error TS2344: Type 'T' does not satisfy the constraint 'Record<string, any>'.

51 export declare type StorageCopyConfig<T> = T extends StorageProviderWithCopy ? StorageOperationConfig<T, 'copy'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'copy'>, T>;
                                                                                                                                                                                               ~

  node_modules/@aws-amplify/storage/lib-esm/types/Storage.d.ts:51:39
    51 export declare type StorageCopyConfig<T> = T extends StorageProviderWithCopy ? StorageOperationConfig<T, 'copy'> : StorageOperationConfigMap<StorageOperationConfig<AWSS3Provider, 'copy'>, T>;
                                             ~
    This type parameter might need an `extends Record<string, any>` constraint.
```

**Comment by benedict1986** [comment]
I tested version 4.3.37, 4.3.33 and 4.3.32 with angular 14.2.4. All these versions have the same error as @clintfoster mentioned. When I turn off the strict mode, then there are no more errors.

**Comment by bonnie-gaggle** [comment]
I have the same issue with version 4.3.22 and 4.3.37 with Angular 14.0.4. Using `skipLibCheck: true` and turning off strict mode are not desirable solutions.

**Pull request merged**
