### PR TITLE
feat(@aws-amplify/core): add ui protected channel

### PR DESCRIPTION
**Pull request by reesscot**
#### Description of changes
This PR adds a new `ui` protected Hub channel.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by elorzafe — APPROVED** [review]
LGTM thanks @reesscot 🌮

**Review by alharris-at — APPROVED** [review]

**Review by zchenwei — APPROVED** [review]

**Review by calebpollman — APPROVED** [review]
LGTM 🚢

**Review by elorzafe — APPROVED** [review]
🌮

**Review by zchenwei — APPROVED** [review]
Looks goooood!

**Pull request merged**
