### PR TITLE
feat(@aws-amplify/ui-components): amplify-s3-image component

### PR DESCRIPTION
**Pull request by jordanranz**
_Description of changes:_
- `amplify-s3-image` component
 
Validation steps:
- From `amplify-js`, `cd packages/amplify-ui-components`
- Copy or update `aws-exports.js` file with new storage config, ping me if need be
- Run `yarn` then `yarn start`
- Storage example should show up first, if not navigate to Storage sample

Usage:
`<amplify-s3-image imgKey="amplify-logo.png">`
- `imgKey` represents the key of the image inside the Amplify CLI configured S3 bucket

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
I'm unable to run this locally.

1. `hub pr checkout 4591`

1. `yarn workspace @aws-amplify/ui-components start` yields

	> Screen Shot 2019-12-18 at 1 06 20 PM

I removed `yarn.lock`, but get the same error.

**Comment by ericclemmons** [comment]
@jordanranz The problem seems to be **that the `browser` field references a path that doesn't exist:**

Note the `browser` value here (`./dist/es/index.js`):
> https://unpkg.com/browse/@aws-sdk/signature-v4@0.1.0-preview.10/package.json

**`./dist` isn't published:**
> https://unpkg.com/browse/@aws-sdk/signature-v4@0.1.0-preview.10/

Removing the `browser` key (thus using `main`), rollup bundles successfully.

**Comment by ericclemmons** [comment]
Noticed that the problem may not exist with `0.1.0-preview.2` which is `latest`:
> https://unpkg.com/browse/@aws-sdk/signature-v4@0.1.0-preview.2/package.json

But for some reason I'm getting `0.1.0-preview.10`, hence the bug.

We may need to pin the version?

**Comment by sammartinez** [comment]
Closing as a result of the latest components that are live

**Pull request closed without merging**
