### PR TITLE
deps: Bump @aws-sdk to gamma.v8

### PR DESCRIPTION
**Pull request by wlee221**
_Issue #, if available:_ #6698, #6685

_Description of changes:_ This PR bumps `@aws-sdk` dependencies to version gamma.v8, and fixes predictions unit test where it does not configure identify properly.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by wlee221** [comment]
First several commits are from the chatbot release -- they were squashed and hence reappearing here. They make no code changes to main.

**Review by ashika01 — APPROVED** [review]
LGTM 👍

**Review by elorzafe — APPROVED** [review]
Thanks @wlee221 !! 🌮

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Pull request merged**
