### PR TITLE
fix: (Geo) Kebab case to Camel case config props

### PR DESCRIPTION
**Pull request by nadetastic**
#### Description of changes

- Geo Location services access config keys with kebab case, causing manually configured resources to fail. Updating the access to use camelCase as expected. (https://github.com/aws-amplify/amplify-js/issues/12870)

- Typo in comment under I18n (https://github.com/aws-amplify/amplify-js/issues/12752)

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/12870
https://github.com/aws-amplify/amplify-js/issues/12752

#### Description of how you validated changes
- Tested with local build

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by cwomack — DISMISSED** [review]
LGTM

**Review by calebpollman — CHANGES_REQUESTED** [review]
Think that the changes in `AmazonLocationServiceProvider` are non-breaking, but the fact that this is only an issue for Gen2 makes me concerned that there is something off with the returned shape of `Geo` in `parseAWSExports` as existing apps are using v6 do not exhibit the issue that this PR is addressing. Before approving:
- Need to understand why non-Gen2 customers are not facing this issue
- Need to see a successful run of the UI e2e tests with this change

**Review by kvramyasri7 — DISMISSED** [review]
Nice

**Comment by nadetastic** [comment]
> Think that the changes in `AmazonLocationServiceProvider` are non-breaking, but the fact that this is only an issue for Gen2 makes me concerned that there is something off with the returned shape of `Geo` in `parseAWSExports` as existing apps using v6 do not exhibit the issue that this PR is addressing. Before approving:
> 
> * Need to understand why non-Gen2 customers are not facing this issue
> * Need to see a successful run of the UI e2e tests with this change

@calebpollman I wouldn’t classify it as a Gen2 vs Gen1 thing but more of Legacy vs Resource config issue:
- Only happens when the Geo resources are manually added as ResourceConfig (camelCase) and does not happen if added as Legacy config (kebab_case)
- The library (or really AmazonLocationServiceProvider) is expecting it to be in kebab_case (aka legacy config) however it is in camelCase (aka Resource config)
- An important note (why it works when parseExports is used on LegacyConfig) - there are two object created when legacy config is used - one with camelCase and a copy in kebab_case, however, if Resource config is used, the legacy config object is not present which results in the error

Working on the the UI e2e tests

**Comment by calebpollman** [comment]
> @calebpollman I wouldn’t classify it as a Gen2 vs Gen1 thing but more of Legacy vs Resource config issue:
> 
> * Only happens when the Geo resources are manually added as ResourceConfig (camelCase) and does not happen if added as Legacy config (kebab_case)
> * The library (or really AmazonLocationServiceProvider) is expecting it to be in kebab_case (aka legacy config) however it is in camelCase (aka Resource config)
> * An important note (why it works when parseExports is used on LegacyConfig) - there are two object created when legacy config is used - one with camelCase and a copy in kebab_case, however, if Resource config is used, the legacy config object is not present which results in the error
> 
> Working on the the UI e2e tests

From what i am reading here, the fact that `parseAWSExports` returns both camelCase and kebab_case objects is part of the root issue since the return does not match the expected shape of the `ResourcesConfig`, and should be addressed as a part of this PR to align handling of projects with hand rolled `ResourcesConfig` and legacy configs.

Once the handling of the Geo config parsing is fixed, the updates [here](https://github.com/aws-amplify/amplify-js/pull/12921/files#diff-f674c8cdcaf8ed449c0d1110d1d0bc57b81561bceded531b92d1c82d0d124740L221), [here](https://github.com/aws-amplify/amplify-js/pull/12921/files#diff-f674c8cdcaf8ed449c0d1110d1d0bc57b81561bceded531b92d1c82d0d124740R291) and [here](https://github.com/aws-amplify/amplify-js/pull/12921/files#diff-f674c8cdcaf8ed449c0d1110d1d0bc57b81561bceded531b92d1c82d0d124740R330) to the differing inputs should be fine, but we should make sure that we do need to include lookup against the `search_indices` as well to ensure backwards compatibility.

**Comment by nadetastic** [comment]
Updated PR to address the issue where 	`parseAWSExports` was returning  both `searchIndices` and `search_indices`

**Comment by AllanZhengYP** [comment]
Close this request since it has been replaced by #13303 and released

**Pull request closed without merging**
