### PR TITLE
chore(storage): remove custom client support of SSE-C & re-enable skipped tests

### PR DESCRIPTION
**Pull request by AllanZhengYP**
#### Description of changes

* Remove custom client support of SSE-C
* Re-enable skipped tests
* Update umbrella package with storage umd build
* Update size-limit results

#### Description of how you validated changes
Unit tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kvramyasri7 — DISMISSED** [review]
Looks good to me. Thanks @AllanZhengYP. 
It would be nice to have a reason why there is increase in bundle size in description : )

**Review by jimblanc — DISMISSED** [review]

**Review by ashwinkumar6 — DISMISSED** [review]
Looks good to me,
Thank you Allan

**Comment by AllanZhengYP** [comment]
@kvramyasri7 It's unrelated to this change. The bundle test fails for logger only.

**Review by kvramyasri7 — APPROVED** [review]
LGTM

**Review by jimblanc — APPROVED** [review]

**Pull request merged**
