### PR TITLE
remove aws-sdk dependency

### PR DESCRIPTION
**Pull request by powerful23**
*Issue #, if available:*
To remove the dependency of aws-sdk in other packages.
*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mordka** [comment]
@powerful23 what's the reason for this? should we add `aws-sdk` dependency on the project level? I'm getting the following errors:
```
ERROR in ./node_modules/@aws-amplify/analytics/lib/Providers/AWSKinesisProvider.js
Module not found: Error: Can't resolve 'aws-sdk/clients/kinesis' in 'project/node_modules/@aws-amplify/analytics/lib/Providers'
ERROR in ./node_modules/@aws-amplify/interactions/lib/Providers/AWSLexProvider.js
Module not found: Error: Can't resolve 'aws-sdk/clients/lexruntime' in 'project/node_modules/@aws-amplify/interactions/lib/Providers'
ERROR in ./node_modules/@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js
Module not found: Error: Can't resolve 'aws-sdk/clients/mobileanalytics' in 'project/node_modules/@aws-amplify/analytics/lib/Providers'
ERROR in ./node_modules/@aws-amplify/analytics/lib/Providers/AWSPinpointProvider.js
Module not found: Error: Can't resolve 'aws-sdk/clients/pinpoint' in 'project/node_modules/@aws-amplify/analytics/lib/Providers'```

**Comment by powerful23** [comment]
@mordka no, can you try removing the node_modules and reinstall again?

**Comment by mordka** [comment]
@powerful23 I've done it multiple times, only adding `aws-sdk` to the project's package.json makes the project compiling, but I don't think it works. 
How is it supposed to resolve module in this place (e.g.)
https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSKinesisProvider.ts#L15

**Comment by powerful23** [comment]
@mordka because `@aws-amplify/analytics` depends on `@aws-amplify/core` and `@aws-amplify/core` has the dependency of `aws-sdk`.  So as long `@aws-amplify/analytics` is installed, then `aws-sdk` should be installed too.

**Pull request merged**
