### PR TITLE
feat(aws-amplify-react-native): Disable SignIn if username filled but…

### PR DESCRIPTION
**Pull request by milansusnjar**
… password empty

_Issue #, if available:_

_Description of changes:_

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Amplifiyer** [comment]
@milansusnjar Thanks for the contribution with this PR, we really appreciate it. I have a quick question, do you know how password less authentication will work with this change, i.e. using custom auth challenge where users are not required to enter the password in the sign in page.

**Comment by milansusnjar** [comment]
I'm not very familiar with aws-amplify and didn't know there is an option for password-less authentication. I was helping for a few days on a project with aws-amplify and saw that problem because if you don't fill anything and press Sign-in you get an error saying Something lambda something and had to fix that.

**Comment by ashika01** [comment]
@milansusnjar : we had an PR merged in which handles disable. Could you lets us know if this PR is still valid?

**Comment by milansusnjar** [comment]
> @milansusnjar : we had an PR merged in which handles disable. Could you lets us know if this PR is still valid?

I can't confirm this, I'm not on that project anymore.
Feel free to close this PR and if someone would have the same issue, they can create a new PR. It's a small change in the code.
Thanks.

**Pull request closed without merging**
