### PR TITLE
Change the signIn button text when loading

### PR DESCRIPTION
**Pull request by Anenth**
*Issue #, if available:*
Right now there is no indication about after user click on signin

*Description of changes:*
Changing the text button text to 'loading...' will help the user understand there is something happening.
This also helps here #3753 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jordanranz** [comment]
I like this improvement but we will need to add this improvement to each of the other frameworks we support to maintain consistency for the UX. Is this something you are willing to add to the PR?

**Comment by Anenth** [comment]
@jordanranz that make sense, I don't really have much experience other frameworks, maybe we could create issues for assigned to people who are good at respective frameworks?

**Comment by jordanranz** [comment]
I think we may want to use a spinner icon instead of actually rendering text on the button here. We are in the process of doing a UI component refactor to utilize web components under the covers. This is definitely a feature we would like to improve on for that project. I'll add the milestone to this PR.

**Comment by Anenth** [comment]
@jordanranz do you have any discussion about the "utilize web components under the covers" you mentioned here?

**Pull request closed without merging**
