### PR TITLE
fix(ops): pin babel-core and babel-cli version

### PR DESCRIPTION
**Pull request by jamesaucode**
#### Description of changes
`yarn build` was failing due to an issue in bable. Pinning the `@babel/core` and `@babel/cli` version.
See: https://github.com/babel/babel/issues/14273

#### Issue #, if available
N/A

#### Description of how you validated changes
ran `yarn setup-dev` from a fresh clone.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by elorzafe — APPROVED** [review]
LGTM thanks @jamesaucode 🌮

**Review by sammartinez — COMMENTED** [review]
LGTM 🌮

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Review by david-mcafee — APPROVED** [review]
LGTM!

**Comment by JLHwung** [comment]
The upstream Babel issue has been fixed in `7.17.4`.

**Pull request merged**
