### PR TITLE
fix(aws-amplify-react-native): auto-fill the user name field on ConfirmSignUp page

### LINKED ISSUE #6789: [aws-amplify-react-native] email field on ConfirmSignUp is not auto-filled after redirecting from SignUp page
**Describe the bug**
aws-amplify-react-native v4.2.5

After signed up, the auth flow goes to ConfirmSignUp correctly, however, the email field is not been auto filled

**To Reproduce**

1. Create an app with <Authenticator> (`usernameAttributes="email"`)
1. Go to 'SignUp'
1. fill out email and password and sign up
1. network request returns 200 and page redirected to ConfirmSignUp
1. email field shows up, but it is empty

**Expected behavior**
The email field should auto filled

**Code Snippet**
The problem is here:
https://github.com/aws-amplify/amplify-js/blob/6abbf5053978420ef008fc45968a54d0762943de/packages/aws-amplify-react-native/src/Auth/ConfirmSignUp.tsx#L75

It should consider the `usernameAttributes` cases.

Because the value been filled is coming from this logic:
https://github.com/aws-amplify/amplify-js/blob/6abbf5053978420ef008fc45968a54d0762943de/packages/aws-amplify-react-native/src/Auth/AuthPiece.tsx#L69

It is checking 3 cases, but the `ConfirmSignUp.getDerivedStateFromProps` always returns `username` which breaks it,

**Screenshots**
After changing that line, the bug is fixed
image

image

### PR DESCRIPTION
**Pull request by Albert-Gao**
close #6789

_Issue #6789, if available:_

_Description of changes:_
auto-fill the user name field on ConfirmSignUp page

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Albert-Gao** [comment]
close https://github.com/aws-amplify/amplify-js/pull/6790 and focus on this one to catch up with the main branch

**Comment by eddiekeller** [comment]
Hey @Albert-Gao , thanks for the submission. It looks good to me, but I don't really know the context around this change. Can you explain it for me so that I better understand?

**Comment by Albert-Gao** [comment]
@eddiekeller Sure, when using the Auth module, after signed up, the module will lead the user to the Confirm-Sign-Up page, the problem is the "email" / "username" field will be empty, so the user needs to type twice, which does not aligned with the other products out there.

with this PR being merged, 
- the user will see the "email"/"username" field being filled up with the registered value, unless the user refreshes the UI so we lose the data in the memory (but should not happen here, since it is react-native)
- also, this updates is scaleable, it is not hard-coded "email"/"username" field, it will aligned with whatever set as the main auth field from the `props.usernameAttributes`, so if the `props.usernameAttributes` will be something like `custom-ID`, this PR still works.

Just checked the current code, it still applies, since no changes to this file during this period.

**Comment by eddiekeller** [comment]
Hey @Albert-Gao , thanks for that explanation! Honestly, this is a great idea and a welcome change.

I just kicked off a "merge from main". I'll be watching it and as long as no tests fail, I'll approve!

**Review by eddiekeller — APPROVED** [review]

**Comment by eddiekeller** [comment]
I will merge soon - we have a deployment going out this morning so I am waiting until that is finished.

**Comment by Albert-Gao** [comment]
Hi, thanks 😊 this is great!

**Pull request merged**
