### PR TITLE
feat: Added support for specifying a custom endpoint for identity pools: issue 11275

### PR DESCRIPTION
**Pull request by snagatsu**
#### Description of changes
you can specify a custom endpoint for accessing a Cognito user pool, such as signIn or signOut. However, you cannot specify a custom endpoint for accessing an identity pool, such as fetchAuthSession. We have added a custom endpoint for the identity pool to the amplifyconfig and implemented a solution.

#### Issue #, if available
#11275

#### Description of how you validated changes
You built a custom app using Amplify and verified that you can access the AWS API Gateway URL you provided. AWS API Gateway referenced this URL.
https://aws.amazon.com/jp/blogs/architecture/enriching-amazon-cognito-features-with-an-amazon-api-gateway-proxy/

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nadetastic** [comment]
Hi @snagatsu thank you for your contribution! I'll review this with the team and follow up with any comments/updates.

**Comment by adadouche** [comment]
any updates on this PR?

**Comment by snagatsu** [comment]
there is no additional information available

**Comment by AllanZhengYP** [comment]
Hi @snagatsu, thanks a lot for the contribution. It helps a lot when we triage the feature requests. As of the implementation, the proposed one does not quite conform to our abstractions. 

The main issue is that we need to resolve the Amplify configuration for endpoint in the provider layer like here and keep the `awsClient` layer as straightforward as possible: https://github.com/aws-amplify/amplify-js/blob/f049a9eed80aac352739035c7018b3fba7aa58fe/packages/auth/src/providers/cognito/credentialsProvider/credentialsProvider.ts#L27

For changes that modifies that public interfaces like this one, we need to go through internal processes to make sure their naming is reasonable and consistent. We also need to update our documentation too. 

I will bring this to the team to discuss and keep you updated. The team might pick up the feature request.

**Comment by AllanZhengYP** [comment]
Hi @snagatsu 

After another review I think the change in current status makes sense. Currently we will be vetting the new configuration name with the team.

**Comment by dmytzo** [comment]
any updates on this PR?

**Comment by cwomack** [comment]
@snagatsu, @adadouche, and @dmytzo

Wanted to follow up on this.  We've got this feature request captured within issue #13445 and the corresponding PR #13552.  As such, we'll this PR out as a duplicate and recommend you follow those two for updates on progress.

**Pull request closed without merging**
