### PR TITLE
fix: upgrade CircleCI Cypress image to 12.22.8

### PR DESCRIPTION
**Pull request by david-mcafee**
#### Description of changes

Testing potential Cypress version upgrades

#### Issue #, if available

None - all builds are currently blocked on Circle CI

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jamesaucode — APPROVED** [review]
LGTM 🎉

**Review by nickarocho — APPROVED** [review]
LGTM!

**Review by elorzafe — APPROVED** [review]
LGTM 🌮

**Comment by david-mcafee** [comment]
Docs PR to address #1: https://github.com/aws-amplify/docs/pull/4165

**Pull request merged**
