### PR TITLE
Fix(amazon-cognito-identity-js): podspec for amazon-cognito-identity-js

### PR DESCRIPTION
**Pull request by brianjd**
*Description of changes:* Updated the podspec to point to the new repo, and use a variable release tag based on version.  That being said, there seems to be a release tag missing for 2.0.3.

### CODE REVIEW

**Comment by brianjd** [comment]
Is this still being reviewed?

**Comment by elorzafe** [comment]
@powerful23 what do you think?

**Comment by powerful23** [comment]
@elorzafe looks good to me. @brianjd did you test this in your local?

**Comment by brianjd** [comment]
@powerful23 Yes.

**Pull request merged**
