### PR TITLE
fix(@aws-amplify-core): updated browser ClientDevice to show android or ios for platform based off of userAgent

### PR DESCRIPTION
**Pull request by seang96**
Description of changes:

Using Ionic compiled on Android, endpoints were being set to APNs because the platform was  being detected as "linux armv8l". By checking userAgent, you can check if the device is android or not, and set the platform as android.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by seang96** [comment]
Any updates on doing this merge? Some solution for this is necessary, otherwise packages that uses ClientDevice to check if it is Android iOS or browser fails to work properly when using the Ionic Framework.

**Comment by haverchuck** [comment]
@seang96  - First off, apologies for the late response.  Thanks for your contribution.  
I think one concern with this PR is that it could change the analytics data being sent for existing applications.    As seen when this object is created and then later sent:

```
        const demographicByClientInfo = {
            appVersion: clientInfo.appVersion,
            make: clientInfo.make,
            model: clientInfo.model,
            modelVersion: clientInfo.version,
            platform: clientInfo.platform
        };
```

We definitely see the problem you've pointed out with APNs though, and a solution is needed.  So just to clarify:  is the issue you're having 

a) analytics data doesn't have 'android' as the platform, or
b) the endpoint is being set wrong.

If just B, then we can probably find a solution very similar to what you've already done, perhaps by not setting platform to the os value as your PR accomplishes, but returning 'os' as a new clientInfo attribute (or something like that?).  We could then key off that value to avoid setting APNs.

**Comment by seang96** [comment]
@haverchuck From what I could find it is just B where the endpoint is not being set correctly. See [528](https://github.com/aws-amplify/amplify-js/blob/master/packages/analytics/src/Providers/AWSPinpointProvider.ts#L528) of analytics. 

Should I update this PR modifying that line or make it a separate PR and change this one to have the OS attribute while keeping platform the same?

**Comment by haverchuck** [comment]
@seang96 It would be great if you just updated this PR. Thanks!

**Pull request closed without merging**
