### PR TITLE
Can't use "code" as query parameter

### PR DESCRIPTION
**Pull request by clethrill**
_Issue #:_ #3494 

_Description of changes:_ Added a guard in to stop the handling of the auth flow from hijacking any url with ?code=xxx in it

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by sw-yx — APPROVED** [review]

**Comment by clethrill** [comment]
@elorzafe @sw-yx what does it take to get this accepted and merged?

**Comment by sw-yx** [comment]
someone on the eng team needs to find time to review. unfortunately my approval means nothing 😂

**Review by ericclemmons — CHANGES_REQUESTED** [review]
Can we get some unit tests to cover this?  This improves our `code` handling heuristics, isn't full-proof, but is worth merging with tests 🙏

**Comment by clethrill** [comment]
I'm not very familiar with testing practices. I can have a look when I get some time or could someone more familiar could do have a go at it?

**Comment by sammartinez** [comment]
> I'm not very familiar with testing practices. I can have a look when I get some time or could someone more familiar could do have a go at it?

@elorzafe, Can you look to guide @clethrill on locations for updating unit tests here?

**Comment by clethrill** [comment]
@sammartinez @elorzafe I really need this in. I currently don't have the time or expertise to implement tests for this. Can we get this PR going somehow?

**Review by cmanger05 — APPROVED** [review]

**Comment by jcortez** [comment]
@clethrill @ericclemmons I have implemented unit tests for this fix in https://github.com/aws-amplify/amplify-js/pull/7306 . We are also running into this issue trying to integrate with a third party OAuth login and are waiting for this fix to be merged.

**Review by harrysolovay — APPROVED** [review]
This is valid & will work. Nice job!

**Review by manueliglesias — APPROVED** [review]
LGTM if #7306 tests look good and it  gets merged too

**Pull request merged**
