### PR TITLE
feat: custom user agent InternalCognitoUser

### PR DESCRIPTION
**Pull request by erinleigh90**
#### Description of changes
- Creates and exports InternalCognitoUser class from /internals scope with added userAgentValue parameter on public API's that result in service calls
- Sends received userAgentValue through cognito client service calls

NOTES
- Same as https://github.com/aws-amplify/amplify-js/pull/11643, but without the changes to Auth.ts - will make merging InternalAuth and InternalCognito cleaner. I will create a separate PR for the connecting piece in InternalAuth after InternalAuth and InternalCognitoUser are fully tested and approved.
- To see the changes to InternalCognitoUser after moving the changes over from CognitoUser, see [this comparison](https://github.com/erinleigh90/amplify-js/compare/8641fe4f6620e06e04c050428319a98d8b0e4ef4...cd95804b02013c0a4acd9a2126c3a184482c2d27#diff-e663fb319a13d200f6200fed8357e4975cbe1171a9743d6b8f9720fc852ac83e)

#### Description of how you validated changes
yarn tests pass
integ tests pass
smoke tested in sample app

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x]  Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jimblanc — APPROVED** [review]
This LGTM

**Review by israx — APPROVED** [review]
LGTM!

**Review by svidgen — APPROVED** [review]
Approving for `api-graphql` and `datastore` package changes.

**Review by stocaaro — APPROVED** [review]
There's a lot going on in this one and its mostly down in js :-/. I can follow the high level change. There's a fair amount of code moving with small changes and I haven't chased down those diffs to think them through.

This is inline what what you've done elsewhere and I trust that you've verified  those moved file edits. Based on this and confirmation that the overall change looks like I would expect.

Ship it.

**Review by stocaaro — COMMENTED** [review]
This [diff](https://github.com/aws-amplify/amplify-js/pull/11709/files/8641fe4f6620e06e04c050428319a98d8b0e4ef4..d8b1b4520fa8cff6a0c8aa3ffc8f31f40b7f2751#diff-e663fb319a13d200f6200fed8357e4975cbe1171a9743d6b8f9720fc852ac83e) helps Prettier did this no favors, but this is what I was looking for.

**Pull request merged**
