### PR TITLE
feat: Add capability for fetching logging constraints from API Gateway

### PR DESCRIPTION
**Pull request by cshfang**
#### Description of changes

This PR adds the ability to fetch remote logging constraints from S3 via API Gateway endpoint

#### Description of how you validated changes
Tested function in a sample web application:
* Function is able to send signed request to API Gateway for resource
* Updates to JSON file in S3 bucket are reflected in future responses
* Updates to ETag are returned as part of request `If-None-Match` header

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by ashika112 — APPROVED** [review]
LGTM

**Review by ashika112 — APPROVED** [review]

**Comment by ashika112** [comment]
Bundle size file needs to be updated to pass the test i guess.

**Comment by cshfang** [comment]
> Bundle size file needs to be updated to pass the test i guess.

Yeah, with the feature branches - especially those with multiple contributors - I think it makes sense to just update the size at once when the branch is ready. But I think I can probably do it here since this should be the last PR for a bit

**Review by ashwinkumar6 — APPROVED** [review]
LGTM 
Thanks @cshfang

**Pull request merged**
