### PR TITLE
Remove import of deprecated AsyncStorage from 'react-native' and change to '@react-native-community/async-storage'

### PR DESCRIPTION
**Pull request by idanlo**
related to #3956 

*Description of changes:*
change AsyncStorage import path from `react-native` to `@react-native-community/async-storage`. This will only work if the user already has `@react-native-community/async-storage` as a dependency in their project (or installed in their node_modules folder), I wasn't sure where to put that dependency (dev dependency, peer etc) so please correct me.

Because AsyncStorage from `react-native` is deprecated (https://facebook.github.io/react-native/docs/asyncstorage) and exported to a different library, saving auth state no longer works with react native, meaning that if a user exists the application, when he will open it again he will be logged out, this should be fixed as soon as possible.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bneigher** [comment]
+1 for this, this is a pretty bad breakage for us react native folks

**Comment by idanlo** [comment]
the build is failing because `@react-native-community/async-storage` is not in the dependencies in `package.json`, I don't know where to put it - devDependencies/dependencies/peerDependencies.
This is the only thing we need and then we can merge this.
This is a huge problem for react-native developers because our users are signed out every time they close the app

**Comment by jpaas** [comment]
Also, this is only 1 of about 5 or 6 instances in the code base where `AsynsStorage` is imported from `react-native`.

**Comment by idanlo** [comment]
@jpaas I would love to get more help on this. The only reason I opened a PR for this is to get more attention from contributors because this is a very important issue that is not addressed

**Comment by jpaas** [comment]
@idanlo I tried playing around with a fork but I didn't have much luck. The monorepo & submodules are difficult to work with. Although I had some success building I had trouble using the local modules in a test project.

I tried changing the import in:
`packages/amazon-cognito-identity-js/src/StorageHelper-rn.js`
`packages/aws-amplify-react-native/docs/Cache_AsyncStorageCache.js.html`
`packages/cache/src/AsyncStorageCache.ts`
`packages/core/src/RNComponents/reactnative.ts`
`packages/core/src/StorageHelper/reactnative.ts`
`packages/pushnotification/src/PushNotification.ts`

I did encounter your issue in the circleci build, so I added `@react-native-community/async-storage` to the deps in `packages/amazon-cognito-identity-js/package.json` because it was the only place where it seemed `react-native` was declared as a dep.

This got it building. But then as I said, it was hard installing the local packages with `file:` qualifiers.

**Comment by jpaas** [comment]
I put up another PR. It at least passes the checks, but I haven't been able to actually test that it works.

**Comment by jpaas** [comment]
Oops, here is the PR: https://github.com/aws-amplify/amplify-js/pull/4027

**Comment by Dellybro** [comment]
When will this be changed? This is affecting 3 projects of mine.

**Comment by billdami** [comment]
Also looking for updates on this, has anyone tried installing the PR's forked repo to verify if this works?

This is pretty much a dealbreaker for any new React Native apps attempting to use amplify for authentication.

**Comment by tmitchel2** [comment]
This issue should be reopened, currently AsyncStorage from React Native is still being used.  It is deprecated and this will break once it is fully removed.

**Comment by Ashish-Nanda** [comment]
Hi @tmitchel2 
The PR #8250 to migrate to the community version of AsyncStorage is being reviewed and will be merged shortly.
Please refer https://github.com/aws-amplify/amplify-js/pull/4027#issuecomment-837324409 for more details on the release.

**Comment by tmitchel2** [comment]
Great news and much appreciated @Ashish-Nanda and those involved

**Pull request closed without merging**
