### PR TITLE
fix: rewrite "forget password" to "forgot password"

### PR DESCRIPTION
**Pull request by wlee221**
_Issue #, if available:_ #6921, #7008.

_Description of changes:_ rewrite "forget password" to "forgot password". This is a follow up to #7008 and #6921.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Ashish-Nanda — APPROVED** [review]
LGTM 🚀

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Comment by amhinson** [comment]
The only other thing I'd consider here is customers with their own language customizations (https://docs.amplify.aws/ui/customization/translations/q/framework/react), as this wouldn't show the correct translation without updating their code.

**Comment by wlee221** [comment]
@amhinson, that is a good point. Because this is a deprecating component, we may want to just leave it as-is. What do you think @sammartinez?

**Comment by sammartinez** [comment]
> @amhinson, that is a good point. Because this is a deprecating component, we may want to just leave it as-is. What do you think @sammartinez?

I believe we can do this fix as this would be a patch for customers utilizing this component. I am OK with this change going in but to @amhinson, customers will need to upgrade their code.

**Pull request merged**
