### PR TITLE
Add Span Tag around '*' for Required Input Fields

### PR DESCRIPTION
**Pull request by selkhateeb**
_Issue #, if available:_
Not available.
_Description of changes:_
The 'span' tag allows for custom styling of required flag. Also this makes it consistent with the signup form.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sam-nasb** [comment]
@haverchuck this is a small UI enhancement to keep things consistent with signup form. It will allow for customizing the styles of required fields.
What's it going to take to get you to take a look at it?

**Comment by jordanranz** [comment]
Hey @sam-nasb, thank you for contributing!

This change looks good but unfortunately it would break anyone using the i18n utility for translating the english words and statements changed in this PR.

We can roll this into our [UI component refactor highlighted in this RFC](https://github.com/aws-amplify/amplify-js/issues/3279). This breaking change will need to be made to achieve consistency between the frontend frameworks that we support. 

If you would like, you can open a new issue with the use case required and we can track it for the release of the UI component refactor.

**Comment by sam-nasb** [comment]
@jordanranz, thank you for checking the code and your kind words.
The company changed direction on using this and I don't have a use case for it anymore. Feel free to close the PR if you don't think you have a need for it.
I appreciate you looking into it.

**Comment by jordanranz** [comment]
@sam-nasb, since this feature is already built into the UI component refactor project, I'll go ahead and close this PR. Thank you again for contributing!

**Pull request closed without merging**
