### PR TITLE
feat(auth): `forgetSpecificDevice` not in `Auth` class

### PR DESCRIPTION
**Pull request by tejasmr**
#### Description of changes

Added `forgetSpecificDevice` implementation in `Auth` class in `Auth.ts` which calls `forgetSpecificDevice` from `CognitoUser` class. Added unit tests for it in `auth-unit-test.ts`

#### Issue #, if available

#9904 

#### Description of how you validated changes
```
yarn build --scope @aws-amplify/auth
yarn test --scope @aws-amplify/auth
```
All test cases passed but got warnings about
```
@aws-amplify/auth:     console.error ../core/lib/Logger/ConsoleLogger.js:129
@aws-amplify/auth:       [ERROR] 10:48.608 AuthError - 
@aws-amplify/auth:                   Error: Amplify has not been configured correctly. 
@aws-amplify/auth:                   The configuration object is missing required auth properties.
@aws-amplify/auth:                   This error is typically caused by one of the following scenarios:
@aws-amplify/auth:       
@aws-amplify/auth:                   1. Did you run `amplify push` after adding auth via `amplify add auth`?
@aws-amplify/auth:                       See https://aws-amplify.github.io/docs/js/authentication#amplify-project-setup for more information
@aws-amplify/auth:       
@aws-amplify/auth:                   2. This could also be caused by multiple conflicting versions of amplify packages, see (https://docs.amplify.aws/lib/troubleshooting/upgrading/q/platform/js) for help upgrading Amplify packages.
```
Is this expected? 
Also where should I add docs? Is it in authclass.html and/or search.js? or is it elsewhere?

#### Checklist

- [x] PR description included
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] `yarn test` passes
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Scy147** [comment]
@abdallahshaban557 Any update on this?

**Comment by abdallahshaban557** [comment]
Hi @Scy147 - we do not have updates yet, our team was resolving a couple of high priority issues for customers using our Auth category. We will get back to you soon with an update!

**Comment by abdallahshaban557** [comment]
Hi @tejasmr - thank you for your contribution! Our team is planning to re-write the Authentication category, and introduce this similar functionality. One of our team members will reach out to you with some recommendations on changes to ensure your contribution matches our new naming conventions!

**Comment by tejasmr** [comment]
Sure, @abdallahshaban557, I will follow up with them

**Comment by haverchuck** [comment]
Hi @tejasmr - We don't currently offer the abilty to forget a device - other than the current device - in any of our Amplify libraries, but I will bring this up with our teams.

**Comment by haverchuck** [comment]
Hi @tejasmr - Chatted with our other library teams, and our other libraries provide this functionality with an optional parameter for a device in the existing `forgetDevice` API.  Would you be up for making that non-breaking change in this PR, instead of introducing a new API? You could probably use the `IAuthDevice` interface.

**Comment by tejasmr** [comment]
I rolled back the commits but it closed the issue, so I created a new PR #10510 for this @haverchuck

**Pull request closed without merging**
