### PR TITLE
Fixing Sign In spanish translation

### PR DESCRIPTION
**Pull request by fabripautasso**
#### Description of changes
`Sign In` Spanish translation is wrong. Fixing it to take the proper translation.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by evcodes** [comment]
Hey Frabricio,

I am going to work on reproducing this and check if it breaks the UI. I will get back to you ASAP

**Review by evcodes — APPROVED** [review]
LGTM, merging the amplify-react changes

**Comment by evcodes** [comment]
Hey @fabripautasso, thank you for your contribution. I worked in your changes along with other additions in this commit: https://github.com/aws-amplify/amplify-js/commit/70fcf949e09842c196249a7e8283a2745819500b. You rock!

**Comment by fabripautasso** [comment]
> Hey @fabripautasso, thank you for your contribution. I worked in your changes along with other additions in this commit: [70fcf94](https://github.com/aws-amplify/amplify-js/commit/70fcf949e09842c196249a7e8283a2745819500b). You rock!

Cool, thanks @evcodes !

**Pull request closed without merging**
