### PR TITLE
feat(aws-amplify-react-native): Federated Signin for react-native with Google and Facebook providers

### PR DESCRIPTION
**Pull request by nidsharm**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sky1234** [comment]
is this fix integrating federated signin with cognito userpool?

**Comment by ganap** [comment]
When will this be available?

**Comment by ganap** [comment]
When will this be available?

**Comment by ganap** [comment]
Any time soon? Or is there another way to do Federated login  in React-Native? I would think this would be a high priority item..

**Comment by tobiastornros** [comment]
Any progress on this?

**Comment by 10ky** [comment]
The Cognito Identity pool has "Login with Amazon" as one of its supported federated identity providers.  Awsmobile's user signin feature does not have "Login with Amazon" as an option.   I hoping to see "Login with Amazon" federated signin supported by Amplify react-native lib and Awsmobile.  Don't forget your own federated identity provider :O)

**Comment by ignaciosantise** [comment]
@nidsharm any updates? 😄

**Comment by leesolway** [comment]
Would love to see a solution to this problem merged in... Any news?

**Comment by undefobj** [comment]
> Would love to see a solution to this problem merged in... Any news?

@leesolway we're very close to providing a React Native authentication HOC for the hosted UI. You can follow the PR here: https://github.com/aws-amplify/amplify-js/pull/2665

Additionally we are working on a revamp of the federatedSignIn functionality which will allow more flexibility across any platform. Please take a look at the RFC and comment with any thoughts: https://github.com/aws-amplify/amplify-js/issues/2716

**Comment by powerful23** [comment]
I am going to close this pr as #2665 has been merged.

**Pull request closed without merging**
