### PR TITLE
Checking null value using string predicates

### PR DESCRIPTION
**Pull request by leandrogehlen**
Checking null value using string predicates

#### Description of changes

Checking null or undefined value using beginWith, contains and `notContains` predicate operator

#### Description of how you validated changes

Using `startWith`, `contains` and `notContains` predicate operator results in 
`Cannot read property 'indexOf' of null` when model has null attribute values

#### Checklist

- [X] PR description included
- [X] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by iartemiev — CHANGES_REQUESTED** [review]
Thank you for opening the PR, @leandrogehlen! 

Please delete the `package-lock.json` file, otherwise, the PR looks good!

**Review by iartemiev — CHANGES_REQUESTED** [review]
Could you please also add some test coverage for this change to `packages/datastore/__tests__/util.test.ts`?

You can add a new `test` block for `validatePredicateField` and just cover `beginsWith`, `contains`, and `notContains` with a few cases each that validate the behavior.

**Comment by leandrogehlen** [comment]
I really tried, but I couldn't do it.

I need some help:

```ts
test('validatePredicate', () => {
  const classes = initSchema(testSchema());
		

  const { Model } = classes as {
    Model: PersistentModelConstructor<Model>;
  };

  const model = new Model({
    field1: 'Some value',
    dateCreated: new Date().toISOString()
  });		
  
  const predicate =  ModelPredicateCreator.createFromExisting(
   ...// model.optionalField1("contains", "value")
  );	
  
  expect(validatePredicate(model, ..., predicate).toEqual(false);
```

**Comment by iartemiev** [comment]
@leandrogehlen I don't think you need to test `validatePredicate` for this PR. Just `validatePredicateField`. 

I would add an `export` at the beginning of [utilts:79](https://github.com/aws-amplify/amplify-js/blob/57436aa16056ec49fda64ecbaf2b1172f4753fa8/packages/datastore/src/util.ts#L79), then import `validatePredicateField` into `util.test.ts` and add e.g.,

```js
test('validatePredicateField', () => {
  expect(validatePredicateField(undefined, 'contains', 'test')).toEqual(false);

  expect(validatePredicateField('testtest', 'contains', 'test')).toEqual(true);
});
```

And so on for `beginsWith`, `contains`, and `notContains`

**Comment by leandrogehlen** [comment]
@iartemiev, you are right. Sorry, i did not pay attention.

The tests has been added

**Review by iartemiev — APPROVED** [review]
LGTM! 👍🏻  Thanks again, @leandrogehlen!

**Pull request merged**
