### PR TITLE
Fix getMFAOptions data extraction

### PR DESCRIPTION
**Pull request by sjawhar**
*Description of changes:*
`cognitoUser.getMFAOptions()` is currently broken. It always returns undefined, because `userData.MFAOptions` is not defined. Instead, there are two keys in `userData` containing MFA info: `UserMFASettingList` and `PreferredMfaSetting`. So we should return those instead.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by haverchuck** [comment]
@sjawhar - Since the name of the function you've updated is getMFAOptions, I think it makes sense that it returns the MFAOptions value.  What are your thoughts on creating a similar function called getMFASettings to return the values that your PR currently adds to getMFAOptions?  If you do not want to make this update it's ok - we can take it on.

**Comment by sjawhar** [comment]
The problem is that `MFAOptions` is undefined, or at least was when I opened the pull request. There was no `MFAOptions` attribute of `userOptions`

**Comment by haverchuck** [comment]
@sjawhar Yes - MFAOptions will only be defined if SMS MFA settings are enabled.  Getting the setting variables that you are using in the PR is a fine solution for more comprehensive data; however, I think it would be good to retrieve these in a seperate function.  There may be some developers who are using MFAOptions in scenarios where it does bring back data, and suddently giving them additional properties in the response is less desirable than providing a seperate function for developers to use going forward (IMO).

**Comment by sjawhar** [comment]
@haverchuck I just ran through and tested it real quick. Tried when I have no MFA, when I have SMS, and when I have TOTP. `userData.MFAOptions` was undefined in all three cases. Can you help me understand what I'm missing?

**Comment by davidgatti** [comment]
Pickard

**Comment by haverchuck** [comment]
@sjawhar I'm contacting the service team with this, please stay tuned.

**Comment by mlabieniec** [comment]
Just FYI on this the cognito team has an update that they will be pushing out to address this asap, will keep the thread posted once the update is complete!

**Comment by rachitdhall** [comment]
We have identified an issue in Amazon Cognito where the Admin/GetUser service response doesn’t correctly populate MFAOptions when on a pool with MFA required and the end user uses SMS MFA. We are actively working on the fix and will circle back when the service update is completed.

Rachit,
Development Manager, Amazon Cognito

**Comment by davidgatti** [comment]
LOL :D new technique to pretend Issues are being solved? Love It! :D

**Comment by davidgatti** [comment]
What the patch-1 about? going from space to tabs? :D

**Comment by svidgen** [comment]
I'm touching base with @rachitdhall internally. The Cognito service is still behaving as described in the OP from what I can tell. But, I'm not actually clear as to what the correct behavior is there.

I'll also need to base with @haverchuck, I think. I'm honestly not 100% sure how `getMFAOptions()` is intended to be use. So, I more background to provide guidance on this PR.

**Comment by svidgen** [comment]
As it turns out, [`MFAOptionType` is no longer supported *at all*](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_MFAOptionType.html). So, this method is being deprecated in the client library, and I'll be closing this particular PR.

You could always use `user.getUserData()` *directly*. But, I'm not actually clear on what the intended use-case is here. So, I'd suggest checking the [MFA docs](https://docs.amplify.aws/lib/auth/mfa/q/platform/js) for the recommended MFA setup and filing a separate issue if something is missing or unclear in those docs.

**Pull request closed without merging**
