### PR TITLE
rewrite retry as promise based

### LINKED ISSUE #8514: "ReferenceError: regeneratorRuntime is not defined" in v4
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Vue

### Amplify APIs

Authentication

### Amplify Categories

auth

### Environment information

<details>

```
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 22.42 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 7.19.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.59
    Firefox: 84.0.2
    Safari: 14.1.1
  npmPackages:
    @aws-amplify/datastore: ^3.1.1 => 3.1.2 (2.10.1)
    @creativelayer/chalk-icons: ^1.1.2 => 1.1.2
    @creativelayer/chalk-ui: ^1.32.0 => 1.32.0
    @types/jest: ^26.0.23 => 26.0.23
    @typescript-eslint/eslint-plugin: ^4.28.1 => 4.28.1
    @typescript-eslint/parser: ^4.28.1 => 4.28.1
    @vitejs/plugin-vue: ^1.2.4 => 1.2.4
    @vue/compiler-sfc: ^3.1.2 => 3.1.2
    @vue/eslint-config-standard: ^6.0.0 => 6.0.0
    @vue/eslint-config-typescript: ^7.0.0 => 7.0.0
    @vue/test-utils: ^2.0.0-rc.9 => 2.0.0-rc.9
    @xstate/vue: ^0.6.0 => 0.6.0 (0.5.0)
    autoprefixer: ^10.2.6 => 10.2.6
    aws-amplify: ^3.4.3 => 3.4.3
    buffer: ^6.0.3 => 6.0.3 (4.9.2)
    cypress: ^7.6.0 => 7.6.0
    dynamic-import-polyfill: ^0.1.1 => 0.1.1
    eslint: ^7.29.0 => 7.29.0
    eslint-plugin-cypress: ^2.11.2 => 2.11.3
    eslint-plugin-import: ^2.23.4 => 2.23.4
    eslint-plugin-jest: ^24.3.6 => 24.3.6
    eslint-plugin-vue: ^7.12.1 => 7.12.1
    jest: ^26.6.3 => 26.6.3
    mockdate: ^3.0.5 => 3.0.5
    postcss: ^8.3.5 => 8.3.5
    tailwindcss: ^2.2.4 => 2.2.4
    ts-jest: ^26.5.5 => 26.5.6
    typescript: ^4.3.4 => 4.3.4
    vite: 2.2.4 => 2.2.4
    vue: ^3.0.11 => 3.1.2
    vue-jest: ^5.0.0-alpha.10 => 5.0.0-alpha.10
    vue-loader: ^16.2.0 => 16.2.0
    vue-router: ^4.0.10 => 4.0.10
    vue-router-mock: 0.0.3 => 0.0.3
    xstate: ^4.20.1 => 4.20.1
  npmGlobalPackages:
    @aws-amplify/cli: 5.0.2
    np: 7.5.0
    npm: 7.19.0
```

</details>

### Describe the bug

When using `aws/amplify` and import the Auth part, `Auth.signOut()` throws a "ReferenceError: regeneratorRuntime is not defined" error when using Vite as the builder.

### Expected behavior

Not to throw an error

### Reproduction steps

1. Use Vite (latest)
2. Use aws/amplify (latest)
3. Sign in with Auth
4. Call `Auth.signOut()`
5. Results in error

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line


```

</details>

### aws-exports.js

```javascript
/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://hqptdavyajhyrjy5hsucf7s4aq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dvzhiao7afalnd4ngy656gg57i",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://hl5y1tbtsc.execute-api.us-east-1.amazonaws.com/reinier",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:a5a66054-9e29-4237-bd34-92f3f757230c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bPyCr6PJt",
    "aws_user_pools_web_client_id": "6pgdqdokmqvtnv7d732teu478f",
    "oauth": {},
    "aws_user_files_s3_bucket": "creativelayeromsf1e74c96893d4c5180677f6c846170d102506-reinier",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;

```

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

The error doesn't occur with any v3 version. I'll see if any of the old v4 versions also work, but I have my doubts.

### PR DESCRIPTION
**Pull request by hkjpotato**
##### TL,DR
Rewrite the `retry` method in `amazon-cognito-identity-js` as promised based, to avoid the implicit dependency on the `regeneratorRuntime` polyfill.

##### Details
This is to fix #8514, a breaking change reported by the customer. The issue is caused by a recent change in `amazon-cognito-identity-js`, where `aysnc` and `await` syntax is [used](https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/src/Client.js#L177-L201) for the first time in that package.

It creates an implicit dependency on `regeneratorRuntime` in all its built code (umd/es/commonjs), and affect downstream packages like auth.

Screen Shot 2021-07-01 at 10 42 50 AM

- `amazon-cognito-identity-js` was written long ago with traditional nodejs callback style + promise.
- It was written in ES6 and transpiled to ES5 by babel using `@babel/preset-env`, which includes `babel/plugin-transform-regenerator` (see [discussion](https://github.com/babel/babel/issues/9849#issuecomment-487040428))
- The plugin detects `async` and `await` keyword and convert them into  the `regeneratorRuntime` methods, assuming `regeneratorRuntime` is made available globally.

Customers now have to explicitly add and define `regenerator-runtime` in their codebase (not needed for CRA). They don't need to before. Rewriting the `retry` as promised base helps avoid the extra step for the customers. 

----

Why other package (Auth) does not have this problem? Because they are written in typescript and get compiled by tsc first. Typescript use inline [`__awaiter`](https://stackoverflow.com/questions/47995484/whats-the-purpose-of-typescripts-awaiter) helper to deal with `async/await`.

In the future, we could consider unifying the language and compile tool, to avoid polyfilling ES6 feature differently. This is out of scope of the quick fix though.

#### Issue #, if available

#8514

#### Description of how you validated changes
`async/await `is just syntax sugar for promise, switching the syntax does not affect how javascript gets executed in terms of the event loop (micro tasks).

profiling on `retry` by async/await
Screen Shot 2021-07-01 at 10 38 34 AM

profiling on `retry` by promise
Screen Shot 2021-07-01 at 10 39 33 AM

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by elorzafe — APPROVED** [review]
LGTM thanks @hkjpotato 🌮

**Comment by hkjpotato** [comment]
going to test it with the integration test sample

**Review by ericclemmons — APPROVED** [review]
Thanks for doing this! It's a lesson for us to learn that differences in build tooling can introduce different behavior for the same implementation 😓

**Review by svidgen — APPROVED** [review]

**Comment by TheDutchCoder** [comment]
I'm the customer who reported this and I think (but I'm not 100% sure), that the issue is that the transpiled version of this package is being used, instead of the native ESM version.

Maybe there's no ESM version at all (I haven't checked), but the transpiled version seems to have some external dependencies still that users have to configure in their build tool (webpack/Vite/etc).

However (like in our case) we don't cater to older browsers and depend on ESM modules all the way (and certain functionality like, in this case, async/await).

I've wondered if there's a way to have all aws internal dependencies be resolved as ESM modules when appropriate, but I would assume that's a much larger discussion?

Anyway, just wanted to shed some light on it! Thanks for taking care of this!

**Comment by hkjpotato** [comment]
will send out integ test change in another pr

**Comment by hkjpotato** [comment]
@TheDutchCoder we need to look more into it in the future but I think ESM is the module system, while `async` and `await` is a ES6 syntax defined in its spec https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-async-function-definitions

**Pull request merged**
