### PR TITLE
fix(amazon-cognito-identity-js): import React Native headers from <React/*.h>

### PR DESCRIPTION
**Pull request by schiller-manuel**
#### Description of changes

Import React Native headers from <React/*.h>
This ensures compatibility with Expo SDK 44.

#### Issue #, if available

see https://github.com/expo/expo/issues/15622 and for a detailed description this comment: https://github.com/expo/expo/issues/15622#issuecomment-997225774

#### Description of how you validated changes

1. create a new react native project: `npx react-native init ExpoIssue --template react-native-template-typescript`
2. install `amazon-cognito-identity-js`:  `npm install amazon-cognito-identity-js && npx pod-install`
3. install `expo-modules`: `npx install-expo-modules`

Executing `npm run ios` now **fails to build.**

The `master` branch demonstrates the failing state: https://github.com/schiller-manuel/expo-issue

4. apply this PR using `patch-package` to `amazon-cognito-identity-js`

Executing `npm run ios` now **successfully builds**.

The `patch-package-amazon-cognito-identity-js` branch demonstrates this patch:  https://github.com/schiller-manuel/expo-issue/tree/patch-package-amazon-cognito-identity-js

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cshfang** [comment]
@schiller-manuel Thanks for the PR. This only came to my attention recently but it lgtm. I wasn't able to reproduce this following your steps anymore as it seems that the Expo team has already introduced a patcher which transforms the double-quoted imports when running `npx install-expo-modules` in the meantime (https://github.com/expo/expo/pull/15655). Will approve as I think this is probably still a good change since it is possible to install Expo manually as well.

**Review by cshfang — APPROVED** [review]

**Review by hkjpotato — APPROVED** [review]
I have checked with Expo team this is backward compatible with RN >= 4.0 (five years ago)

> yes, the double-quoted import is for react-native < 0.40 which is almost five years ago. after react-native >= 0.40 and later react-native has fully CocoaPods adoption, the #import <> style is supported and recommended.

see more details here https://github.com/expo/expo/pull/15458

**Comment by hkjpotato** [comment]
@schiller-manuel thank you for the contribution!

**Comment by schiller-manuel** [comment]
@hkjpotato thanks for merging!
do you have any ETA on a release that contains this fix?

**Comment by hkjpotato** [comment]
@schiller-manuel  this is released in the newer version of Amplify

**Pull request merged**
