### PR TITLE
fix(pushnotification): deprecated imports

### LINKED ISSUE #8023: Update @aws-amplify/pushnotifiaction react native to support androidx library in android
**Describe the bug**
When try to build release in android it gives me that build failed because of syntax error. that happens because @aws-amplify/pushnotifiaction android depends on deprecated v7 support library and react-native 60 and above uses androidx

**To Reproduce**
1. migrate @aws-amplify/pushnotifiaction to use androidx

 - OS: android 9
- react-natvie 60 and above

**error stack**
```
> Task :aws-amplify_pushnotification:compileReleaseJavaWithJavac FAILED
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationAttributes.java:16: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;
                                 ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:34: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:28: error: cannot find symbol
import android.support.v4.app.NotificationCompat;
                             ^
  symbol:   class NotificationCompat
  location: package android.support.v4.app
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\RNPushNotificationMessagingService.java:29: error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
                                 ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationAttributes.java:132: error: cannot find symbol
    @NonNull
     ^
  symbol:   class NonNull
  location: class RNPushNotificationAttributes
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                              ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:192: error: cannot find symbol
                    .setPriority(NotificationCompat.PRIORITY_HIGH)
                                 ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:191: error: cannot find symbol
                    .setVisibility(NotificationCompat.VISIBILITY_PRIVATE)
                                   ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:188: error: package NotificationCompat does not exist
            NotificationCompat.Builder notification = new NotificationCompat.Builder(context)
                                                                            ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:258: error: package NotificationCompat does not exist
            notification.setStyle(new NotificationCompat.BigTextStyle().bigText(bigText));
                                                        ^
E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java:309: error: cannot find symbol
                notification.setCategory(NotificationCompat.CATEGORY_CALL);
                                         ^
  symbol:   variable NotificationCompat
  location: class RNPushNotificationHelper
Note: E:\react\funbits-provider-app\node_modules\@aws-amplify\pushnotification\android\src\main\java\com\amazonaws\amplify\pushnotification\modules\RNPushNotificationHelper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':aws-amplify_pushnotification:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 9m 15s
```

### PR DESCRIPTION
**Pull request by Simon-TechForm**
#### Description of changes
Removes a lot of unused imports and migrates deprecated android.support imports to androidx. Androidx has been used since `react-native@0.60` and this package has relied on jetify ever since.

#### Issue #, if available
Resolves #8023 and a couple of other issues that were closed with "run jetify".

#### Description of how you validated changes
Installed pushnotification in an android app without running jetify.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Samaritan1011001 — APPROVED** [review]
Tested the changes on RN versions 60, 65, 67 and 68. 
LGTM. Thank you for your contribution @Simon-TechForm

**Comment by Simon-TechForm** [comment]
@Samaritan1011001 @cshfang @calebpollman any chance that this could be looked at? amplify-js is currently the only library requiring us to keep jetify in our build pipeline.

**Comment by Simon-TechForm** [comment]
@Samaritan1011001 @cshfang @calebpollman any chance that this could be looked at? amplify-js is currently the only library requiring us to keep jetify in our build pipeline.

**Review by cshfang — APPROVED** [review]
Lgtm thanks for the contribution!

**Pull request merged**
