### PR TITLE
fix(@aws-amplify/core): add zen-observable dependency

### PR DESCRIPTION
**Pull request by ericclemmons**
_Issue #, if available:_ #4506

`core` uses `zen-observable`:

https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/core/src/Util/Reachability.ts#L1

But it isn't declared as a dependency:
https://github.com/aws-amplify/amplify-js/blob/8d2ba6e85031a7880d2b573e1f68108d22a7de54/packages/core/package.json#L39-L46

Users who had multiple packages installed (such as API/PubSub) would get this as a  transitive dependency, which hid the error.

See this demo repo: https://github.com/ericclemmons/amplify-js-issues-4506

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ericclemmons** [comment]
@Amplifiyer How would you test that `@aws-amplify/core`'s `zen-observable` dependency installs via `@aws-amplify/auth` in a project like https://github.com/ericclemmons/amplify-js-issues-4506?

`yarn link` is normally the way to go for local development, but there must be a command or two I'm missing to do this successfully.

**Comment by Amplifiyer** [comment]
> @Amplifiyer How would you test that `@aws-amplify/core`'s `zen-observable` dependency installs via `@aws-amplify/auth` in a project like https://github.com/ericclemmons/amplify-js-issues-4506?
> 
> `yarn link` is normally the way to go for local development, but there must be a command or two I'm missing to do this successfully.

If I understand your question correctly, you can publish locally using verdaccio and then import the auth package (which should now bring the verdaccio published core package and would have zen-observable dependency). Let me know if I misunderstood your question.

Also shouldn't the rimraf dependency be part of the monorepo dependencies?

**Comment by ericclemmons** [comment]
@Amplifiyer I see.  Verdaccio isn't mentioned for public contributors in https://github.com/aws-amplify/amplify-js/wiki/Local-Development or https://github.com/aws-amplify/amplify-js/blob/master/CONTRIBUTING.md, so I didn't know it was a sanctioned workflow.

`rimraf` is a root-level dependency, as well as in a few package's `devDependencies`: https://github.com/aws-amplify/amplify-js/search?utf8=%E2%9C%93&q=rimraf&type=

It was added here because `yarn workspace @aws-amplify/core build` didn't work initially (likely due to hoisted dependencies failing to install prior).

Let me know if you'd like me to revert a60ce75, and we can discuss monorepo build tooling another time 🙏

**Comment by Amplifiyer** [comment]
> It was added here because yarn workspace @aws-amplify/core build didn't work initially (likely due to hoisted dependencies failing to install prior).
>
> Let me know if you'd like me to revert a60ce75, and we can discuss monorepo build tooling another time 🙏

Yeah, we moved all the common devdependencies to the root level in all the packages where we added ES6 builds. I believe the idea is to run yarn bootstrap from the root level first before building the individual packages. I think this part is missing from the local development wiki as well. Maybe we can create a story to update this wiki?

**Comment by ericclemmons** [comment]
@Amplifiyer Updated & ready for 👀

**Comment by ashika01** [comment]
Ship it 🚢

**Comment by mtraynham** [comment]
Any word on this getting merged?  Seems rather important if the project is missing dependencies.

**Comment by ericclemmons** [comment]
@mtraynham Sorry for the delay!  We merged #4494 and didn't bring this with it by mistake.

**Comment by hisham-blackbuck** [comment]
Hi guys, any word on when this patch would get released?

**Pull request merged**
