### PR TITLE
adding KinesisClient endpoint configuration to AWSKinesisProvider

### PR DESCRIPTION
**Pull request by dioxmio**
_Issue #, if available:_

No opened issue, just a piece of missing configuration missing

_Description of changes:_

Adding the missing `endpoint` configuration to the AWSKinesisProvider. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dioxmio** [comment]
@amhinson could you give it a quick look? it's just a basic config variable propagation. many thanks :D

**Comment by dioxmio** [comment]
> Hey @dioxmio thanks for the PR! A couple of questions:
> 
> * Do you happen to have a link to where this `endpoint` option is documented?
> * Could you add/update the tests for this additional option?

thanks for the review @amhinson . As you suggested I have added a simple unit test to make sure parameter is indeed passed on when invoked `initKenesis`

here is the link to the KinesisClient endpoint:

https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Kinesis.html

could you check again? thanks :)

**Comment by iartemiev** [comment]
Thank you @dioxmio!

**Comment by dioxmio** [comment]
awesome, many thanks all :)

**Pull request merged**
