### PR TITLE
fix(@aws-amplify/auth): fix storage bug for auto sign in value

### PR DESCRIPTION
**Pull request by helgabalashova**
#### Description of changes

Changing set auto sign in storage value to string from boolean

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by elorzafe — APPROVED** [review]
Looks good, thanks @helgabalashova 🌮

**Comment by ShivamJoker** [comment]
Can you guys please merge this I am getting the error
```
The value for key "@MemoryStorage:amplify-auto-sign-in" is not a string. This can lead to unexpected behavior/errors. Consider stringifying it.
Passed value: true
```

**Review by elorzafe — APPROVED** [review]

**Review by Samaritan1011001 — APPROVED** [review]
LGTM, thank you!

**Review by stocaaro — APPROVED** [review]
This is the type of bug that would be a great candidate to add testing for. Since this is an emergency break fix type of thing, I have not objections to getting it approved / out promptly, but seeing a unit test added to capture the use-case should be captured as follow on work.

**Pull request merged**
