### PR TITLE
fix(@aws-amplify/core): automatically set clock offset based on CognitoIdentityCredentials systemClockOffset

### LINKED ISSUE #4312: Occasional 504 and 403(service worker) errors when using Api with Signature V4
**Describe the bug**
I am using `API.post('apiPath', path, init)` to sign requests with Signature V4 and send to an Edge optimized API endpoint created using API Gateway(AWS_IAM authorization).

When this error happens, the request ends up with 504 error. And on Chrome Network tab, the same request that has a gear next to it(I assume it is managed by a service worker) has 403 error. 

For the same user, it may happen on one of his devices but works on other devices. So, the user is definitely not disabled on Cognito. 

**To Reproduce**
I don't have specific steps to reproduce it as it happens to some of my users. It works most of the time for most users thus, the code is ok. 

I opened this issue to see if anyone else experiences the same. 

**Expected behavior**
Expected api requests to complete successfully every time

**Devices Affected**
Mostly Chrome 77 on Windows 10
but it happens on Chrome 77 on Mac OS too

### PR DESCRIPTION
**Pull request by Jun711**
_Issue #, if available:_
fix #4312, #2014, #3719 based on #4844

_Description of changes:_
Turn on correctClockSkew option provided by AWS.CognitoIdentityCredentials in Amplify Credentials class
Use DateUtils to setClockOffset using systemClockOffset calculated by AWS.CognitoIdentityCredentials 
in aws-sdk 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by warrenmcquinn** [comment]
Thank you for your work @Jun711 -- I hope this is merged quickly! This is a bug that desperately needs a fix.

**Comment by elgordino** [comment]
Is there a schedule for when this might be merged into a release?

**Comment by GeorgeBellTMH** [comment]
Any ETA?

**Comment by ericclemmons** [comment]
Unfortunately, this PR can't be accepted as-is because of Amplify now using https://github.com/aws/aws-sdk-js-v3 (#3365), which automatically accounts for clock drift: https://github.com/aws/aws-sdk-js-v3/pull/459

I'm reproducing various scenarios (e.g. https://github.com/aws-amplify/amplify-js/issues/2014#issuecomment-583565431) to determine how to resolve this with the latest version of Amplify.

**Comment by ericclemmons** [comment]
Please see my comment in https://github.com/aws-amplify/amplify-js/issues/2014#issuecomment-632275952.  I need to do more validation to resolve the conflicts in this PR updated to match `aws-amplify@latest`'s `Credentials.ts`.

If you have use-cases and steps to reproduce, I can get this updated to finally resolve it.

**Comment by ericclemmons** [comment]
Thanks for your PR! We've since updated our libraries and I've pulled your changes forward into https://github.com/aws-amplify/amplify-js/pull/5869. 

This will be released shortly!

**Pull request closed without merging**
