### PR TITLE
chore: add transformer v2 DataStore integ tests to CCI pipeline

### PR DESCRIPTION
**Pull request by nickarocho**
#### Description of changes

- Adds the [duplicated DataStare sample apps](https://github.com/aws-amplify/amplify-js-samples-staging/pull/281) (scaffolded and provisioned via GQL Transformer & Auth V2 CLI) to our CCI deployment pipeline
- Also adds both the v1 and v2 Observe Query integ tests to the pipeline
- Also adds the SQLiteAdapter integ test to the pipeline to kill two birds

#### Description of how you validated changes
- All tests were [passing](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/9694/workflows/ff4db219-5318-4c5a-8abb-a125bf7619c9) in the source branch prior to creating this PR

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by iartemiev — CHANGES_REQUESTED** [review]
We'll also want to add the new v2 tests under the `requires` param for the deploy job [here](https://github.com/aws-amplify/amplify-js/blob/1d32dc68c0ab49b469f1ac76f810d6afc090ebdc/.circleci/config.yml#L1453)

**Comment by nickarocho** [comment]
> We'll also want to add the new v2 tests under the `requires` param for the deploy job [here](https://github.com/aws-amplify/amplify-js/blob/1d32dc68c0ab49b469f1ac76f810d6afc090ebdc/.circleci/config.yml#L1453)

Good call. Added to the `deploy` job, please re-check. Thanks!

**Review by iartemiev — APPROVED** [review]
LGTM! Thank you so much for adding these, Nick! 🎉

**Review by iartemiev — APPROVED** [review]
LGTM 👍🏻

**Review by svidgen — APPROVED** [review]

**Pull request merged**
