### PR TITLE
fixes(#3620)

### PR DESCRIPTION
**Pull request by haverchuck**
*Issue #, if available:*
fixes(#3620)

*Description of changes:*
This will allow users to use the strict template check option for Angular AOT compilation.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bluezebragames** [comment]
The changes definitely look good.  Just recording my testing experience here before I go...

It took me a while, but I got the changes to be included correctly and it looks like it does in fact fix the issue with `protected` variables not being accessible.  However, I was still unable to get the angular project to compile with AOT for two reasons:

1.  `rxjs`.  `error TS2307: Cannot find module 'rxjs/Subject'`, in `import { Subject } from 'rxjs/Subject';` -- it looks like in `rxjs` version 6, it's just `import { Subject } from 'rxjs';`.  I tried pinning `rxjs` to a lower version, but Angular requires at least `rxjs 5.6.0-forward-compat.0`, which still gives the `Cannot find module 'rxjs/Subject'` errors (plus some more, to boot).

2.  `@ViewChild`.  The error here was `An argument for 'opts' was not provided` -- in Angular 8, `@ViewChild` requires two parameters instead of one, also passing an object like `{static: false}`.  I feel like the previous problem might just be because of a versioning error or something, but this one I'm pretty sure will need to be fixed before Angular 8 AOT support at least.

**Comment by antoinebrault** [comment]
any ETA for the merge ?

**Comment by dsoegijono** [comment]
@haverchuck Any chance of updating this?

**Comment by sammartinez** [comment]
Closing pull request as issue was addressed

**Pull request closed without merging**
