### PR TITLE
fix: Import React/RCTUtils to address build error with RCTMakeError

### PR DESCRIPTION
**Pull request by blainekasten**
I tried including this library with the latest version of Expo and when building the ios app, xcode would crash on RCTMakeError not being imported and by utilizing `patch-package` to add this import it fixed the problem and allowed me to build.

### CODE REVIEW

**Comment by ashika01** [comment]
@calebpollman could someone from RN take a look at this?

**Comment by hkjpotato** [comment]
Hi @blainekasten , Expo team has submitted a separate PR https://github.com/aws-amplify/amplify-js/pull/9387, do you think it can address the issue?

**Comment by tobzy** [comment]
Following. I have the same issue

**Comment by tannerabread** [comment]
This should be resolved with the linked PR #9387 
From two tests within our team we did not see this issue with new builds from expo apps

If you are still experiencing this issue and do not think that the linked PR closed the issue, please comment back and we can investigate further.

Thank you for your contribution to our library!

**Pull request closed without merging**
