### PR TITLE
fixes validationDataObject

### PR DESCRIPTION
**Pull request by ewah**
_Issue #, https://github.com/aws-amplify/amplify-js/issues/7655

_Description of changes:_

validationData now pulls from the correct object (validationDataObject)

### CODE REVIEW

**Comment by lielran** [comment]
Thanks @ewah . we are waiting for this fix :)

**Comment by lielran** [comment]
@elorzafe @ewah
don't want to rush things but this become urgent for us and the fix seems very simple to review.

**Comment by k-yle** [comment]
the definitions for `validationData` have been broken for typescript users for months (see #7100). Also a one-line fix... Now it's totally broken and users can't even sign in.

**Comment by jimmyn** [comment]
I have the same issue and I'm passing recaptcha token in validation data and it just stopped working.

**Comment by lielran** [comment]
@powerful23  @mlabieniec  - can you please review this one-liner PR?

**Comment by jimmyn** [comment]
@lielran do you know the version where it was working because I updated the package and now I can't seem to roll back to the working solution.

**Comment by lielran** [comment]
"aws-amplify": "3.3.14",
"aws-amplify-react": "4.2.18",

this what is working for us.

**Comment by jimmyn** [comment]
@lielran thanks! works for me as well.

**Review by sammartinez — APPROVED** [review]
LGTM 🌮  Thanks for contributing!

**Pull request merged**
