### PR TITLE
feat(aws-amplify-angular/auth): Add federated sign in for social providers

### PR DESCRIPTION
**Pull request by OrozcoJonathan**
*Issue #, if available:*
#2456
#1488
#3537

*Description of changes:*
This change adds a federated sign in component to the aws-amplify-angular library

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sammartinez** [comment]
@OrozcoJonathan Can you look into resolving the conflicts please?

**Comment by iartemiev** [comment]
Hey @OrozcoJonathan, I've resolved the conflicts and got the tests to pass. Will be further testing and reviewing this today.

**Comment by elorzafe** [comment]
@OrozcoJonathan thanks for this PR, we pull this changes forward into new UI components libraries. For more information on how to use federated sign in with social providers you can find it [here](https://github.com/aws-amplify/amplify-js/tree/master/packages/amplify-ui-components#amplify-authenticator-federated)

**Comment by tvb** [comment]
@elorzafe it states federated login by Identity Pools (IDP) does this mean it won’t work with User Pools Federated Logins?

**Pull request closed without merging**
