### PR TITLE
fix(@aws-amplify/datastore): catch auth error during sync

### LINKED ISSUE #6406: [DataStore] Performing save() while user is unauthenticated will cause app to freeze
**Describe the bug**
The mutation will infinitely retry if client performs save() when user is not authenticated.

**To Reproduce**
Two ways to reproduce this:
Method 1: (This method can reproduce the issue consistently)
1. Logout
2. Perform a `DataStore.save()`.
3. App will freeze because of infinite retry in mutation processor.

Method 2: (This is slightly difficult to reproduce but still doable)
1. Perform a `DataStore.save()`.
2. Quickly logout with or without calling `DataStore.clear()`.
3. App will freeze because of infinite retry in mutation processor.

**Expected behavior**
1. `DataStore.save()` should throw error if user is not authenticated.
2. Mutation processor should exit loop when GraphQL returns 'No current user', otherwise it stuck in `while(tryWith)` loop.

**Screenshots**
With debugging mode enabled, you'll notice the console is spammed with 'No current user' error as mutationProcessor infinitely try the mutation.
image

**What is Configured?**
<details>
  <summary><strong>Environment</strong></summary>

```
  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 189.99 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.3.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 84.0.4147.89
    Safari: 13.1.1
  npmPackages:
    uuid: 3.3.2 => 3.3.2 
  npmGlobalPackages:
    @aws-amplify/cli: 4.22.0
    ios-deploy: 1.10.0
    npm: 6.14.4
    react-native-cli: 2.0.1
```

</details>

**Smartphone (please complete the following information):**

- Device: iPad
- OS: iOS 13

### PR DESCRIPTION
**Pull request by wei**
_Issue #, if available:_
Fixes #6406

_Description of changes:_
Mutations jittered retry does not catch auth errors and results in an infinite loop and a dead page. This PR catches the error. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

/cc @iartemiev

### CODE REVIEW

**Comment by nubpro** [comment]
you might want to add a try catch exception when executing errorHandler, I have seen it fail a couple of times. The failure point was at modelInstanceCreator.

**Comment by wei** [comment]
> you might want to add a try catch exception when executing errorHandler, I have seen it fail a couple of times. The failure point was at modelInstanceCreator.

Thanks @nubpro , Updated PR to include try catch similar to how the previous catch is doing it.

**Review by iartemiev — APPROVED** [review]
LGTM! Thank you @wei 

Going to wait for @manueliglesias to take a look as well

**Comment by nubpro** [comment]
I understand that @wei has left the program, what's stopping this PR from being merged? @sammartinez

**Comment by iartemiev** [comment]
> I understand that @wei has left the program, what's stopping this PR from being merged? @sammartinez

I just replied in the linked issue, but we don't think this PR should be needed anymore, as this scenario is covered in the Multi-Auth feature.

**Pull request closed without merging**
