### PR TITLE
chore(geo): refactor create/update to saveGeofences

### PR DESCRIPTION
**Pull request by TreTuna**
#### Description of changes

Due to the way that Location Service handles checking if a geofence exists (404 error if it does not exist, which would be logged to the console), we have decided to not separate these methods and combine them into one without checks if the geofences already exist.
- remove `updateGeofences`
- change `createGeofences` to `saveGeofences`
- use `logger.debug` instead of `logger.warn`
- Util tests were wrapped in a larged `describe` block - No actual test changes in that file

There were not much logic changes here, more of rearranging and renaming code
 
#### Description of how you validated changes
- Unit tests updated
- Testing in demo app through Verdaccio

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Amplifiyer** [comment]
I don't see the refactor change in the diff. Are all the changes updated in this PR?

**Comment by TreTuna** [comment]
> I don't see the refactor change in the diff. Are all the changes updated in this PR?

There was a commit missing... gtg now

**Review by thaddmt — APPROVED** [review]

**Review by Amplifiyer — APPROVED** [review]
LGTM. Are the log level changes intentional?

**Comment by TreTuna** [comment]
> LGTM. Are the log level changes intentional?

Yes, they are intended as there was a lot of console cruft before. This way it's only logged if you intentionally want to see them.

**Pull request merged**
