### PR TITLE
fix(@aws-amplify/core): Include refreshToken in UniversalStorage for SSR

### LINKED ISSUE #7106: Auth.currentSession () don'ts work in SSR, when token expires
**Describe the bug**
I use nextjs with amlify `{ssr: true}`.
I extract token from req in `getServerSideProps` in this way:

```
async function getServerSideProps (context) {
  const { Auth }= withSSRContext(context);
  const session = await Auth.currentSession();
  ...
}
````

**To Reproduce**
It works if user logged in recently. But if user closes the tab and opens it a few hours, this line will throw an error:
`const session = await Auth.currentSession()`

The reason is clear: it happened because user's tokens are not valid anymore. BUT int he documentation https://docs.amplify.aws/lib/auth/overview/q/platform/js#sign-up-and-sign-in I found that:

The Amplify client will refresh the tokens calling Auth.currentSession if they are no longer valid.

Seems that it doesn't work on server side. It just throws an error without possibility to refresh tokens.

### PR DESCRIPTION
**Pull request by ericclemmons**
Fixes #7106 

(See https://github.com/aws-amplify/amplify-js/issues/7106#issuecomment-722525268 for more)

For a page that **requires** a valid `accessToken` to operate (think about `/dashboard` when logged in), `getServerSideProps` would throw the error `No current user` because the `accessToken` has expired. 

This PR adds `refreshToken` to `UniversalStorage` so that the server can refresh the `accessToken` on the server & complete the request. Once the user lands on the client again, the cookie is updated with a new `accessToken` that's then persisted for the server.
 
**Note that the server still doesn't persist the new `accessToken` for the _client_.** The client is still responsible for persisting tokens. Again, this PR allows `getServerSideProps` to get an updated `accessToken` so an error isn't thrown and the client can renegotiate new tokens.  Otherwise, customers will have to setup a catch + redirect flow for the client to update cookies, just to come back to the `/dashboard` like they expected.

See my testing of `/api/profile.tsx`:

```tsx
import { Amplify, withSSRContext } from 'aws-amplify'
import { NextApiRequest, NextApiResponse } from 'next'

import awsconfig from '../../src/aws-exports'

Amplify.configure({ ...awsconfig, ssr: true })

export default async function fetchProfile(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const SSR = withSSRContext({ req })

  try {
    console.log((await SSR.Auth.currentSession()).idToken.jwtToken)
    const user = await SSR.Auth.currentAuthenticatedUser()

    return res.status(200).json({ user })
  } catch (error) {
    console.error(error)
    return res.status(500).json({ error })
  }
}

```

Notice how, when the `accessToken` is initially persisted on the client, the server is able to update it without the client interacting:

```console
❯ yarn dev
yarn run v1.22.10
$ next dev
ready - started server on http://localhost:3000
event - compiled successfully
event - build page: /api/profile
wait  - compiling...
event - compiled successfully

...-lHODRqVDE6indQEEoq2PCVNvwrwYAW4FdlvlRJv2UN0UFxwzc3CCrx12E6wRL-TjdN2wfsk-0GfN_ivi9McZVNubxp8DHUokCyTBUZEwIij6tJBUNek7PlPGeatWVeOcVHX8psivdlIR847O8GZ2gV0SH2ZcnBKjlgPcNVxa5SI09mv9DIgC9VuG7XMpipzeBCnBS9w7fFmsb_-M5tlr7EqWsvrX9fSMZ0rA

9:14 AM
event - build page: /
wait  - compiling...
event - compiled successfully
event - build page: /api/todos
wait  - compiling...
event - compiled successfully

// The next day:
...-Obg09y9NmOg7GLpCoZz518mk2kG7BzULzjR0jX1DiIZgMSv03pAKLeqqNtWm133LRn3oOWWFl2Wy2U8Ghl8kWwD7u6eUA-zS0py_4BWpky14k9YaeNR73wVXq8ou_MDdfMXhzTC3F57vEbwGAhneJtzA8zpFYv4SGU1C8i4H-RyGSbNeKXhSc2xh5NT1cN-YZJQ

^^ After client refreshed
```

---

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by usualdesigner** [comment]
@ericclemmons this change allows us to get a new token on the server. Is there a chance to update the token on the frontend based on the new token from the server?

**Comment by ericclemmons** [comment]
**Note: this PR requires approval from security before merging**.

**Comment by ericclemmons** [comment]
@usualdesigner That's coming!  Once we add support for `httpOnly` cookies, all token management will happen on the server via `withSSRContext({ req, res })`.

For now, this PR at least prevents `500` errors in `getServerSideProps` when the token expires (and customers aren't using `try/catch` ;)).

**Comment by usualdesigner** [comment]
@ericclemmons thank you for your efforts

**Comment by rluncasu** [comment]
Any news on this ? Hit the roadblock and I don't like to do redirect to client, refresh then back

**Review by rluncasu — APPROVED** [review]

**Review by rluncasu — APPROVED** [review]

**Comment by rluncasu** [comment]
any news on this ?

**Review by asp3 — APPROVED** [review]

**Review by sammartinez — APPROVED** [review]
LGTM 🌮

**Comment by S-Cardenas** [comment]
Any change you guys can approve this merge? It's really important to alot of people :)

**Comment by oemer-sellwerk** [comment]
When can we expect this to be merged? What is blocking it?

**Comment by liamlevesqueP8** [comment]
Woooooo!!! Thank you! So is this ready to use now?

**Comment by sammartinez** [comment]
> Woooooo!!! Thank you! So is this ready to use now?

We do have this within our `unstable` tag if you would like to test, we plan to do a release of this sometime next week

**Comment by Bigdragon13th** [comment]
@sammartinez Is this feature release yet?

**Comment by sammartinez** [comment]
> @sammartinez Is this feature release yet?

It is! We released this last week to our library. Please let us know if you are experiencing any issues. Thanks!

**Comment by gustavokobayashi** [comment]
I've been experiencing some authentication bugs.

First of all, thank you very much for this long-waited feature. It was really necessary.

Now, as for the issue, the refresh tokens are available at client side but what I'm experiecing is that if I refresh the page once the access token has expired, the Auth fails (throws the following error):

`{
  code: 'NotAuthorizedException',
  name: 'NotAuthorizedException',
  message: 'Invalid Refresh Token.'
}`

If I simply refresh again the page, the user is again authenticated. Here is my server side code (for Next.JS):

`export const getServerSideProps: GetServerSideProps = async (context) => {
  const { Auth } = withSSRContext(context)
  
  try {
    await Auth.currentSession()
    return { props: { logged: true }}
  } catch (err) {
    return { props: { logged: false }}
  }

}`

If I log in and the token expires, when I refresh the page I get `logger: false`. If I just refresh the page again, I get `logged: true` back.

Thanks in advance.

**Pull request merged**
