### PR TITLE
refactor: enforce "strict" type checking on aws-amplify-react-native

### PR DESCRIPTION
**Pull request by crutchcorn**
#### Description of changes

This PR changes `aws-amplify-react-native` to use TypeScript's `strict` mode for type checking. This PR changes no runtime behavior but fixes various type-checking issues.

#### Issue #, if available

I did not raise an issue since this is an internal-only change and should not impact external users.

#### Description of how you validated changes

I ran `tsc --noEmit` and verified the build works in my app as expected.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by abdallahshaban557** [comment]
Hi @crutchcorn - we are planning deprecating the aws-amplify-react-native library later on this month, and therefore we are closing out this PR. Thank you for the contribution, we are planning on looking at all issues in our repo and assigning good first issues for future contributors. Would you be interested in contributing in the future to our library?

**Comment by crutchcorn** [comment]
I certainly am! My work will be using the future Amplify UI code, and it'll be my duty to implement it.

In particular, I'm very interested in seeing TypeScript typings and a more customizable UI - if there are efforts I can make towards either of these I think it would be mutually benificial.

**Comment by abdallahshaban557** [comment]
Ooo - if UI is your jam - I am adding @calebpollman since he is building a new Authenticator component for React Native. He can share a bit more on his plans!

Also - on the Amplify Javascript library in general, we are working on improving our Typescript support to make our library easier to use!

**Comment by crutchcorn** [comment]
Hi gang - just wanted to double-check on this.

Is there anything I can be doing to help the migration of the new Authenticator component to RN? I'm happy to pick up any work that's needed to get us there; even if that means doing a setup call or whatnot.

**Pull request closed without merging**
