### PR TITLE
Angular Authenticator uneffective Hide feature

### PR DESCRIPTION
**Pull request by ksavidetove**
*Issue #, if available:*
#1191

*Description of changes:*
Conditional display the links of the Angular Authenticator

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by haverchuck** [comment]
@ksavidetove - When you were seeing this behavior were you using the "authenticator" component (which acts as a parent for the other auth components), or were you using the "sign-in" component in isolation? 
(comment originally posted to issue)

**Comment by ksavidetove** [comment]
I was using the authenticator element. So from this parent element, the default view is the Sign In, but with a link to Sign Up displayed even if I hid it. And when you use this link, the authenticator remembers that you wanted to hide this part and presents you nothing. And you are stuck there.

**Comment by AdamShechter9** [comment]
This is still an issue with latest version of amplify.
any chance to merge and fix the issue?

**Comment by elorzafe** [comment]
@ksavidetove we are going thru a refactor, we are going to close the PR for now. We will update the PR and issue to milestone that this is going to be addressed.

Thanks!

**Comment by haverchuck** [comment]
@ksavidetove - Not sure if you are still monitoring this (obviously it's been awhile), but we have decided to merge this.  There were many conflicts resulting from the time lag in merging this, so I pulled this down and pushed it to another branch.  I did not want to update your branch in case you were using it for personally.  I did not rebase, so your commits will be [in the PR](https://github.com/aws-amplify/amplify-js/pull/3173).  I don't think I can add you as a reviewer, but I think you can comment on the PR if you want. We will leave it open for a bit.

**Pull request closed without merging**
