### PR TITLE
fix(@aws-amplify/analytics): attempt to delete unused endpoints

### PR DESCRIPTION
**Pull request by njdullea**
_Issue #, if available: 
- [7251](https://github.com/aws-amplify/amplify-js/issues/7251#issuecomment-777602959)
- [1378](https://github.com/aws-amplify/amplify-js/issues/1378)
- [5423](https://github.com/aws-amplify/amplify-js/issues/5423)

_Description of changes:
The amplify 3.3.8 would removed unused endpoints. Then this [merge](https://github.com/aws-amplify/amplify-js/pull/7245) deleted the code that removes the endpoints and I can't find a reason why so these changes re-include the modifications from the previous merge.

Also, I did my best to follow the [contribution guide](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md) but let me know if there needs to be any changes.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by GeorgeBellTMH** [comment]
I think we need to revert this in cli as well...https://github.com/aws-amplify/amplify-cli/pull/5918

**Comment by mariotsi** [comment]
Can this PR be worked on please? A bug has been reintroduced an none knows why.

**Comment by GeorgeBellTMH** [comment]
This has been sitting around for sooo long...and nobody is fixing it...

**Comment by kylekirkby** [comment]
@sammartinez any idea when this can be merged?

**Comment by abdallahshaban557** [comment]
Hi @njdullea - thank you for this contribution. We have been discussing the issue with unused endpoints in the Analytics and Notification categories, and we have a path forward with the changes that are coming on the Pinpoint side. In the future, the Analytics category would no longer have a need for Endpoints, which would severely limit situations where a user accumulates over 20 endpoints which end up creating the "Maximum endpoints reached" issue. We are also discussing if we would want to still provide a utility to allow developers to clean unused Endpoints if a customer has added multiple devices with Push Notifications for example, but that will come at a later time. 

We will post updates on these issues when we have our solution ready for preview!

**Pull request closed without merging**
