### PR TITLE
fix(@aws-amplify/ui-components): amplify-container component, use dispatch auth event on check user

### PR DESCRIPTION
**Pull request by jordanranz**
_Description of changes:_
- Dispatch auth events inside of `checkUser` so `withAuthenticator` and customers can listen to signed in and sign out events.
- Wrap authenticator and center it for `withAuthenticator` to reduce friction for out of the box functionality:
Screen Shot 2020-05-08 at 11 07 01 AM

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jordanranz** [comment]
I am currently re-working the styling on the container a bit.

**Comment by jasper72** [comment]
This only works for withAuthenticator. Please could it be applied to <AmplifyAuthenticator> or some guidance provided as to how we position the sign in/up without impacting the position of the app itself.

**Comment by ericclemmons** [comment]
You're right @jasper72.  I opened up https://github.com/aws-amplify/amplify-js/issues/5775 to address this.

**Comment by jasper72** [comment]
Thank you

**Pull request merged**
