### PR TITLE
feat: Patch JKBigInteger to use NSSecureCoding

### PR DESCRIPTION
**Pull request by palpatim**
_Issue #, if available:_

_Description of changes:_

Patches our fork of JKBigInteger to support NSSecureCoding.

Related to https://github.com/aws-amplify/aws-sdk-ios/issues/2914

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by elorzafe — APPROVED** [review]
Thanks @palpatim 🥇 ! As soon we complete testing this is going to be merged.

**Review by Ashish-Nanda — APPROVED** [review]
LGTM 🚀

**Comment by manueliglesias** [comment]
Thanks @palpatim !!

This PR will help customers using non-expo React Native. 🎉 

Would it be possible to have a similar PR sent to expo?
(https://github.com/expo/expo/tree/41458d1de91544c41097818db21e44e9aa84688c/ios/Exponent/Versioned/Core/Api/Cognito)

I don't know if it is needed there, I just remember they include some of our code. Regarding the mechanics/process for sending the PR, I am not familiar, but @undefobj will surely be

**Comment by undefobj** [comment]
> Thanks @palpatim !!
> 
> This PR will help customers using non-expo React Native. 🎉
> 
> Would it be possible to have a similar PR sent to expo?
> (https://github.com/expo/expo/tree/41458d1de91544c41097818db21e44e9aa84688c/ios/Exponent/Versioned/Core/Api/Cognito)
> 
> I don't know if it is needed there, I just remember they include some of our code. Regarding the mechanics/process for sending the PR, I am not familiar, but @undefobj will surely be

Yup we are talking with Expo now.

**Review by manueliglesias — COMMENTED** [review]
@palpatim 

This might be just me not understanding ios development at all, but 

- we have this folder: https://github.com/aws-amplify/amplify-js/tree/main/packages/amazon-cognito-identity-js/ios/JKBigInteger, right? Which is some kind of "fork" of JKBInteger

- it is my understanding that here is where we bring it for usage, or “import it”
https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/ios/RNAWSCognito.h#L19

- If I am right so far, what’s the point of this in the podscpec then??
https://github.com/aws-amplify/amplify-js/blob/main/packages/amazon-cognito-identity-js/RNAWSCognito.podspec#L23

**Comment by iartemiev** [comment]
@manueliglesias - you were right, the local fork was getting ignored and only the pod was being used. I pushed a change to the podspec

**Review by iartemiev — APPROVED** [review]
Tested with RN CLI and Expo - the local JKBigInteger fork is now getting imported. Auth / Cognito is working as expected

**Review by amhinson — APPROVED** [review]

**Review by manueliglesias — APPROVED** [review]

**Review by Ashish-Nanda — APPROVED** [review]
LGTM. Thanks for testing the change.

**Pull request merged**
