### PR TITLE
release: Amplify JS release 2024-02-06

### PR DESCRIPTION
**Pull request by elorzafe**
#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by kvramyasri7 — DISMISSED** [review]
Would be nice to see the release template filled completely as it is not a single PR but a release PR

**Review by jimblanc — APPROVED** [review]

**Review by ashwinkumar6 — APPROVED** [review]

**Review by Samaritan1011001 — APPROVED** [review]

**Review by HuiSF — APPROVED** [review]

**Review by stocaaro — APPROVED** [review]

**Review by kvramyasri7 — CHANGES_REQUESTED** [review]
Seems like not updated yet

**Comment by kvramyasri7** [comment]
seems like some issue with a release we might need doctors here. Haha kidding.

**Comment by kvramyasri7** [comment]
oops seems like just engineers are enough to do this release. Kidding again.

**Comment by kvramyasri7** [comment]
This is not a joke as per the ask by the Manager.

**Pull request merged**
