### PR TITLE
Add Authenticator option to start on a different screen

### PR DESCRIPTION
**Pull request by rlmartin**
*Issue #, if available:*

*Description of changes:*
This is useful for things such as: a set of onboarding screens before
signup; landing on SignUp first instead of SignIn.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by rlmartin** [comment]
@mlabieniec @richardzcode @powerful23 any feedback?

**Comment by rlmartin** [comment]
@mlabieniec still waiting on any kind of feedback here.

**Comment by richardzcode** [comment]
Hey @rlmartin sorry for the late reply. It is just we need to always be conservative when adding new parameters. So a bit careful here.

I believe this is a valid case. The change look good. Only I am hesitated on adding a new name. Here are my thoughts,

From `<Authenticator />` point of view, what we need is the initial authState, and make sure `signOut` goes back to this initial authState. Then can we just use the name `authState`? So `props.authState` is the init value and `state.authState` is what changing.

In our case, we could just set `<Authenticator authState="signUp" />`.

Then same goes to parameter naming of `withAuthenticator`, just use `authState`.

What do you think?

**Comment by elorzafe** [comment]
@rlmartin We made a lot of changes on our repo. For example `dist` was removed. The PR looks good but we need to update this in order to merge. Also we need to support this behavior on the other frameworks to keep consistency. Is this something you are interested in?

**Comment by mlabieniec** [comment]
@rlmartin we are working on a update to the ui components in general, we will tag this as part of that refactor features. Let us know if you have more feedback on the use case here that you'd like us to include.

**Comment by rlmartin** [comment]
@mlabieniec the main point is that it would be good to make configurable the component that you start on when not logged in.

**Pull request closed without merging**
