### PR TITLE
fix(@aws-amplify/pubsub): Handle onclose events in AwsRealTimeSocket

### PR DESCRIPTION
**Pull request by greimela**
_Issue #, if available:_
#5403 

_Description of changes:_
This change allows a user of the socket to restart the subscription after it terminates without an error.
This can sometimes happen when devices enter or leave standby.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by bensie** [comment]
We're seeing the same behavior as described in #5403 and would love to see this merged!

**Comment by ericclemmons** [comment]
@greimela @bensie I was able to validate this (including @adamup928's example from #5403).

Since a socket reconnect doesn't happen automatically, how are/would you handling reconnecting?

**Comment by greimela** [comment]
@ericclemmons Nice, thanks for the confirmation!

We are using the error callback to restart our subscriptions. So if the close events arrive there it's perfect for us 👌

**Comment by bensie** [comment]
@greimela Would you mind sharing how you trigger the websocket reconnect from within the subscribe `error` function? It doesn't seem like triggering resubscribes causes the websocket connection to reconnect if it's no longer active. Thanks!

**Comment by greimela** [comment]
@bensie We are actually opening a completely new subscription in the case of an error.

**Comment by bensie** [comment]
@greimela Guessing I'm missing a step here and I think we might be mixing up terminology - with 1 websocket connection and many subscriptions on that connection, if the websocket connection is closed and the `onclose` event is fired, how do you reconnect the websocket ahead of re-initiating those subscriptions? Do you have a code snippet you could share?

**Comment by greimela** [comment]
@bensie We are using this lib only through the GraphQL subscriptions, so we might speak of different `subscriptions` here.

We just call `API.graphql(...).subscribe(...)` again after we get the error.

**Comment by bensie** [comment]
@greimela Interesting, thanks! I'll keep digging, when we do that the websocket connection doesn't seem to reconnect automatically and the resubscribe fails.

**Pull request merged**
