### PR TITLE
fix(storage): Optimized storage category `sideEffects` to improve shake-ability

### PR DESCRIPTION
**Pull request by jimblanc**
#### Description of changes
Refactored the storage module's `sideEffects` to improve shake-ability by moving singleton registration out of `index.ts`. Verified change with a simple Auth-only React app and a variety of bundlers.

##### Bundler results
The table below outlines observed bundle size improvements from this change. Apps that don't use storage directly should also see improvements from no longer having to bundle `@aws-sdk/client-s3`.
| Bundler  | Parsed `packages` Δ | Parsed `node_modules` Δ | GZipped `packages` Δ | GZipped `node_modules` Δ |
| --- | --- | --- | --- | --- |
| Webpack | -41 kB | -107 kB | -6.58 kB | -48 kB |
| Rollup | -44 kB | -390 kB | NA | NA |
| Parcel | -31 kB | -98 kB | NA | NA |
  
#### Issue #, if available
Tangentially related to [Increase in package size with aws-amplify@4.3.36](https://t.corp.amazon.com/P72001406/overview)

#### Description of how you validated changes
- Manually confirmed bundle optimization with a simple Auth sample app
- [`build_test_deploy`](https://app.circleci.com/pipelines/github/aws-amplify/amplify-js/14763/workflows/5ebc88a2-e898-4d42-a177-774b7dd0fbcc) CircleCI test pass
  - The 4 failing datastore observe tests are unrelated & currently being investigated by the datastore team

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are unchanged
- [ ]  Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by reesscot — APPROVED** [review]
LGTM, thanks for testing this it the various bundlers!

**Review by chintannp — DISMISSED** [review]
LGTM 🚀

**Review by reesscot — DISMISSED** [review]
LGTM, tested in CRA and I see the bundle size drop

**Review by chintannp — DISMISSED** [review]
LGTM 🛳

**Review by chintannp — APPROVED** [review]

**Review by israx — APPROVED** [review]
LGTM

**Pull request merged**
