### PR TITLE
fix: added type declaration to associate secret code for MFA

### PR DESCRIPTION
**Pull request by lousybear**
required for authenticating with MFA option enabled

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ashika01** [comment]
@lousybear Help me understand this better. Why do we need the `associateSecretCode` added? I see the only place that is used is inside `associateSoftwareToken` and to use TOTP MFA wouldn't one be using that?

**Comment by lousybear** [comment]
@ashika01 Yes, as you mentioned it is required for TOTP based MFA workflow, since it is not currently defined as a valid callback function type we might need to get this added to get the workflow running.

**Comment by elorzafe** [comment]
@lousybear the README can be misleading because is passing `this` on the callback for `associateSoftwareToken` but that callback is not needed on the original call. At the end is required to do `cognitoUser.associateSoftwareToken(callbacks)`.

If that is part of the type unless you do that "binding" it wont have any effect.

Let me know what you think.

**Comment by abdallahshaban557** [comment]
@lousybear - was the description from @elorzafe sufficient for you? Should we close this PR?

**Pull request closed without merging**
