### PR TITLE
feature(amazon-cognito-identity-js) allow custom auth

### PR DESCRIPTION
**Pull request by jason-h-michael**
*Issue #, if available:*
#525 

*Description of changes:*
Allow custom auth flow type as an extension of normal signin with username/password.

A user should be able to start a signin by entering username and password, and when that passes, be prompted for additional challenges (like custom MFA).  Cognito supports that workflow.  Amplify doesn't.  This solves that.  I have tested this change by making it locally, and everything works following that -> the user is launched into the custom auth flow in Cognito, invoking the correct triggers within.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jason-h-michael** [comment]
@abemusic - check this out

**Comment by powerful23** [comment]
@jason-h-michael Hi, did you check this doc: https://aws-amplify.github.io/docs/js/authentication#customizing-authentication-flow?

**Comment by jason-h-michael** [comment]
Yes, but these two sections are at odds:

*******
"Customizing Authentication Flow
Amazon Cognito User Pools support customizing the authentication flow to enable new challenge types, **in addition to a password**, to verify the identity of users. These challenge types may include CAPTCHAs or dynamic challenge questions.

To define your challenges for custom authentication flow, you need to implement Lambda triggers for Amazon Cognito."
******* a little farther down in the same documentation *******
"Using a Custom Challenge
To initiate a custom authorization flow in your app, call signIn **without a password.**"

We want to use the former: 
user enters username/password, clicks Login button
user is prompted for custom challenge, enters that, and clicks Submit button

We have the three triggers set up in Cognito to do the custom steps, but need to Amplify.configure with authFlowType: CUSTOM (only in certain cases, not always) and call signin with both username and password.

**Comment by powerful23** [comment]
@jason-h-michael Gotcha. Btw, did you test it in your local?

**Comment by jason-h-michael** [comment]
Does this seem like something we could get merged in soon?  If not, I will have to go through pain of forking/building, which isn't easy with this particular mono-repo.

**Pull request merged**
