### PR TITLE
fix(@aws-amplify-react): Fixes conditional rendering of SignIn Auth component

### PR DESCRIPTION
**Pull request by alvaromb**
Added support for conditional rendering of both SignUp and ForgotPassword in SignIn component.

*Issue #, if available:*
#1467

*Description of changes:*
On `master` branch, one cannot hide either `SignUp` or `ForgotPassword` components from `SignIn`, even if the `hide` prop is supported. This PR fixes that.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mlabieniec** [comment]
fixed in #1478

**Comment by alvaromb** [comment]
@mlabieniec seems that this feature has been reverted in the recent release: https://github.com/aws-amplify/amplify-js/commit/41d3184239b4087d750c86ae7401843afe6f6555#diff-10c5e460f7548affa2288aee3ad9fe7fR112

Can I help you with something to make it possible to enable this feature?

**Comment by alvaromb** [comment]
Hi @mlabieniec. #1478 got reverted. We need to be able to use the existing props to hide the user sign up process.

Can you take a look at this issue? How can we help to bring this feature to the source code again? I'm happy to help.

**Comment by powerful23** [comment]
@alvaromb Hi we have noticed this issue and has merged a pr to fix that: #1632

**Pull request closed without merging**
