### PR TITLE
Update firebase-core and firebase-messaging

### PR DESCRIPTION
**Pull request by dusan-dragon**
*Issue #, if available:*
No issue was created

*Description of changes:*

Updating firebase core and firebase messaging for pushnotifications as it is using quite old version of it and it is kind of conflicting with others projects which also use firebase but with up to date versions of it....

### CODE REVIEW

**Comment by jordanranz** [comment]
Related to https://github.com/aws-amplify/amplify-js/issues/2541#issuecomment-479875853

**Comment by dusan-dragon** [comment]
Also note that with new version of gradle google is enforcing strict version checks, so most of the apps using amplify are going to have broken builds.... the not pleasant workaround for this is just disabling all version checks :(

**Comment by powerful23** [comment]
@dusan-dragon about the strict version, is it related to: https://github.com/OneSignal/OneSignal-Gradle-Plugin/issues/37 ?
And isn't this a breaking change because if firebase is upgraded in @aws-amplify/pushnotification, then you also need to upgrade your firebase version in your app accordingly, https://aws-amplify.github.io/docs/js/push-notifications#setup-for-android -> step 7

**Comment by dusan-dragon** [comment]
@powerful23 kind of it is related in the way that if you use gradle plugin 'com.google.gms.google-services' the new version is automatically checking strict version...
We do not use OneSignal at all... Also yes, you need to upgrade the firebase deps but if the app use it already (for example ours) then we want to stick to new up-to date version and not to historic 12.0 version

**Comment by AndruByrne** [comment]
Looking forward to this PR getting reviewed...

**Comment by elorzafe** [comment]
@dusan-dragon the team is addressing this problem in the Push Notifications milestone. We will keep you posted on the repo with the updates.

**Pull request closed without merging**
