### PR TITLE
feat(@aws-amplify/auth): add SignInWithApple to supported providers

### PR DESCRIPTION
**Pull request by andreialecu**
_Issue #, if available:_
https://github.com/aws-amplify/amplify-js/issues/3395

_Description of changes:_

Updates enums to include the new `SignInWithApple` identity provider. 

See: https://github.com/aws-amplify/amplify-js/issues/3395#issuecomment-566672493

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by amhinson** [comment]
Hey @andreialecu Thanks for the PR!

It looks like we are creating that `CognitoHostedUIIdentityProvider` enum in 2 different places for some reason. Ideally, this should only be created in `types/Auth.ts`. Could you also remove the other enum in this PR as well?

**Comment by andreialecu** [comment]
@amhinson done.

**Comment by cristiandan** [comment]
hi, any update on this ?

**Comment by andreialecu** [comment]
@amhinson fixed, sorry for the delay.

**Pull request merged**
