### PR TITLE
Fix #4342: move @types/zen-observable to devDependencies

### LINKED ISSUE #4342: Duplicate identifier 'Subscriber'
Am getting duplicate identifier subscriber issue from past 2 weeks.

error

Package.json.

```
{
  "name": "test",
  "version": "0.1.9",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "BUILD_ENV=${BUILD_ENV} ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve",
    "compodoc": "./node_modules/.bin/compodoc -p src/tsconfig.app.json -w -s",
    "test": "karma start ./test-config/karma.conf.js",
    "test-ci": "karma start ./test-config/karma.conf.js --single-run",
    "test-coverage": "karma start ./test-config/karma.conf.js --coverage",
    "e2e": "npm run e2e-update && npm run e2e-test",
    "e2e-test": "protractor ./test-config/protractor.conf.js",
    "e2e-update": "webdriver-manager update --standalone false --gecko false"
  },
  "config": {
    "ionic_generate_source_map": "true"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/cdk": "^5.2.5",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/material": "^7.3.5",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/app-center-analytics": "^4.18.0",
    "@ionic-native/app-center-crashes": "^4.18.0",
    "@ionic-native/app-version": "^4.17.0",
    "@ionic-native/barcode-scanner": "^4.20.0",
    "@ionic-native/camera": "^4.17.0",
    "@ionic-native/code-push": "^4.20.0",
    "@ionic-native/core": "~4.15.0",
    "@ionic-native/device": "4.7.0",
    "@ionic-native/dialogs": "^4.17.0",
    "@ionic-native/file": "^4.20.0",
    "@ionic-native/image-picker": "^4.17.0",
    "@ionic-native/social-sharing": "^4.17.0",
    "@ionic-native/speech-recognition": "^4.17.0",
    "@ionic-native/splash-screen": "~4.15.0",
    "@ionic-native/status-bar": "~4.15.0",
    "@ionic/pro": "2.0.3",
    "@ionic/storage": "2.2.0",
    "apollo-client": "^2.6.2",
    "aws-amplify": "^1.2.4",
    "aws-amplify-angular": "^3.0.3",
    "aws-appsync": "^1.8.0",
    "cordova-android": "7.1.4",
    "cordova-android-play-services-gradle-release": "^2.0.0",
    "cordova-android-support-gradle-release": "^2.0.1",
    "cordova-browser": "5.0.4",
    "cordova-ios": "4.5.4",
    "cordova-plugin-app-version": "^0.1.9",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-compat": "^1.2.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-dialogs": "^2.0.1",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-ionic": "^5.3.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.2.5",
    "cordova-plugin-speechrecognition": "^1.2.0",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-telerik-imagepicker": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-plugin-x-socialsharing": "^5.4.3",
    "cordova-plugin-zip": "^3.1.0",
    "es6-promise-plugin": "^4.2.2",
    "font-awesome": "^4.7.0",
    "graphql-tag": "^2.10.1",
    "ionic-angular": "3.9.2",
    "ionic-long-press": "^1.5.0",
    "ionicons": "3.0.0",
    "ng2-translate": "^5.0.0",
    "phonegap-plugin-barcodescanner": "^8.0.1",
    "primeng": "^5.2.7",
    "rxjs": "5.5.11",
    "sentry-cordova": "^0.15.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@compodoc/compodoc": "^1.1.8",
    "@ionic/app-scripts": "3.2.2",
    "@types/jasmine": "^2.8.12",
    "@types/node": "^10.12.10",
    "angular2-template-loader": "^0.6.2",
    "html-loader": "^0.5.5",
    "istanbul-instrumenter-loader": "^3.0.1",
    "jasmine": "^2.99.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^3.1.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.4",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^3.0.5",
    "null-loader": "^0.1.1",
    "protractor": "^5.4.1",
    "ts-loader": "^3.5.0",
    "ts-node": "^7.0.1",
    "typescript": "3.3.3333",
    "webpack": "^3.12.0"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {
        "ANDROID_SUPPORT_ANNOTATIONS_VERSION": "27.+"
      },
      "cordova-plugin-ionic-keyboard": {},
      "cordova-plugin-speechrecognition": {},
      "cordova-plugin-dialogs": {},
      "cordova-plugin-camera": {},
      "cordova-plugin-file": {},
      "cordova-plugin-file-transfer": {},
      "cordova-plugin-zip": {},
      "cordova-plugin-app-version": {},
      "cordova-plugin-telerik-imagepicker": {
        "PHOTO_LIBRARY_USAGE_DESCRIPTION": "Allow to access your gallery"
      },
      "cordova-plugin-x-socialsharing": {
        "ANDROID_SUPPORT_V4_VERSION": "24.1.1+"
      },
      "cordova-plugin-appcenter-analytics": {},
      "cordova-plugin-appcenter-crashes": {},
      "cordova-android-play-services-gradle-release": {
        "PLAY_SERVICES_VERSION": "15.+"
      },
      "cordova-android-support-gradle-release": {
        "ANDROID_SUPPORT_VERSION": "27.+"
      },
      "cordova-plugin-code-push": {},
      "phonegap-plugin-barcodescanner": {
        "ANDROID_SUPPORT_V4_VERSION": "27.+"
      },
      "cordova-plugin-whitelist": {},
      "sentry-cordova": {}
    },
    "platforms": [
      "ios",
      "android"
    ]
  }
}
```
We gone through https://github.com/aws-amplify/amplify-js/issues/3248 issue and updated the comment but i did't get any reply on that.

### PR DESCRIPTION
**Pull request by ericclemmons**
_Issue #, if available:_ #4342

Moves `@types/zen-observable` to `devDependencies` and updates to `^0.8.0`.

This is a regression of #3529 when #4007 was merged.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by satishmolletipipra** [comment]
@ericclemmons We forked the aws-amplify repo and moved @types/zen-observable to devDependencies in api/package.json and pusub/package.json as like you but am facing the duplicate subscribers issue after adding build aws-amplify repo to my local repo.

**Comment by ericclemmons** [comment]
@satishmolletipipra I may need to do additional auditing on this.

Because of the dependencies between `aws-amplify` and the rest, I was also getting similar errors because `@aws-amplify/api` was still being installed from NPM vs. locally.

On your project, what do you get when you run `yarn why @types/zen-observable`?

**Comment by satishmolletipipra** [comment]
@ericclemmons Thanks for the quick response. I am getting following response when i run `yarn why @types/zen-observable`

image

**Comment by ericclemmons** [comment]
This is helpful!  I think you may be seeing the same workflow issues I've been having.  Commit f82eda2857f29b966e58f15c750b137cfbf10054 updated the versions so that they're all `@types/zen-observable@^0.8.0` (to be in sync with the aws-sdk), but yarn is still reporting it as `0.5.4`.

Since this change makes sense on paper, it's probably best to merge it, publish it, and see if that patch addresses it when installed via the registry or not.

(I've made some notes on my end that there's a miss with tooling & workflow to successfully validate these changes.  Ideally, I'd want customers like yourself to be able to do something like `npm i aws-amplify@0.0.0-pr4494-abcd` to truly validate _prior_ merging)

**Comment by satishmolletipipra** [comment]
@ericclemmons Thanks for the update. while running `npm i aws-amplify@0.0.0-pr4494-abcd` I am getting following response.
image

**Comment by ericclemmons** [comment]
@satishmolletipipra Sorry for the confusion!  That package doesn't exist.  This is a workflow _I'd like to enable_, since it's much easier for customers to test than forking the repo & setting up the local dev workflow:

> I've made some notes on my end that there's a miss with tooling & workflow to successfully validate these changes. Ideally, I'd want customers like yourself to be able to do something like `npm i aws-amplify@0.0.0-pr4494-abcd` to truly validate prior merging

**Comment by jmpreston** [comment]
Thank you guys for working on this!  Frustrating problem and the only work around left for me is nuking Cognito in my app.  So I'll wait for a fix in January and do other stuff.  Enjoy the holidays!

**Comment by ericclemmons** [comment]
@jmpreston Try out `2.2.1` and let us know if this resolved it 🤞
https://github.com/aws-amplify/amplify-js/compare/aws-amplify@2.2.1...master

**Comment by jmpreston** [comment]
@ericclemmons.  This worked for me!  Thanks.

**Pull request merged**
