### PR TITLE
GH-4468: Transfer Acceleration option can now be passed to Storage.put()

### PR DESCRIPTION
**Pull request by cespin**
#### Description of changes
Currently, it is not possible to make the Amplify client use the transfer acceleration option of S3.

With this modification the web application would pass an extra parameter to the put and that would attempt to do the upload using transfer acceleration

#### Issue #, if available
#4468 

#### Description of how you validated changes

Ran the unit tests, checked with the documentation of the AWS S3 client that the parameter is valid.

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by veskopetkov — APPROVED** [review]

**Review by tzzoug — APPROVED** [review]

**Comment by cespin** [comment]
Hi,

Any chance I can get some feedback on this PR? The lack of this feature is impacting my production environment.

Thanks,

**Review by jamesaucode — APPROVED** [review]
LGTM :)

**Comment by iartemiev** [comment]
@jamesaucode when merging PRs, please make sure to squash and merge to a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/)-style message. For example: `feat(@aws-amplify/storage): add transfer acceleration option to Storage.put`. This enables our pipelines to correctly version packages and generate changelogs.

**Comment by cespin** [comment]
Hi @iartemiev / @jamesaucode ,

Thanks for merging this. Much appreciated.

I just upgraded the _aws-amplify_ to version 4.2.4 which is supposed to include these changes according to the release notes but I don't see them in there when I navigate into the code.

I've downloaded the library several times, seems that the package doesn't match the release notes.

can you help me check if this is the case ? 

Thanks,

**Comment by cespin** [comment]
I can confirm what I said above. 

I downloaded the the package from the release page, [here](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%404.2.4)

The source code I downloaded doesn't include these changes but the release notes say it does.

**Comment by iartemiev** [comment]
@cespin, this change has not yet been released. It will be in the next release of aws-amplify. Where are you seeing that this is included in 4.2.4?

**Comment by iartemiev** [comment]
The change is currently available through our pre-release NPM tag If you want to use it before it goes out in the next release. You can `npm install aws-amplify@4.2.5-unstable.1`

**Comment by cespin** [comment]
Thanks for the information @iartemiev 

I saw it [in this URL](https://github.com/aws-amplify/amplify-js/releases/tag/aws-amplify%404.2.4) after clicking on [2 commits](https://github.com/aws-amplify/amplify-js/compare/aws-amplify@4.2.4...main)

**Comment by iartemiev** [comment]
Those are not the commits that are included in the release. That's showing commits that have been merged to the main branch after the release went out.
Screen Shot 2021-08-20 at 12 47 16 PM

**Comment by cespin** [comment]
Thanks for the clarification @iartemiev

**Pull request merged**
