### PR TITLE
Pass deeplink URL from pinpoint to killed react-native app

### PR DESCRIPTION
**Pull request by isnifer**
#### Description of changes
This PR brings deeplink information to Intent that opens application from notification.
Existing intent configuration just doing plain application opening, my PR pass information about deeplink to it.
After this change `Linking.getInitialURL()` started to get this `initialURL` and user is available to use this information on JS side.

#### Issue #, if available

This PR closes (already closed, but not resolved) issue #1849

#### Description of how you validated changes
1. Configure notifications for your app via `pinpoint` + `amplify`
2. write `const initialURL = await Linking.getInitialURL()` somewhere in your app where you're handling deep linking and log it to `console` for example
4. "Kill" the app
5. Send notification to the app
6. Tap on your notification
7. Watch to your terminal where `console.log` will prove the change

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by isnifer** [comment]
After my success I have found that `aws-sdk-android` repo has almost the same code — https://github.com/aws-amplify/aws-sdk-android/blob/e5b43ab848bc304c452324772af4310c3b0cb972/aws-android-sdk-pinpoint/src/main/java/com/amazonaws/mobileconnectors/pinpoint/targeting/notification/NotificationClientBase.java#L812-L813

**Comment by cshfang** [comment]
Hi @isnifer we recently had to make changes to the push notifications packages to address some issues with Android 12. As a result, your PR will need to be updated as the changes reside in a broadcast receiver that notifications now basically ignore due to [Notification trampoline restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#notification-trampolines). Do you think you can adapt your changes so that they can go into the RNPushNotificationHelper instead?

**Comment by isnifer** [comment]
@cshfang I'll rebase my branch. Hope, it won't take 8 months

**Comment by cwomack** [comment]
@isnifer, wanted to ping you to see if you're still interested in working on this PR.  Doesn't look like the rebase has happened yet, but let us know if you're still working on this. Thanks!

**Comment by isnifer** [comment]
@cwomack Hey, no I don't work on this.

**Comment by cwomack** [comment]
@isnifer, thanks for the reply and confirmation.  We'll close out the PR then.

**Pull request closed without merging**
