### PR TITLE
add getStoragePrefix method to CognitoUser and CognitoUserPool

### PR DESCRIPTION
**Pull request by belgac**
*Issue #, if available:*

*Description of changes:*
allows to use a unified way to get the amazon cognito storage prefix and allows to get it from outside of the cognito library

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by belgac** [comment]
are the tests fixed by now?

**Comment by powerful23** [comment]
@belgac Hi this pr looks good to me. Can you resolve the conflicts so we can merge this? Thanks.

**Comment by powerful23** [comment]
@belgac since there is no further response and we think there isn't enough reason to introduce this feature, we are going to close it. Thanks for contributing!

**Comment by belgac** [comment]
I understand, the actual purpose of this PR isn't clear and is more of a workaround to be able to have sync altenatives to async methods in the implementation of the library. I will redesign a better way to do this when I go back on working on the frontend of my app

**Pull request closed without merging**
