### PR TITLE
fix(amazon-cognito-identity-js): Missing cognito user challenge name …

### PR DESCRIPTION
**Pull request by micksatana**
#### Description of changes
- Add `ChallengeName` type and `challengeName` property in `CognitoUser`

#### Issue #, if available
- https://github.com/aws-amplify/amplify-js/issues/3316
- https://github.com/aws-amplify/amplify-js/issues/3733
- https://github.com/aws-amplify/amplify-js/issues/6974

#### Description of how you validated changes
- `yarn link` and test on `auth` package
Screen Shot 2565-07-01 at 01 08 18

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by decebal — APPROVED** [review]

**Comment by micksatana** [comment]
This will fix #3316 as well.

**Comment by elorzafe** [comment]
@micksatana 

Thanks for your contribution, I updated your PR by fixing an Auth unit test that was using a wrong value for `ChallengeName`.

**Review by elorzafe — APPROVED** [review]
Looks good, thanks @micksatana 🎉 🏅

**Review by nickarocho — APPROVED** [review]
LGTM, thanks for your contribution, @micksatana! 👍

**Comment by abdallahshaban557** [comment]
Once we deploy our next version of the JS library, we need to close out the 3 GH issues mentioned in the PR.

**Pull request merged**
