### PR TITLE
Ui components/feature description field to forms

### PR DESCRIPTION
**Pull request by emmi**
_Issue #, if available:_
No issues

_Description of changes:_
Found myself hoping to have a way to add extra descriptions/information on the sign-up form (for instance to make it more accessible) and ended up adding it to sign-in, sign-up and forgot-password forms, although it's quite easy to add into the others as well. 

Few example photos
Screenshot 2020-05-19 at 18 34 10
Screenshot 2020-05-19 at 18 34 48

**I also included a small CSS fix** where the margin between the form footer's secondary and primary contents was not working properly. Below you can see the before and after photos of the changes.

Before
Screenshot 2020-05-19 at 18 59 07

After
Screenshot 2020-05-19 at 18 35 21

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by ashika01** [comment]
@emmi - the css fix came into play for tab/mobile support. Could you maybe post a screenshot if that?

**Comment by emmi** [comment]
> @emmi - the css fix came into play for tab/mobile support. Could you maybe post a screenshot if that?

Here you go, seems to work fine. :) 

IMG_3557

**Comment by ashika01** [comment]
Thanks we will get on this.

**Comment by jordanranz** [comment]
Hey @emmi! Sorry for the delay in response on this PR.

We ended up going with a `slot` approach for these changes. The changes should be included in the latest release of the UI libraries. Could you try:
```
<AmplifySignIn slot="sign-in">
    <div slot="header-subtitle">Header subtitle content</div>
</AmplifySignIn>
```

**Pull request closed without merging**
