### PR TITLE
fix(@aws-amplify/core): use empty string as translation

### PR DESCRIPTION
**Pull request by yana-katty**
#### Description of changes

This PR fixes the I18n `get` function return an empty string, if provided vocabulary contains an empty string entry.
Only fallback to the default value if the vocabulary doesn't contain such a key at all.

#### Issue #, if available

https://github.com/aws-amplify/amplify-js/issues/8754

#### Description of how you validated changes
 * Local unit testing
 * Verified that get function return an empty string in my local app

test code
```
    I18n.setLanguage('fr');
    const dict = {
        'fr': {
            'empty string': "",
            'Sign Up': "S'inscrire"
        }
    };
    I18n.putVocabularies(dict);
    console.log(I18n.get('empty string'));// returnig empty string
    console.log(I18n.get('Sign Up'));// returnig provided vocabulary ( "S'inscrire" )
    console.log(I18n.get('Sign in'));//returnig key value('Sign in')
    console.log(I18n.get('Sign in','Se connecter'));//returnig default value ('Se connecter')
```

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [ ] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by evcodes — APPROVED** [review]
Hey @yana-katty thank you so much for this PR. I just pulled down the changes locally and this is a great fix. I see how this would be an issue and I appreciate your commit. Green light from me 🚀

**Review by evcodes — CHANGES_REQUESTED** [review]
!= with null, will also work if val is undefined since it's not strictly unequal. I am working on a fix.

**Review by evcodes — APPROVED** [review]
This works now

**Review by nickarocho — APPROVED** [review]
LGTM! Thank you for your contribution! 🤘

**Pull request merged**
