### PR TITLE
fix(@aws-amplify/core): AWS.config.systemClockOffset for signing requ…

### PR DESCRIPTION
**Pull request by thiagohirata**
…ests

_Issue #, if available:_
#2014  #3719 #3699

_Description of changes:_
Signer calls `AWS.util.date.getDate()` instead of `new Date()` - making it possible to correct the signature and headers for the correct date when the system time is wrong by:

```
import { AWS } from '@aws-amplify/core'
AWS.config = new AWS.Config({
    systemClockOffset: CLOCK_OFFSET
})
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by thiagohirata** [comment]
Hi, @Amplifiyer! 
Any chance checking this out?

**Comment by Amplifiyer** [comment]
> Hi, @Amplifiyer!
> Any chance checking this out?

@thiagohirata thanks for submitting the PR. I have a few questions about the implementation and the intended usage.
* How are customers going to calculate CLOCK_OFFSET and pass it to AWS.Config?
* Would it be better to calculate this offset in the signer itself? Such as by reading the data header in the response and calculating the clock drift and setting it again on the retry?

We are also looking to migrate towards aws-sdk V3 which is in preview right now. V3 version doesn't export a global AWS variable or currently has any ways to provide a clockSkew value. This change will then need to be migrated as well when we migrate to V3 of aws-sdk.

**Comment by thiagohirata** [comment]
Hi, @Amplifiyer 

I am not sure if the current version of aws-sdk provides an automatic way to recalculate itself the clock skew. I will check.

Making this process automatic sounds good, but I was expecting that amplify-js would follow the same behaviour as aws-sdk.

This is a current issue here in Brazil - we had in two consecutive years changes in daylight saving time rules (the current rule is that there is no daylight saving time), and there is a bunch of devices with outdated databases. With users manually adjusting the time, but not changing the internal timezone offset, all signatures are automatically expired.

I made a webservice myself to calculate the skew of the client. The requests made with aws-sdk work when I provide this option, but there is no way to make amplify-js work.

Thanks!

**Comment by dorsegal** [comment]
@Amplifiyer 
We applied the fix manually and it worked great.
Any change this merge will happen?

**Comment by dorsegal** [comment]
We found a way to calculate clock offset using aws amplify:
```
Auth.currentAuthenticatedUser({
      bypassCache: true // this will get the latest clockDrift
    }).then(user => {
        AWS.config = new AWS.Config({
          systemClockOffset: -(user.signInUserSession.clockDrift * 1000)
      })
}
```

**Comment by thiagohirata** [comment]
Hi @Amplifiyer!

> @thiagohirata thanks for submitting the PR. I have a few questions about the implementation and the intended usage.
> 
> * How are customers going to calculate CLOCK_OFFSET and pass it to AWS.Config?

I created a webservice that returns the server timestamp, and the client compares it with the browser's date. @dorsegal provided another way.

> * Would it be better to calculate this offset in the signer itself? Such as by reading the data header in the response and calculating the clock drift and setting it again on the retry?

Maybe, but I personally think that it is better to give more alternatives to the user.

> We are also looking to migrate towards aws-sdk V3 which is in preview right now. V3 version doesn't export a global AWS variable or currently has any ways to provide a clockSkew value. This change will then need to be migrated as well when we migrate to V3 of aws-sdk.

Yes, but I don't think this is a blocking reason for not merging this PR, as this solves a problem with current aws-sdk verson - don't you agree?

**Comment by houmark** [comment]
Dear AWS team,

Instead of searching for the perfect long term solution and consider eight different options, when you cannot come up with a solution that solves this issue better than the already ready PR, please respect your customers and their valuable time, by merging the already ready PR. Then you can always improve on the solution later when you come up with a better solution long term.

This issue is potentially affecting thousands of users in the wild and developers using Amplify can spend hours individually searching for why a rare bug like this happens, while you could solve this with a click of a button. There's nothing complex about this PR in any way, so the risk of regression is about non-existent.

LGTM!!!

**Comment by computationalcore** [comment]
@houmark is absolutely correct.  In my case, it is literally affecting thousands of users in a published application. Please, merge it and release ASAP.

**Comment by Amplifiyer** [comment]
I'll look into this PR tomorrow and update.

**Comment by computationalcore** [comment]
> I'll look into this PR tomorrow and update.

Ok, thanks @Amplifiyer

**Comment by Jun711** [comment]
This potentially affect a lot of AWS customers who use AWS_IAM for API authorization.
Some paid users may report to us but new users may just leave our website because the website is not working as expected.

**Comment by Jun711** [comment]
@Amplifiyer @thiagohirata 
I wonder if you could explain what the possible cause of this case. We have asked the user to turn on` set time automatically` on a windows machine but there is still drift issue. Maybe `set time automatically` doesn't set time correctly immediately? 

Error message is 
```
Signature expired: 20200204T203226Z is now earlier than 
20200204T203234Z (20200204T203734Z - 5 min.) .  
```

in har file

**Request**
"startedDateTime": "2020-02-04T20:32:26.801Z",
"time": 134.58600000012666,

header
```
"name": "x-amz-date",
"value": "20200204T203226Z"
```

**Response**
```
 "name": "date",
 "value": "Tue, 04 Feb 2020 20:37:34 GMT"
```

**Comment by Amplifiyer** [comment]
We discussed internally how to ensure that future changes (integrating with [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3)) doesn't break this, we are making small changes(#4844) to this PR to abstract out the `AWS` global variable and exposing a util to handle the clock skew.

We are working on releasing this as soon as possible.

**Comment by ramanasak** [comment]
Hi, @Amplifiyer 

How to give a customized header to Sign-in screen, I have used signUpConfig for sign up screen its working fine but for the sign-in screen, it's not working, 

const signUpConfig = {
  //header: 'My Customized Sign Up',
  header: <HeaderLogo/>,
  hideAllDefaults: true,
  defaultCountryCode: '1',
  Label:{color:'red'},
 
};
const SigninConfig = {
  //header: 'My Customized Sign Up',
  header: <HeaderLogo/>,
  hideAllDefaults: true,
  defaultCountryCode: '1',
  Label:{color:'red'},
};

export default withAuthenticator((connect(mapStateToProps, mapDispatchToProps)(App)),{ signUpConfig },true,[],null,MyTheme);


I am stuck here please help thanks in advance.

**Pull request closed without merging**
