### PR TITLE
Adding AMAZON_COGNITO_USER_POOLS as one of the options for authenticationTypes

### PR DESCRIPTION
**Pull request by ykbryan**
Fixing an issue reporting `[Unhandled promise rejection: TypeError: In this environment the sources for assign MUST be an object. This error is a performance optimization and not spec compliant.]` due to missing **AMAZON_COGNITO_USER_POOLS** as one of the _authenticationTypes_.

screenshot 2018-10-09 17 35 44

### CODE REVIEW

**Comment by Jobel91** [comment]
Thanks for this PR, I'm stuck and I'm waiting for merging... Do you think that I could put this manually? And is there a chance that this PR will not merged?

**Comment by ykbryan** [comment]
@Jobel91 i'm waiting for the merging too. u can definitely put this manually in the node_modules. If any approvers can take a quick look at this, that would be great!

**Comment by elorzafe** [comment]
@ykbryan @Jobel91 

Thanks for the PR, I will review this next week.

**Comment by elorzafe** [comment]
@ykbryan Thanks for your PR

`'x-amz-subscriber-id'` parameter is not required for `AMAZON_COGNITO_USERPOOLS` I merged another PR #2173  that fixes the problem, now you can test this on aws-amplify@unstable 
(aws-amplify@1.1.11-unstable.9)

This will be published on the latest tag next week. 

Thanks again for your PR and feel free to contributing

**Pull request closed without merging**
