### PR TITLE
Update tvOS to supported platform

### PR DESCRIPTION
**Pull request by harashvaradhan**
_Issue #, if available:_

_Description of changes:_
I was facing an issue while using the package on tvOS. Updating work podspec, resolved the issue.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by keshavkaul** [comment]
Any maintainers here? Could anyone review this and merge it, please.

**Comment by mihaiblaga89** [comment]
can this be merged please? Thank you

**Review by amhinson — APPROVED** [review]
LGTM 👍

**Comment by ericclemmons** [comment]
Thanks for your contribution!  We discussed this internally, but for now iOS is supported, but tvOS is not.

Unfortunately, we can't accept this PR without expanding our support & testing.

For now, forking is the best option to move forward.

In the interim, there's a related issue to our iOS SDK that input can be added to:
https://github.com/aws-amplify/aws-sdk-ios/issues/1178

**Pull request closed without merging**
