### PR TITLE
Fix/amplify service rxjs imports

### PR DESCRIPTION
**Pull request by DavidHospital**
_Issue #, if available:_ #2103

_Description of changes:_ Refactor imports from `rxjs/Subject` and `rxjs/Observable` to `rxjs`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by jblakeney** [comment]
:+1:

**Comment by outofgamut** [comment]
@iartemiev @sammartinez can @ericclemmons anything I can do to help out with this fix?

**Comment by ericclemmons** [comment]
👋 This looks good, but conflicts need to be resolved before we can merge in.

**Comment by outofgamut** [comment]
@emonhaider ☝️

**Pull request merged**
