### PR TITLE
Bugfix: Translation and field saving

### PR DESCRIPTION
**Pull request by xavierraffin**
_Issue #, if available:_
fixes: #6521

_Description of changes:_
Now the translation update and the value of the field is taken appropriately in:
* signUp
* signIn
* forgotPassword
* confirmSignUp

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sammartinez** [comment]
@xavierraffin I'm trying to understand, how will this solve for the rerender case for Translations? Or is this looking to solve something else that I may be missing. Thanks ahead of time!

**Comment by xavierraffin** [comment]
OK, the problem come from the fact that `buildFormFields` is called in two cases:

```
  componentWillLoad() {
    checkUsernameAlias(this.usernameAlias);	    
    this.buildFormFields();	    
 }
  @Watch('formFields')	 
  formFieldsHandler() {	 
    this.buildFormFields();	  
 }
```

When the component is build first time + when the formFields are updated (this happen when you change language).

Before PR, if you start entering value in field then change language, the buildFormFields execute and erase the value to the one provided in formFields (empty for example). When you submit the form , because 

Because the behavior (before this PR) is to submit the value in newFormFields  variable the submit fail, complaining for empty value where the field are not empty.

Also it fixes some copy paste error that has been introduce in the initial PR from Jordan (in amplify-forgot-password.tsx the array was not flushed).

**Comment by xavierraffin** [comment]
Excuse me but the bug is still there and this is the fix.
Please let me know if you want anything more on this PR?

**Comment by sammartinez** [comment]
> @sammartinez me but the bug is still there and this is the fix.
> Please let me know if you want anything more on this PR?

Hey @xavierraffin, followed up with you offline on next steps here. Will provide an update from the team once I am able to run this implementation by them.

**Pull request closed without merging**
