### PR TITLE
feat(@aws-amplify/interactions): add session and request attributes t…

### PR DESCRIPTION
**Pull request by aaliakseyenka**
*Description of changes:*
Adds ability to set `sessionAttributes` and `requestAttributes` to Lex provider

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Doradas0** [comment]
Any updates on when this feature will be merged or how I might be able to get around this issue in the meantime?

**Comment by B-DAP** [comment]
Is there a chance of getting this PR revived? I'm currently facing the issue of not be able to pass `sessionAttributes` to Lex. I have not been able to find any other way of passing those attributes. Thanks. @elorzafe

**Comment by faberyx** [comment]
I would like to send `sessionAttributes ` too from amplify, without this feature this client is quite useless unfortunately.

Thanks,  @elorzafe

**Comment by wdevon99** [comment]
> I would like to send `sessionAttributes ` too from amplify, without this feature this client is quite useless unfortunately.
> 
> Thanks, @elorzafe

Agreed! Need this feature urgently! 👍

**Comment by wdevon99** [comment]
> I would like to send `sessionAttributes ` too from amplify, without this feature this client is quite useless unfortunately.
> 
> Thanks, @elorzafe

@elorzafe Did you find a way to do it , any work around ?

**Comment by faberyx** [comment]
> > I would like to send `sessionAttributes ` too from amplify, without this feature this client is quite useless unfortunately.
> > Thanks, @elorzafe
> 
@wdevon99   I ended up using  `@aws-sdk/client-lex-runtime-service` directly.

I ended up with something similar to this.. seems working, you can adapt it to your code maybe, yo can also add the setSession, getSession, deleteSession, postContent requests in a similar way

 ```javascript
import {
  LexRuntimeServiceClient,
  PostTextCommand, 
  PostTextRequest
} from '@aws-sdk/client-lex-runtime-service';

/** Amplify config */
import awsconfig from '../aws-exports';

import { Credentials, getAmplifyUserAgent } from '@aws-amplify/core';
import { LexResponse } from '../interfaces/lexResponse';

export interface LexAttributes {
  [key: string]: string;
}

/**
 * GET AWS SDK CLIENT CREDENTIALS
 */
const getClient = async () => {
  // RETRIEVE CREDENTIALS FROM AMPLIFY
  const credentials = await Credentials.get();
  if (!credentials) {
    return Promise.reject('No credentials');
  }

  // RETRIEVE BOT CONFIGURATION
  const botConfig = awsconfig.aws_bots_config[0];

  // CREATE A CLIENT
  const client = new LexRuntimeServiceClient({
    region: botConfig.region,
    credentials,
    customUserAgent: getAmplifyUserAgent()
  });

  return { client, credentials, botConfig };
};

/**
 * SENDS A TEXT MESSAGE TO LEX
 */
export const sendMessage = async (message: string, sessionAttributes?: LexAttributes, requestAttributes?: LexAttributes): Promise<LexResponse | null> => {
  try {
    // GET THE AWS LEX CLIENT
    const { client, credentials, botConfig } = await getClient();

    // MESSAGE REQUEST PARAMS
    const params: PostTextRequest = {
      botAlias: botConfig.alias,
      botName: botConfig.name,
      inputText: message,
      userId: credentials.identityId
    };

    // ADDS SESSION ATTRIBUTES TO MESSAGE
    if (sessionAttributes) {
      params.sessionAttributes = sessionAttributes;
    }

    // ADDS REQUEST ATTRIBUTES TO MESSAGE
    if (requestAttributes) {
      params.requestAttributes = requestAttributes;
    }

    // CREATE POST TEXT COMMAND
    const postTextCommand = new PostTextCommand(params);

    // AWS LEX API CALL
    return await client.send(postTextCommand);
  } catch (err) {
    console.error(err);
    return null;
  }
};
```

**Comment by wdevon99** [comment]
> > > I would like to send `sessionAttributes ` too from amplify, without this feature this client is quite useless unfortunately.
> > > Thanks, @elorzafe
> 
> @wdevon99 I ended up using `@aws-sdk/client-lex-runtime-service` directly.
> 
> I ended up with something similar to this.. seems working, you can adapt it to your code maybe, you can also add the `setSession`, `getSession`, `deleteSession`, `postContent` requests in a similar way
> 
> ```js
> import {
>  LexRuntimeServiceClient,
>  PostTextCommand, 
>  PostTextRequest
> } from '@aws-sdk/client-lex-runtime-service';
> 
> /** Amplify config */
> import awsconfig from '../aws-exports';
> 
> import { Credentials, getAmplifyUserAgent } from '@aws-amplify/core';
> import { LexResponse } from '../interfaces/lexResponse';
> 
> export interface LexAttributes {
>  [key: string]: string;
> }
> 
> /**
> * GET AWS SDK CLIENT CREDENTIALS
> */
> const getClient = async () => {
>  // RETRIEVE CREDENTIALS FROM AMPLIFY
>  const credentials = await Credentials.get();
>  if (!credentials) {
>    return Promise.reject('No credentials');
>  }
> 
>  // RETRIEVE BOT CONFIGURATION
>  const botConfig = awsconfig.aws_bots_config[0];
> 
>  // CREATE A CLIENT
>  const client = new LexRuntimeServiceClient({
>    region: botConfig.region,
>    credentials,
>    customUserAgent: getAmplifyUserAgent()
>  });
> 
>  return { client, credentials, botConfig };
> };
> 
> /**
> * SENDS A TEXT MESSAGE TO LEX
> */
> export const sendMessage = async (message: string, sessionAttributes?: LexAttributes, requestAttributes?: LexAttributes): Promise<LexResponse | null> => {
>  try {
>    // GET THE AWS LEX CLIENT
>    const { client, credentials, botConfig } = await getClient();
> 
>    // MESSAGE REQUEST PARAMS
>    const params: PostTextRequest = {
>      botAlias: botConfig.alias,
>      botName: botConfig.name,
>      inputText: message,
>      userId: credentials.identityId
>    };
> 
>    // ADDS SESSION ATTRIBUTES TO MESSAGE
>    if (sessionAttributes) {
>      params.sessionAttributes = sessionAttributes;
>    }
> 
>    // ADDS REQUEST ATTRIBUTES TO MESSAGE
>    if (requestAttributes) {
>      params.requestAttributes = requestAttributes;
>    }
> 
>    // CREATE POST TEXT COMMAND
>    const postTextCommand = new PostTextCommand(params);
> 
>    // AWS LEX API CALL
>    return await client.send(postTextCommand);
>  } catch (err) {
>    console.error(err);
>    return null;
>  }
> };
> ```

Thank alot @faberyx

**Comment by wdevon99** [comment]
We could use the  LexRuntime directly as well!

` const lexInstance = await new AWS.LexRuntime({
      region: AwsConstants.LEX_BOT_REGION,
      credentials,
   });
`

**Pull request closed without merging**
