### PR TITLE
feat-config-cognito-endpoint

### PR DESCRIPTION
**Pull request by GeorgeBellTMH**
Adds the ability to repoint the cognito endpoint from aws-exports.js by allowing for setting existing endpoint variable from config.

This will be used for mocking Auth as part of: https://github.com/aws-amplify/amplify-cli/pull/10861

#### Description of how you validated changes

1. Added aws_cognito_endpoint: "https://localhost:20009/cognito" to aws-exports.js and verified that cognito used the configured endpoint. 
2. Removed aws_cognito_endpoint from config and verified it used the original aws cognito endpoint as configured

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#steps-towards-contributions)
- [x] Relevant documentation is changed or added (and PR referenced)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by abdallahshaban557** [comment]
Hi @GeorgeBellTMH - thank you for the contribution to both our repo and the CLI repo. This requires a larger conversation internally for us to enable, but I will keep it open so that we can organize internally and get back to you with next steps! Really appreciate your contribution!

**Comment by GeorgeBellTMH** [comment]
No problem, this ticket definitely resolves the problem of redirecting the url, but the other ticket in the cli requires more work to flesh out all the api results to get to a fully working mock...I did one or two api calls and then ran out of time to complete the rest. The other ticket should be fairly easy for someone to complete if they have the time. Although I understand that maybe there is some refactoring of it that would reduce the number of mock servers etc.

**Comment by abdallahshaban557** [comment]
Gotcha @GeorgeBellTMH - makes total sense! We will get back to you once we have more capacity internally to review your mock implementation. Thank you so much!

**Comment by cwomack** [comment]
Hey there, @GeorgeBellTMH :wave:. In an effort to be transparent and assess our outstanding externally submitted PR’s, we wanted to follow up on this. Both this and the [associated PR on the CLI repo](https://github.com/aws-amplify/amplify-cli/pull/10861) are related to mocking Auth, which is not something we’re looking to prioritize or implement at this point. As such, we close both out for the time being.

As we move forward towards a cloud-based sandbox experience with the upcoming launch of our [Gen 2 Developer Experience](https://docs.amplify.aws/gen2/how-amplify-works/concepts/) of Amplify, it should address the workflow of testing with Auth and API categories in isolated environments.  Note that Gen 2 is currently in developer preview, but our focus is getting it launched for General Availability soon!

**Pull request closed without merging**
